<?php
declare(strict_types=1);session_start();require __DIR__.'/includes/db.php';require __DIR__.'/includes/functions.php';
$token=trim((string)($_GET['token']??$_POST['token']??''));$delivery=null;$error='';$success=false;
if(preg_match('/^[a-f0-9]{64}$/i',$token)){$s=db()->prepare('SELECT d.*,COALESCE(p.project_name,o.project_name) AS project_name,COALESCE(t.requires_acceptance,1) AS requires_acceptance FROM document_deliveries d LEFT JOIN projects p ON p.id=d.project_id LEFT JOIN investment_opportunities o ON o.id=d.investment_opportunity_id LEFT JOIN document_templates t ON t.id=d.template_id WHERE d.token_hash=? LIMIT 1');$s->execute([hash('sha256',$token)]);$delivery=$s->fetch()?:null;}
if(!$delivery||(int)($delivery['requires_acceptance']??0)!==1){http_response_code(404);$error='This agreement link is invalid or no longer available.';}
elseif($_SERVER['REQUEST_METHOD']==='POST'){
 if(!csrf_check($_POST['csrf_token']??''))$error='Your session expired. Please reload the page.';
 elseif($delivery['status']==='accepted')$success=true;
 else{$name=trim((string)($_POST['accepted_name']??''));$agree=isset($_POST['agreement_confirm']);if(strlen($name)<2||!$agree)$error='Enter your full name and confirm that you accept the agreement.';else{$u=db()->prepare("UPDATE document_deliveries SET status='accepted',accepted_at=NOW(),accepted_name=?,accepted_email=recipient_email,accepted_ip=?,accepted_user_agent=? WHERE id=? AND status='sent'");$u->execute([$name,$_SERVER['REMOTE_ADDR']??null,substr((string)($_SERVER['HTTP_USER_AGENT']??''),0,500),$delivery['id']]);$contactType=$delivery['lead_id']?'lead':'inquiry';$contactId=(int)($delivery['lead_id']?:$delivery['inquiry_id']);contact_activity_log($contactType,$contactId,'agreement_accepted','Agreement accepted',$delivery['project_name'].' · Accepted by '.$name,null,(int)$delivery['id']);$success=true;$delivery['status']='accepted';$delivery['accepted_name']=$name;$delivery['accepted_at']=date('Y-m-d H:i:s');}}
}
$isAccepted=$success||($delivery&&strtolower((string)($delivery['status']??''))==='accepted');
$pageTitle='Accept Agreement | ZNP Development';$activePage='';require __DIR__.'/includes/header.php';
?>
<main class="agreement-public"><section class="agreement-card"><div class="agreement-brand">ZNP Development</div><?php if($error):?><h1>Agreement Unavailable</h1><div class="status error"><?=e($error)?></div><?php elseif($isAccepted):?><h1>Agreement Accepted</h1><p>Thank you. Your acceptance of the <strong><?=e($delivery['document_name'])?></strong> for <strong><?=e($delivery['project_name'])?></strong> has been recorded.</p><dl><div><dt>Accepted By</dt><dd><?=e((string)($delivery['accepted_name']??''))?></dd></div><div><dt>Accepted On</dt><dd><?=e(date('F j, Y g:i A',strtotime((string)$delivery['accepted_at'])))?> Central Time</dd></div></dl><?php else:?><h1>Accept Agreement</h1><p>Please review the attached agreement previously emailed to you for <strong><?=e($delivery['project_name'])?></strong>.</p><div class="agreement-meta"><span><?=e($delivery['document_name'])?></span><span>Version <?=e($delivery['template_version'])?></span></div><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="token" value="<?=e($token)?>"><label>Full Legal Name<input name="accepted_name" required autocomplete="name" value="<?=e($delivery['recipient_name'])?>"></label><label class="agreement-check"><input type="checkbox" name="agreement_confirm" value="1" required><span>I have reviewed and accepted the terms of this agreement.</span></label><button class="primary" type="submit">Accept Agreement</button></form><p class="agreement-legal">By selecting Accept Agreement, you are electronically confirming your acceptance. A record of the date, time, name, IP address, and browser information will be retained.</p><?php endif;?></section></main>
<?php require __DIR__.'/includes/footer.php';?>
