<?php
declare(strict_types=1);
require_once __DIR__.'/includes/bootstrap.php';
require_once __DIR__.'/includes/budget.php';
require_once __DIR__.'/includes/expense_tracker.php';
require_once __DIR__.'/includes/contracts.php';
if(!dev_is_super()){http_response_code(403);exit('Budget access denied.');}
$projectId=dev_active_project_id((int)($_GET['project_id']??0));$project=dev_require_project($projectId);dev_ensure_budget_schema();dev_ensure_expense_tracker_schema();dev_ensure_contract_schema();
$budget=dev_budget_for_project($projectId,(int)($user['id']??0));$items=dev_budget_items((int)$budget['id']);$expenses=dev_project_expenses($projectId);$groups=array_values(array_filter(dev_expense_groups($projectId),static fn(array $group):bool=>(string)($group['group_type']??'')!=='ungrouped'));$drawNames=array_map(static fn(array $group):string=>(string)$group['group_name'],$groups);$contracts=dev_contracts($projectId);
$expenseTotals=[];$drawTotals=[];foreach($expenses as $expense){$isContingency=!empty($expense['is_contingency'])||strcasecmp(trim((string)($expense['category']??'')),'Contingency')===0;$itemId=$isContingency?0:(int)($expense['construction_budget_item_id']??0);if(!$isContingency&&!$itemId)continue;$amount=(float)$expense['amount'];$expenseTotals[$itemId]=($expenseTotals[$itemId]??0)+$amount;$group=(string)($expense['grouping_name']??'');if($group!=='')$drawTotals[$itemId][$group]=($drawTotals[$itemId][$group]??0)+$amount;}
$contractTotals=[];$contractRemaining=[];foreach($contracts as $contract){$itemId=(int)($contract['construction_budget_item_id']??0);if(!$itemId)continue;$contractTotals[$itemId]=($contractTotals[$itemId]??0)+(float)$contract['new_contract_amount'];$contractRemaining[$itemId]=($contractRemaining[$itemId]??0)+(float)$contract['total_balance'];}
$rows=[];foreach($items as $item){$itemId=(int)$item['id'];$rows[]=['category'=>(string)$item['category_name'],'item'=>(string)$item['item_name'],'budget'=>(float)$item['amount'],'reallocation'=>(float)($item['reallocated_amount']??0),'spent'=>(float)($expenseTotals[$itemId]??0),'contract_value'=>(float)($contractTotals[$itemId]??0),'contract_remaining'=>(float)($contractRemaining[$itemId]??0),'draws'=>$drawTotals[$itemId]??[],'note'=>(string)($item['reallocation_note']??'')];}
$subtotal=array_sum(array_map(static fn(array $item):float=>(float)$item['amount'],$items));$contingency=$subtotal*((float)($budget['contingency_percent']??5)/100);$rows[]=['category'=>'Project Allowances','item'=>'Contingency','budget'=>$contingency,'reallocation'=>(float)($budget['contingency_reallocated_amount']??0),'spent'=>(float)($expenseTotals[0]??0),'contract_value'=>0.0,'contract_remaining'=>0.0,'draws'=>$drawTotals[0]??[],'note'=>(string)($budget['contingency_reallocation_note']??'')];
$path=dev_build_aia_budget_xlsx((string)$project['project_name'],$rows,$drawNames);$name=preg_replace('/[^A-Za-z0-9._-]+/','-',trim((string)$project['project_name'])).'-budget-cost-schedule.xlsx';header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Length: '.filesize($path));header('Content-Disposition: attachment; filename="'.$name.'"');readfile($path);@unlink($path);exit;
