<?php
require __DIR__.'/includes/bootstrap.php';
$projectId=dev_active_project_id((int)($_GET['project_id']??$_POST['project_id']??0));$p=dev_require_project($projectId);$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{if(!csrf_check((string)($_POST['csrf']??'')))throw new RuntimeException('Your session expired.');$id=(int)($_POST['id']??0);$name=trim((string)($_POST['building_name']??''));if($name==='')throw new RuntimeException('Building name is required.');
  $vals=[$projectId,$name,trim((string)($_POST['building_type']??'')),max(0,(int)($_POST['unit_count']??0)),($_POST['start_date']??'')?:null,($_POST['target_completion_date']??'')?:null,trim((string)($_POST['notes']??''))];
  if($id){$vals[]=$id;db()->prepare('UPDATE construction_buildings SET construction_project_id=?,building_name=?,building_type=?,unit_count=?,start_date=?,target_completion_date=?,notes=?,updated_at=NOW() WHERE id=?')->execute($vals);dev_activity($projectId,'building_updated','Building updated: '.$name,'building',$id);}else{db()->prepare("INSERT INTO construction_buildings(construction_project_id,building_name,building_type,unit_count,start_date,target_completion_date,notes,building_code,site_location,current_phase,percent_complete,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'','','',0,'Planned',NOW(),NOW())")->execute($vals);$id=(int)db()->lastInsertId();dev_initialize_schedule($projectId,$id,'Building',$vals[4]);dev_activity($projectId,'building_created','Building created with default multifamily workflow: '.$name,'building',$id);}header('Location: buildings.php?project_id='.$projectId.'&saved=1');exit;
 }catch(Throwable $e){$error=$e->getMessage();}
}
if(isset($_GET['archive'])){$id=(int)$_GET['archive'];db()->prepare('UPDATE construction_buildings SET is_archived=1 WHERE id=? AND construction_project_id=?')->execute([$id,$projectId]);dev_activity($projectId,'building_archived','Building archived.','building',$id);header('Location: buildings.php?project_id='.$projectId.'&archived=1');exit;}
$edit=null;if(isset($_GET['edit'])){$s=db()->prepare('SELECT * FROM construction_buildings WHERE id=? AND construction_project_id=?');$s->execute([(int)$_GET['edit'],$projectId]);$edit=$s->fetch()?:null;}
$s=db()->prepare('SELECT * FROM construction_buildings WHERE construction_project_id=? AND is_archived=0 ORDER BY building_name');$s->execute([$projectId]);$buildings=$s->fetchAll();
require __DIR__.'/includes/header.php';
?>
<div class="page-head"><div><h1>Buildings</h1><p class="muted"><?=e($p['project_name'])?> · Progress and phase are calculated automatically from each workflow.</p></div><a class="btn btn-primary" href="buildings.php?project_id=<?=$projectId?>&new=1">Add Building</a></div>
<?php if(isset($_GET['saved'])):?><div class="card notice-success">Building saved.</div><?php endif;?><?php if($error):?><div class="card notice-error"><?=e($error)?></div><?php endif;?>
<?php if(isset($_GET['new'])||$edit):?><form method="post" class="card form-grid schedule-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="project_id" value="<?=$projectId?>"><input type="hidden" name="id" value="<?=e((string)($edit['id']??0))?>"><div><label>Building Name / Number</label><input name="building_name" required value="<?=e($edit['building_name']??'')?>"></div><div><label>Building Type</label><input name="building_type" placeholder="4-Plex, Type A, Type B" value="<?=e($edit['building_type']??'')?>"></div><div><label>Unit Count</label><input type="number" min="0" name="unit_count" value="<?=e((string)($edit['unit_count']??0))?>"></div><div><label>Building Start Date</label><input type="date" name="start_date" value="<?=e($edit['start_date']??'')?>"></div><div><label>Target Completion Date</label><input type="date" name="target_completion_date" value="<?=e($edit['target_completion_date']??'')?>"></div><div class="form-full"><label>Notes</label><textarea name="notes"><?=e($edit['notes']??'')?></textarea></div><div class="form-full actions"><button class="primary">Save Building</button><a class="btn btn-secondary" href="buildings.php?project_id=<?=$projectId?>">Cancel</a></div></form><?php endif;?>
<div class="grid grid-3"><?php foreach($buildings as $b):$bid=(int)$b['id'];$progress=dev_schedule_progress($projectId,$bid);$phase=dev_schedule_phase($projectId,$bid);$status=dev_schedule_status($projectId,$bid);?><article class="card building-card"><div class="building-card-head"><span class="badge <?=e(dev_status_class($status))?>"><?=e($status)?></span><strong><?=$progress?>%</strong></div><h2><?=e($b['building_name'])?></h2><p class="muted"><?=e($b['building_type']?:'Building')?> · <?=e((string)$b['unit_count'])?> units</p><div class="progress"><span style="width:<?=$progress?>%"></span></div><dl class="compact-details"><dt>Current Phase</dt><dd><?=e($phase)?></dd><dt>Target</dt><dd><?=e(dev_date($b['target_completion_date']))?></dd></dl><div class="actions"><a class="btn btn-primary" href="schedule.php?project_id=<?=$projectId?>&building_id=<?=$bid?>">Open Workflow</a><a class="btn btn-secondary" href="buildings.php?project_id=<?=$projectId?>&edit=<?=$bid?>">Edit</a><a class="btn btn-danger" data-confirm="Archive this building?" href="buildings.php?project_id=<?=$projectId?>&archive=<?=$bid?>">Archive</a></div></article><?php endforeach;?></div><?php if(!$buildings):?><div class="card empty">No buildings have been added yet.</div><?php endif;?>
<?php require __DIR__.'/includes/footer.php';?>
