<?php
declare(strict_types=1);
require_once __DIR__.'/includes/bootstrap.php';
require_once __DIR__.'/includes/contracts.php';
header('Content-Type: application/json; charset=UTF-8');
try{
    if(!dev_is_super())throw new RuntimeException('Contract access denied.');
    if(!csrf_check((string)($_POST['csrf']??'')))throw new RuntimeException('Session expired. Refresh and try again.');
    $projectId=dev_active_project_id((int)($_POST['project_id']??0));dev_require_project($projectId);dev_ensure_contract_schema();$contractId=(int)($_POST['contract_id']??0);$action=(string)($_POST['action']??'notes');
    $check=db()->prepare('SELECT id FROM construction_contracts WHERE id=? AND construction_project_id=?');$check->execute([$contractId,$projectId]);if(!$check->fetchColumn())throw new RuntimeException('Contract not found.');
    if($action==='assignment'){$assignmentId=(int)($_POST['project_company_id']??0);$assignment=db()->prepare('SELECT trade_role FROM construction_project_companies WHERE id=? AND construction_project_id=?');$assignment->execute([$assignmentId,$projectId]);$linkedTrade=(string)$assignment->fetchColumn();if($linkedTrade==='')throw new RuntimeException('Select an available Project Team trade.');$duplicate=db()->prepare('SELECT id FROM construction_contracts WHERE construction_project_id=? AND construction_project_company_id=? AND id<>?');$duplicate->execute([$projectId,$assignmentId,$contractId]);if($duplicate->fetchColumn())throw new RuntimeException('That Project Team trade is already linked to another contract.');db()->prepare('UPDATE construction_contracts SET construction_project_company_id=? WHERE id=? AND construction_project_id=?')->execute([$assignmentId,$contractId,$projectId]);echo json_encode(['ok'=>true]);exit;}
    if($action==='budget_item'){$budgetItemId=(int)($_POST['construction_budget_item_id']??0);if($budgetItemId){$budgetItem=db()->prepare('SELECT bi.id FROM construction_budget_items bi JOIN construction_project_budgets b ON b.id=bi.construction_project_budget_id WHERE bi.id=? AND b.construction_project_id=?');$budgetItem->execute([$budgetItemId,$projectId]);if(!$budgetItem->fetchColumn())throw new RuntimeException('Select an available budget line item.');}db()->prepare('UPDATE construction_contracts SET construction_budget_item_id=? WHERE id=? AND construction_project_id=?')->execute([$budgetItemId?:null,$contractId,$projectId]);echo json_encode(['ok'=>true]);exit;}
    if($action==='payment')throw new RuntimeException('Contract payments are locked. Modify the linked record in Expense Tracker.');
    if($action==='change_order'){$changeOrderId=(int)($_POST['change_order_id']??0);$number=mb_substr(trim((string)($_POST['change_order_number']??'')),0,50);$description=mb_substr(trim((string)($_POST['description']??'')),0,500);if($description==='')throw new RuntimeException('Change order description is required.');$amount=(float)str_replace([',','$'],'',(string)($_POST['amount']??0));$date=trim((string)($_POST['change_order_date']??''));if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date))throw new RuntimeException('Enter a valid change-order date.');$changeOrder=db()->prepare('SELECT co.id FROM construction_contract_change_orders co JOIN construction_contracts ct ON ct.id=co.construction_contract_id WHERE co.id=? AND co.construction_contract_id=? AND ct.construction_project_id=?');$changeOrder->execute([$changeOrderId,$contractId,$projectId]);if(!$changeOrder->fetchColumn())throw new RuntimeException('Change order not found.');db()->prepare('UPDATE construction_contract_change_orders SET change_order_number=?,description=?,amount=?,change_order_date=? WHERE id=? AND construction_contract_id=?')->execute([$number,$description,$amount,$date,$changeOrderId,$contractId]);echo json_encode(['ok'=>true]);exit;}
    $notes=mb_substr(trim((string)($_POST['notes']??'')),0,10000);db()->prepare('UPDATE construction_contracts SET notes=? WHERE id=? AND construction_project_id=?')->execute([$notes,$contractId,$projectId]);echo json_encode(['ok'=>true]);
}catch(Throwable $exception){http_response_code(422);echo json_encode(['ok'=>false,'message'=>$exception->getMessage()?:'The contract notes could not be saved.']);}
