<?php
require __DIR__.'/includes/header.php';$p=dev_require_project($projectId);$error='';
if($_SERVER['REQUEST_METHOD']==='POST')try{if(!csrf_check((string)$_POST['csrf']))throw new RuntimeException('Session expired.');$up=dev_compress_image($_FILES['photo'],'photos');if(!$up)throw new RuntimeException('Choose a photo.');$s=db()->prepare('INSERT INTO construction_photos(construction_project_id,admin_user_id,file_path,original_name,caption,taken_on,created_at) VALUES(?,?,?,?,?,?,NOW())');$s->execute([$projectId,$user['id'],$up['path'],$up['name'],trim((string)$_POST['caption']),($_POST['taken_on']??'')?:date('Y-m-d')]);$id=(int)db()->lastInsertId();dev_activity($projectId,'photo_uploaded','Progress photo uploaded: '.$up['name'],'photo',$id);header("Location: photos.php?project_id=$projectId");exit;}catch(Throwable $e){$error=$e->getMessage();}
$s=db()->prepare('SELECT ph.*,au.full_name FROM construction_photos ph LEFT JOIN admin_users au ON au.id=ph.admin_user_id WHERE ph.construction_project_id=? ORDER BY ph.taken_on DESC,ph.id DESC');$s->execute([$projectId]);$rows=$s->fetchAll();
try{$d=db()->prepare("SELECT dlp.*,dl.log_date taken_on,CONCAT('Daily Log · ',DATE_FORMAT(dl.log_date,'%b %e, %Y')) caption,au.full_name FROM construction_daily_log_photos dlp JOIN construction_daily_logs dl ON dl.id=dlp.daily_log_id LEFT JOIN admin_users au ON au.id=dl.admin_user_id WHERE dlp.construction_project_id=? ORDER BY dl.log_date DESC,dlp.id DESC");$d->execute([$projectId]);$rows=array_merge($rows,$d->fetchAll());usort($rows,fn($a,$b)=>strcmp((string)$b['taken_on'],(string)$a['taken_on']));}catch(Throwable $e){error_log('Daily Log photos could not be included in Progress Photos: '.$e->getMessage());}
?>
<div class="page-head"><div><h1>Progress Photos</h1><p class="muted"><?=e($p['project_name'])?> · Includes Daily Log photos automatically</p></div></div><?php if($error):?><div class="card notice-error"><?=e($error)?></div><?php endif;?>
<form method="post" enctype="multipart/form-data" class="card form-grid" data-heic-upload-form><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="project_id" value="<?=$projectId?>"><div><label>Photo</label><input type="file" name="photo" accept="image/jpeg,image/png,image/webp,image/heic,image/heif,.heic,.heif" required data-heic-input><small class="muted">HEIC/HEIF is converted to JPEG in your browser before upload.</small><div class="heic-upload-status muted" data-heic-status aria-live="polite"></div></div><div><label>Date Taken</label><input type="date" name="taken_on" value="<?=date('Y-m-d')?>"></div><div class="form-full"><label>Caption</label><input name="caption"></div><div class="form-full"><button class="primary">Upload Photo</button></div></form>
<div class="photo-grid" style="margin-top:20px"><?php foreach($rows as $r):?><article class="card photo-card"><img src="../<?=e($r['file_path'])?>" alt=""><h3><?=e($r['caption']?:$r['original_name'])?></h3><small><?=e(dev_date($r['taken_on']))?> · <?=e($r['full_name']?:'User')?></small></article><?php endforeach;?></div><script src="https://cdnjs.cloudflare.com/ajax/libs/heic2any/0.0.4/heic2any.min.js" defer></script><script src="assets/heic-upload.js?v=1.0.0" defer></script><?php require __DIR__.'/includes/footer.php';?>
