<?php
require __DIR__.'/includes/bootstrap.php';
$projectId=dev_active_project_id((int)($_GET['project_id']??$_POST['project_id']??0));$p=dev_require_project($projectId);$buildingId=(int)($_GET['building_id']??$_POST['building_id']??0);$building=null;$scope='Project';
$canManageWorkflow=dev_is_super();
if($buildingId){$s=db()->prepare('SELECT * FROM construction_buildings WHERE id=? AND construction_project_id=? AND is_archived=0');$s->execute([$buildingId,$projectId]);$building=$s->fetch();if(!$building){http_response_code(404);exit('Building not found.');}$scope='Building';}
$error='';$baseUrl='schedule.php?project_id='.$projectId.($buildingId?'&building_id='.$buildingId:'');
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  if(!csrf_check((string)($_POST['csrf']??'')))throw new RuntimeException('Your session expired.');$action=(string)($_POST['action']??'save');
  if(!in_array($action,['complete','batch_complete'],true)&&!$canManageWorkflow)throw new RuntimeException('Only a Super Admin may change workflow activities.');
  if($action==='initialize'){dev_initialize_schedule($projectId,$buildingId?:null,$scope,$building['start_date']??$p['start_date']??null);header('Location: '.$baseUrl.'&initialized=1');exit;}
  elseif($action==='add'){$max=db()->prepare('SELECT COALESCE(MAX(sequence_no),0)+1 FROM construction_schedule_items WHERE construction_project_id=? AND '.($buildingId?'construction_building_id=?':'construction_building_id IS NULL'));$args=[$projectId];if($buildingId)$args[]=$buildingId;$max->execute($args);$seq=(int)$max->fetchColumn();$name=trim((string)($_POST['activity_name']??''));if($name==='')throw new RuntimeException('Activity name is required.');$u=admin_user();db()->prepare('INSERT INTO construction_schedule_items(construction_project_id,construction_building_id,schedule_scope,sequence_no,activity_name,status,percent_complete,is_inspection,created_by_admin_user_id,created_at,updated_at) VALUES(?,?,?,?,?,?,0,?,?,NOW(),NOW())')->execute([$projectId,$buildingId?:null,$scope,$seq,$name,'Not Started',!empty($_POST['is_inspection'])?1:0,$u['id']??null]);dev_activity($projectId,'schedule_item_added',$scope.' workflow activity added: '.$name,'schedule_item',(int)db()->lastInsertId());}
  elseif($action==='complete'){$id=(int)($_POST['id']??0);$date=($_POST['completion_date']??'')?:date('Y-m-d');$q=db()->prepare('SELECT activity_name FROM construction_schedule_items WHERE id=? AND construction_project_id=?');$q->execute([$id,$projectId]);$name=(string)$q->fetchColumn();if($name==='')throw new RuntimeException('Activity not found.');$u=admin_user();db()->prepare("UPDATE construction_schedule_items SET status='Complete',percent_complete=100,actual_start_date=COALESCE(actual_start_date,?),actual_finish_date=?,inspection_result=?,completion_notes=?,completed_by_admin_user_id=?,updated_at=NOW() WHERE id=? AND construction_project_id=?")->execute([$date,$date,trim((string)($_POST['inspection_result']??'')),trim((string)($_POST['completion_notes']??'')),$u['id']??null,$id,$projectId]);
   $uploads=dev_upload_many($_FILES['attachments']??[], 'schedule-activity', ['pdf','doc','docx','xls','xlsx','jpg','jpeg','png','webp'],15728640);$ins=db()->prepare('INSERT INTO construction_schedule_attachments(schedule_item_id,file_path,original_filename,mime_type,file_size,uploaded_by_admin_user_id,created_at) VALUES(?,?,?,?,?,?,NOW())');foreach($uploads as $f)$ins->execute([$id,$f['path'],$f['name'],$f['mime'],$f['size'],$u['id']??null]);dev_activity($projectId,'schedule_item_completed',$scope.' activity completed: '.$name,'schedule_item',$id);header('Location: '.$baseUrl.'&completed=1');exit;}
  elseif($action==='batch_complete'){
   $ids=array_values(array_unique(array_filter(array_map('intval',is_array($_POST['item_ids']??null)?$_POST['item_ids']:[]),static fn($id)=>$id>0)));
   if(!$ids)throw new RuntimeException('Select at least one activity to complete.');
   $date=trim((string)($_POST['completion_date']??date('Y-m-d')));if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date))throw new RuntimeException('Choose a valid completion date.');
   $marks=implode(',',array_fill(0,count($ids),'?'));$scopeSql=$buildingId?'construction_building_id=?':'construction_building_id IS NULL';$args=[$projectId];if($buildingId)$args[]=$buildingId;$args=array_merge($args,$ids);
   $q=db()->prepare("SELECT id,activity_name FROM construction_schedule_items WHERE construction_project_id=? AND $scopeSql AND status<>'Complete' AND id IN ($marks)");$q->execute($args);$selected=$q->fetchAll();
   if(count($selected)!==count($ids))throw new RuntimeException('One or more selected activities are no longer available in this workflow.');
   $u=admin_user();$update=db()->prepare("UPDATE construction_schedule_items SET status='Complete',percent_complete=100,actual_start_date=COALESCE(actual_start_date,?),actual_finish_date=?,completed_by_admin_user_id=?,updated_at=NOW() WHERE id=? AND construction_project_id=?");
   db()->beginTransaction();try{foreach($selected as $item){$id=(int)$item['id'];$update->execute([$date,$date,$u['id']??null,$id,$projectId]);dev_activity($projectId,'schedule_item_completed',$scope.' activity completed: '.$item['activity_name'],'schedule_item',$id);}db()->commit();}catch(Throwable $batchError){if(db()->inTransaction())db()->rollBack();throw $batchError;}
   header('Location: '.$baseUrl.'&batch_completed='.count($selected));exit;
  }
  elseif($action==='reopen'){$id=(int)($_POST['id']??0);$q=db()->prepare('SELECT activity_name FROM construction_schedule_items WHERE id=? AND construction_project_id=?');$q->execute([$id,$projectId]);$name=(string)$q->fetchColumn();db()->prepare("UPDATE construction_schedule_items SET status='In Progress',percent_complete=0,actual_finish_date=NULL,completed_by_admin_user_id=NULL,updated_at=NOW() WHERE id=? AND construction_project_id=?")->execute([$id,$projectId]);dev_activity($projectId,'schedule_item_reopened',$scope.' activity reopened: '.$name,'schedule_item',$id);header('Location: '.$baseUrl.'&reopened=1');exit;}
  elseif($action==='delete'){$id=(int)($_POST['id']??0);$q=db()->prepare('SELECT activity_name FROM construction_schedule_items WHERE id=? AND construction_project_id=?');$q->execute([$id,$projectId]);$name=(string)$q->fetchColumn();if($name==='')throw new RuntimeException('Activity not found.');db()->prepare('DELETE FROM construction_schedule_items WHERE id=? AND construction_project_id=?')->execute([$id,$projectId]);dev_activity($projectId,'schedule_item_deleted',$scope.' workflow activity deleted: '.$name,'schedule_item',$id);header('Location: '.$baseUrl.'&deleted=1');exit;}
  else{$id=(int)($_POST['id']??0);$name=trim((string)($_POST['activity_name']??''));$status=trim((string)($_POST['status']??'Not Started'));$pct=max(0,min(100,(int)($_POST['percent_complete']??0)));db()->prepare('UPDATE construction_schedule_items SET activity_name=?,planned_start_date=?,planned_finish_date=?,actual_start_date=?,status=?,percent_complete=?,responsible_party=?,inspection_result=?,delay_reason=?,notes=?,is_inspection=?,updated_at=NOW() WHERE id=? AND construction_project_id=?')->execute([$name,($_POST['planned_start_date']??'')?:null,($_POST['planned_finish_date']??'')?:null,($_POST['actual_start_date']??'')?:null,$status,$pct,trim((string)($_POST['responsible_party']??'')),trim((string)($_POST['inspection_result']??'')),trim((string)($_POST['delay_reason']??'')),trim((string)($_POST['notes']??'')),!empty($_POST['is_inspection'])?1:0,$id,$projectId]);dev_activity($projectId,'schedule_item_updated',$scope.' activity updated: '.$name,'schedule_item',$id);}
  header('Location: '.$baseUrl.'&saved=1');exit;
 }catch(Throwable $e){$error=$e->getMessage();}
}
$sql="SELECT csi.*,au.full_name completed_by_name FROM construction_schedule_items csi LEFT JOIN admin_users au ON au.id=csi.completed_by_admin_user_id WHERE csi.construction_project_id=? AND ".($buildingId?'csi.construction_building_id=?':'csi.construction_building_id IS NULL').' ORDER BY csi.sequence_no,csi.id';$s=db()->prepare($sql);$args=[$projectId];if($buildingId)$args[]=$buildingId;$s->execute($args);$items=$s->fetchAll();$active=array_values(array_filter($items,fn($x)=>$x['status']!=='Complete'));$completed=array_values(array_filter($items,fn($x)=>$x['status']==='Complete'));$progress=dev_schedule_progress($projectId,$buildingId?:null);$editId=$canManageWorkflow?(int)($_GET['edit']??0):0;
$att=[];if($completed){$ids=array_column($completed,'id');$ph=implode(',',array_fill(0,count($ids),'?'));$a=db()->prepare("SELECT * FROM construction_schedule_attachments WHERE schedule_item_id IN ($ph) ORDER BY created_at");$a->execute($ids);foreach($a->fetchAll() as $f)$att[(int)$f['schedule_item_id']][]=$f;}
require __DIR__.'/includes/header.php';
?>
<div class="page-head"><div><h1><?=$building?e($building['building_name']).' Construction Workflow':'Master Project Workflow'?></h1><p class="muted"><?=e($p['project_name'])?> · Active work stays visible; completed work is archived below.</p></div><div class="actions no-top"><a class="btn btn-secondary" href="buildings.php?project_id=<?=$projectId?>">Buildings</a><?php if($canManageWorkflow):?><a class="btn btn-primary" href="<?=$baseUrl?>&add=1">Add Activity</a><?php endif;?></div></div>
<div class="grid grid-4 schedule-summary"><div class="card metric"><strong><?=$progress?>%</strong><span>Complete</span></div><div class="card metric"><strong><?=count($active)?></strong><span>Active Work</span></div><div class="card metric"><strong><?=count($completed)?></strong><span>Completed</span></div><div class="card metric"><strong><?=count(array_filter($active,fn($x)=>!empty($x['planned_finish_date'])&&$x['planned_finish_date']<date('Y-m-d')))?></strong><span>Late</span></div></div>
<?php if($error):?><div class="card notice-error"><?=e($error)?></div><?php endif;?>
<?php if($canManageWorkflow&&isset($_GET['add'])):?><form method="post" class="card inline-add"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="project_id" value="<?=$projectId?>"><input type="hidden" name="building_id" value="<?=$buildingId?>"><input type="hidden" name="action" value="add"><div><label>New Activity</label><input name="activity_name" required></div><label class="inline-check"><input type="checkbox" name="is_inspection" value="1"> Inspection</label><button class="primary">Add Activity</button></form><?php endif;?>
<?php if(!$items):?><div class="card empty"><p>No workflow activities yet.</p><?php if($canManageWorkflow):?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="project_id" value="<?=$projectId?>"><input type="hidden" name="building_id" value="<?=$buildingId?>"><input type="hidden" name="action" value="initialize"><button class="btn btn-primary" type="submit">Load Default <?=e($scope)?> Workflow</button></form><?php endif;?></div><?php endif;?>
<?php if($active):?><section><div class="workflow-section-head"><h2 class="section-title">Active Work<?=$building?' - '.e($building['building_name']):''?></h2><form id="workflow-batch-complete" method="post" class="workflow-batch-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="project_id" value="<?=$projectId?>"><input type="hidden" name="building_id" value="<?=$buildingId?>"><input type="hidden" name="action" value="batch_complete"><label class="workflow-select-all"><input type="checkbox" data-workflow-select-all data-form="workflow-batch-complete"> Select All</label><label class="workflow-batch-date">Completed <input type="date" name="completion_date" value="<?=date('Y-m-d')?>" required></label><button type="submit" class="btn btn-complete" data-workflow-batch-submit disabled data-confirm="Mark all selected activities as complete?">Mark Selected Complete (<span data-workflow-selected-count>0</span>)</button></form></div><div class="workflow-list"><?php foreach($active as $it):$late=!empty($it['planned_finish_date'])&&$it['planned_finish_date']<date('Y-m-d');?><article class="card workflow-card <?=$late?'workflow-late':''?> <?=!empty($it['is_inspection'])?'workflow-inspection':''?>"><div class="workflow-main"><label class="workflow-select-item" title="Select <?=e($it['activity_name'])?>"><input type="checkbox" name="item_ids[]" value="<?=(int)$it['id']?>" form="workflow-batch-complete" data-workflow-select><span class="sr-only">Select <?=e($it['activity_name'])?></span></label><div class="workflow-seq"><?=e((string)$it['sequence_no'])?></div><div><h3><?=e($it['activity_name'])?></h3><div class="workflow-meta"><span>Due <?=e(dev_date($it['planned_finish_date']))?></span><span><?=e($it['responsible_party']?:'Unassigned')?></span><span class="badge <?=e(dev_status_class($it['status']))?>"><?=e($it['status'])?></span></div></div></div><div class="workflow-actions"><?php if($canManageWorkflow):?><a class="btn btn-secondary btn-small" href="<?=$baseUrl?>&edit=<?=$it['id']?>#edit-<?=$it['id']?>">Edit</a><?php endif;?><button type="button" class="btn btn-complete btn-small" data-open-modal="complete-<?=$it['id']?>">Mark as Complete</button></div></article>
<div class="dev-modal" id="complete-<?=$it['id']?>" hidden><div class="dev-modal-panel"><button class="modal-close" type="button" data-close-modal aria-label="Close">×</button><h2>Complete Activity</h2><p><strong><?=e($it['activity_name'])?></strong></p><form method="post" enctype="multipart/form-data" class="form-grid"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="project_id" value="<?=$projectId?>"><input type="hidden" name="building_id" value="<?=$buildingId?>"><input type="hidden" name="action" value="complete"><input type="hidden" name="id" value="<?=$it['id']?>"><div><label>Completion Date</label><input type="date" name="completion_date" value="<?=date('Y-m-d')?>" required></div><div><label>Inspection Result</label><select name="inspection_result"><option value="">Not Applicable / Pending</option><option>Passed</option><option>Failed</option><option>Partial</option><option>Reinspection Required</option></select></div><div class="form-full"><label>Completion Notes</label><textarea name="completion_notes" placeholder="Optional completion details"></textarea></div><div class="form-full"><label>Photos or Documents</label><input type="file" name="attachments[]" multiple accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png,.webp"><small class="muted">Optional. Up to 15 MB per file.</small></div><div class="form-full actions"><button class="primary">Complete Activity</button><button type="button" class="btn btn-secondary" data-close-modal>Cancel</button></div></form></div></div>
<?php if($canManageWorkflow&&$editId===(int)$it['id']):?><form id="edit-<?=$it['id']?>" method="post" class="card form-grid schedule-edit"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="project_id" value="<?=$projectId?>"><input type="hidden" name="building_id" value="<?=$buildingId?>"><input type="hidden" name="id" value="<?=$it['id']?>"><div class="form-full"><label>Activity</label><input name="activity_name" value="<?=e($it['activity_name'])?>"></div><div><label>Planned Start</label><input type="date" name="planned_start_date" value="<?=e($it['planned_start_date']??'')?>"></div><div><label>Planned Finish</label><input type="date" name="planned_finish_date" value="<?=e($it['planned_finish_date']??'')?>"></div><div><label>Actual Start</label><input type="date" name="actual_start_date" value="<?=e($it['actual_start_date']??'')?>"></div><div><label class="inline-check"><input type="checkbox" name="is_inspection" value="1" <?=!empty($it['is_inspection'])?'checked':''?>> Inspection Item</label></div><div><label>Status</label><select name="status"><?php foreach(['Not Started','In Progress','Inspection','On Hold'] as $v):?><option <?=$it['status']===$v?'selected':''?>><?=$v?></option><?php endforeach;?></select></div><div><label>Percent Complete</label><input type="number" min="0" max="99" name="percent_complete" value="<?=e((string)$it['percent_complete'])?>"></div><div><label>Trade / Responsible Party</label><input name="responsible_party" value="<?=e($it['responsible_party']??'')?>"></div><div><label>Inspection Result</label><select name="inspection_result"><option value="">Not Applicable / Pending</option><?php foreach(['Passed','Failed','Partial','Reinspection Required'] as $v):?><option <?=$it['inspection_result']===$v?'selected':''?>><?=$v?></option><?php endforeach;?></select></div><div class="form-full"><label>Delay Reason</label><textarea name="delay_reason"><?=e($it['delay_reason']??'')?></textarea></div><div class="form-full"><label>Notes</label><textarea name="notes"><?=e($it['notes']??'')?></textarea></div><div class="form-full actions"><button class="primary">Save Activity</button><a class="btn btn-secondary" href="<?=$baseUrl?>">Cancel</a><button class="btn btn-danger" name="action" value="delete" formnovalidate data-confirm="Delete this workflow activity?">Delete Activity</button></div></form><?php endif;?><?php endforeach;?></div></section><?php endif;?>
<section class="completed-section"><button class="completed-toggle" type="button" aria-expanded="false" data-toggle-completed><span>Completed (<?=count($completed)?>)</span><span class="toggle-arrow">▸</span></button><div class="completed-list" hidden><?php foreach($completed as $it):?><article class="card completed-card"><div><h3>✓ <?=e($it['activity_name'])?></h3><p class="muted">Completed <?=e(dev_date($it['actual_finish_date']))?><?=!empty($it['completed_by_name'])?' by '.e($it['completed_by_name']):''?></p><?php if($it['completion_notes']):?><p><?=nl2br(e($it['completion_notes']))?></p><?php endif;?><?php if(!empty($att[(int)$it['id']])):?><div class="attachment-list"><?php foreach($att[(int)$it['id']] as $f):?><a href="schedule_file.php?id=<?=$f['id']?>" target="_blank">📎 <?=e($f['original_filename'])?></a><?php endforeach;?></div><?php endif;?></div><?php if($canManageWorkflow):?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="project_id" value="<?=$projectId?>"><input type="hidden" name="building_id" value="<?=$buildingId?>"><input type="hidden" name="action" value="reopen"><input type="hidden" name="id" value="<?=$it['id']?>"><button class="btn btn-secondary btn-small" data-confirm="Reopen this activity?">Reopen</button></form><?php endif;?></article><?php endforeach;?><?php if(!$completed):?><div class="card empty">No completed activities yet.</div><?php endif;?></div></section>
<?php require __DIR__.'/includes/footer.php';?>
