<?php
require_once __DIR__.'/includes/bootstrap.php';
if(!dev_is_super()){http_response_code(403);exit('Administrator access required.');}
$id=(int)($_GET['id']??$_POST['company_id']??0);if($id<1){header('Location: companies.php');exit;}
$error='';$saved=isset($_GET['saved']);
if($_SERVER['REQUEST_METHOD']==='POST')try{
 if(!csrf_check((string)($_POST['csrf']??'')))throw new RuntimeException('Session expired.');
 $action=(string)($_POST['action']??'');
 if($action==='save_company')db()->prepare('UPDATE construction_companies SET company_name=?,primary_contact=?,cell_phone=?,email=?,updated_at=NOW() WHERE id=?')->execute([trim($_POST['company_name']),trim($_POST['primary_contact']),trim($_POST['cell_phone']),trim($_POST['email']),$id]);
 elseif($action==='add_contact'){db()->prepare('INSERT INTO construction_vendor_contacts(construction_company_id,name,title,phone,email,is_primary,is_active,created_at,updated_at) VALUES(?,?,?,?,?,?,1,NOW(),NOW())')->execute([$id,trim($_POST['name']),trim($_POST['title']),trim($_POST['phone']),trim($_POST['email']),isset($_POST['is_primary'])?1:0]);if(isset($_POST['is_primary'])){ $new=(int)db()->lastInsertId();db()->prepare('UPDATE construction_vendor_contacts SET is_primary=(id=?) WHERE construction_company_id=?')->execute([$new,$id]);}}
 elseif($action==='save_compliance'){db()->prepare('INSERT INTO construction_vendor_compliance(construction_company_id,insurance_status,insurance_expiration,insurance_verified_at,insurance_verified_by,w9_status,w9_verified_at,w9_verified_by,notes,updated_at) VALUES(?,?,?,?,?,?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE insurance_status=VALUES(insurance_status),insurance_expiration=VALUES(insurance_expiration),insurance_verified_at=VALUES(insurance_verified_at),insurance_verified_by=VALUES(insurance_verified_by),w9_status=VALUES(w9_status),w9_verified_at=VALUES(w9_verified_at),w9_verified_by=VALUES(w9_verified_by),notes=VALUES(notes),updated_at=NOW()')->execute([$id,$_POST['insurance_status'],$_POST['insurance_expiration']?:null,$_POST['insurance_status']==='Verified'?date('Y-m-d H:i:s'):null,$_POST['insurance_status']==='Verified'?(int)(admin_user()['id']??0):null,$_POST['w9_status'],$_POST['w9_status']==='On File'?date('Y-m-d H:i:s'):null,$_POST['w9_status']==='On File'?(int)(admin_user()['id']??0):null,trim($_POST['notes'])]);}
 header('Location: vendor_profile.php?id='.$id.'&saved=1');exit;
}catch(Throwable $e){$error=$e->getMessage();}
require __DIR__.'/includes/header.php';
$s=db()->prepare('SELECT * FROM construction_companies WHERE id=?');$s->execute([$id]);$vendor=$s->fetch();if(!$vendor){http_response_code(404);exit('Vendor not found.');}
try{$s=db()->prepare('SELECT * FROM construction_vendor_contacts WHERE construction_company_id=? AND is_active=1 ORDER BY is_primary DESC,name');$s->execute([$id]);$contacts=$s->fetchAll();$s=db()->prepare('SELECT * FROM construction_vendor_compliance WHERE construction_company_id=?');$s->execute([$id]);$compliance=$s->fetch()?:[];}catch(Throwable $e){$contacts=[];$compliance=[];$error=$error?:'Run the v3.4 installer to enable contacts and compliance.';}
try{$s=db()->prepare('SELECT t.trade_name FROM construction_company_trades ct JOIN construction_trades t ON t.id=ct.construction_trade_id WHERE ct.construction_company_id=? ORDER BY t.display_order,t.trade_name');$s->execute([$id]);$trades=$s->fetchAll(PDO::FETCH_COLUMN);}catch(Throwable $e){$trades=[];}
?>
<div class="page-head"><div><a href="companies.php" class="muted">← Vendors</a><h1><?=e($vendor['company_name'])?></h1><p class="muted"><?=e(implode(' · ',$trades))?></p></div></div>
<?php if($saved):?><div class="card notice-success">Vendor profile saved.</div><?php endif;?><?php if($error):?><div class="card notice-error"><?=e($error)?></div><?php endif;?>
<div class="grid grid-2"><section class="card"><h2>Vendor Information</h2><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="company_id" value="<?=$id?>"><input type="hidden" name="action" value="save_company"><div class="form-full"><label>Company</label><input name="company_name" value="<?=e($vendor['company_name'])?>" required></div><div><label>Primary Contact</label><input name="primary_contact" value="<?=e($vendor['primary_contact'])?>"></div><div><label>Phone</label><input name="cell_phone" value="<?=e($vendor['cell_phone'])?>"></div><div class="form-full"><label>Email</label><input type="email" name="email" value="<?=e($vendor['email'])?>"></div><div class="form-full"><button class="primary">Save Vendor</button></div></form></section>
<section class="card"><h2>Compliance</h2><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="company_id" value="<?=$id?>"><input type="hidden" name="action" value="save_compliance"><div><label>Insurance</label><select name="insurance_status"><option>Missing</option><option <?=($compliance['insurance_status']??'')==='Verified'?'selected':''?>>Verified</option><option <?=($compliance['insurance_status']??'')==='Expired'?'selected':''?>>Expired</option></select></div><div><label>Expiration Date</label><input type="date" name="insurance_expiration" value="<?=e($compliance['insurance_expiration']??'')?>"></div><div><label>W-9</label><select name="w9_status"><option>Missing</option><option <?=($compliance['w9_status']??'')==='On File'?'selected':''?>>On File</option></select></div><div class="form-full"><label>Compliance Notes</label><textarea name="notes"><?=e($compliance['notes']??'')?></textarea></div><div class="form-full"><button class="primary">Save Compliance</button></div></form></section></div>
<section class="card" style="margin-top:20px"><div class="section-heading"><h2>Contacts</h2><button class="btn btn-primary" data-open-modal="contact-modal">Add Contact</button></div><div class="table-scroll"><table><thead><tr><th>Name</th><th>Role</th><th>Phone</th><th>Email</th><th>Primary</th></tr></thead><tbody><?php foreach($contacts as $c):?><tr><td><?=e($c['name'])?></td><td><?=e($c['title']?:'—')?></td><td><?php if($c['phone']):?><a href="tel:<?=e(preg_replace('/\D+/','',$c['phone']))?>"><?=e($c['phone'])?></a><?php else:?>—<?php endif;?></td><td><?php if($c['email']):?><a href="mailto:<?=e($c['email'])?>"><?=e($c['email'])?></a><?php else:?>—<?php endif;?></td><td><?=$c['is_primary']?'Yes':'—'?></td></tr><?php endforeach;?></tbody></table></div></section>
<div class="dev-modal" id="contact-modal" hidden><div class="dev-modal-panel"><button class="modal-close" data-close-modal>×</button><h2>Add Contact</h2><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="company_id" value="<?=$id?>"><input type="hidden" name="action" value="add_contact"><div><label>Name</label><input name="name" required></div><div><label>Role / Title</label><input name="title"></div><div><label>Phone</label><input name="phone"></div><div><label>Email</label><input type="email" name="email"></div><div class="form-full"><label><input type="checkbox" name="is_primary" value="1"> Primary contact</label></div><div class="form-full"><button class="primary">Add Contact</button></div></form></div></div>
<?php require __DIR__.'/includes/footer.php';?>
