<?php
require_once __DIR__.'/includes/bootstrap.php';
if(!dev_is_super()){http_response_code(403);exit('Administrator access required.');}
$id=(int)($_GET['id']??$_POST['company_id']??0);if($id<1){header('Location: companies.php');exit;}
$error='';$saved=isset($_GET['saved']);
if($_SERVER['REQUEST_METHOD']==='POST')try{
 if(!csrf_check((string)($_POST['csrf']??'')))throw new RuntimeException('Session expired.');
 $action=(string)($_POST['action']??'');
 if($action==='save_company')db()->prepare('UPDATE construction_companies SET company_name=?,primary_contact=?,cell_phone=?,email=?,updated_at=NOW() WHERE id=?')->execute([trim($_POST['company_name']),trim($_POST['primary_contact']),trim($_POST['cell_phone']),trim($_POST['email']),$id]);
 elseif($action==='save_trade'){
  $linkId=(int)($_POST['link_id']??0);$tradeId=(int)($_POST['trade_id']??0);if($linkId<1||$tradeId<1)throw new RuntimeException('Select a valid trade.');
  $q=db()->prepare('UPDATE construction_company_trades SET construction_trade_id=?,updated_at=NOW() WHERE id=? AND construction_company_id=? AND archived_at IS NULL');$q->execute([$tradeId,$linkId,$id]);if(!$q->rowCount()){ $check=db()->prepare('SELECT 1 FROM construction_company_trades WHERE id=? AND construction_company_id=? AND archived_at IS NULL');$check->execute([$linkId,$id]);if(!$check->fetchColumn())throw new RuntimeException('Vendor trade was not found.');}
 }
 elseif($action==='add_trade'){
  $tradeId=(int)($_POST['trade_id']??0);if($tradeId<1)throw new RuntimeException('Select a valid trade.');
  db()->prepare('INSERT INTO construction_company_trades(construction_company_id,construction_trade_id,created_at,updated_at) VALUES(?,?,NOW(),NOW())')->execute([$id,$tradeId]);
 }
 elseif($action==='archive_trade'){
  $linkId=(int)($_POST['link_id']??0);$q=db()->prepare('UPDATE construction_company_trades SET archived_at=NOW(),updated_at=NOW() WHERE id=? AND construction_company_id=? AND archived_at IS NULL');$q->execute([$linkId,$id]);if(!$q->rowCount())throw new RuntimeException('Vendor trade was not found or is already archived.');
 }
 elseif($action==='restore_trade'){
  $linkId=(int)($_POST['link_id']??0);$q=db()->prepare('UPDATE construction_company_trades SET archived_at=NULL,updated_at=NOW() WHERE id=? AND construction_company_id=? AND archived_at IS NOT NULL');$q->execute([$linkId,$id]);if(!$q->rowCount())throw new RuntimeException('Archived vendor trade was not found.');
 }
 elseif($action==='add_contact'){db()->prepare('INSERT INTO construction_vendor_contacts(construction_company_id,name,title,phone,email,is_primary,is_active,created_at,updated_at) VALUES(?,?,?,?,?,?,1,NOW(),NOW())')->execute([$id,trim($_POST['name']),trim($_POST['title']),trim($_POST['phone']),trim($_POST['email']),isset($_POST['is_primary'])?1:0]);if(isset($_POST['is_primary'])){ $new=(int)db()->lastInsertId();db()->prepare('UPDATE construction_vendor_contacts SET is_primary=(id=?) WHERE construction_company_id=?')->execute([$new,$id]);}}
 elseif($action==='edit_secondary_contact'){
  $contactId=(int)($_POST['contact_id']??0);$name=trim((string)($_POST['name']??''));$title=trim((string)($_POST['title']??''));$phone=trim((string)($_POST['phone']??''));$email=trim((string)($_POST['email']??''));
  if($name==='')throw new RuntimeException('Contact name is required.');if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))throw new RuntimeException('Enter a valid email address.');
  $q=db()->prepare('UPDATE construction_vendor_contacts SET name=?,title=?,phone=?,email=?,updated_at=NOW() WHERE id=? AND construction_company_id=? AND is_primary=0 AND is_active=1');$q->execute([$name,$title,$phone,$email,$contactId,$id]);
  if(!$q->rowCount()){$check=db()->prepare('SELECT 1 FROM construction_vendor_contacts WHERE id=? AND construction_company_id=? AND is_primary=0 AND is_active=1');$check->execute([$contactId,$id]);if(!$check->fetchColumn())throw new RuntimeException('Secondary contact was not found.');}
 }
 elseif($action==='delete_secondary_contact'){
  $contactId=(int)($_POST['contact_id']??0);$q=db()->prepare('UPDATE construction_vendor_contacts SET is_active=0,updated_at=NOW() WHERE id=? AND construction_company_id=? AND is_primary=0 AND is_active=1');$q->execute([$contactId,$id]);if(!$q->rowCount())throw new RuntimeException('Secondary contact was not found.');
 }
 elseif($action==='save_compliance'){db()->prepare('INSERT INTO construction_vendor_compliance(construction_company_id,insurance_status,insurance_expiration,insurance_verified_at,insurance_verified_by,w9_status,w9_verified_at,w9_verified_by,notes,updated_at) VALUES(?,?,?,?,?,?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE insurance_status=VALUES(insurance_status),insurance_expiration=VALUES(insurance_expiration),insurance_verified_at=VALUES(insurance_verified_at),insurance_verified_by=VALUES(insurance_verified_by),w9_status=VALUES(w9_status),w9_verified_at=VALUES(w9_verified_at),w9_verified_by=VALUES(w9_verified_by),notes=VALUES(notes),updated_at=NOW()')->execute([$id,$_POST['insurance_status'],$_POST['insurance_expiration']?:null,$_POST['insurance_status']==='Verified'?date('Y-m-d H:i:s'):null,$_POST['insurance_status']==='Verified'?(int)(admin_user()['id']??0):null,$_POST['w9_status'],$_POST['w9_status']==='On File'?date('Y-m-d H:i:s'):null,$_POST['w9_status']==='On File'?(int)(admin_user()['id']??0):null,trim($_POST['notes'])]);}
 header('Location: vendor_profile.php?id='.$id.'&saved=1');exit;
}catch(Throwable $e){$message=$e->getMessage();$error=str_contains(strtolower($message),'duplicate')?'This vendor already has that trade.':$message;}
require __DIR__.'/includes/header.php';
$s=db()->prepare('SELECT * FROM construction_companies WHERE id=?');$s->execute([$id]);$vendor=$s->fetch();if(!$vendor){http_response_code(404);exit('Vendor not found.');}
try{$s=db()->prepare('SELECT * FROM construction_vendor_contacts WHERE construction_company_id=? AND is_active=1 ORDER BY is_primary DESC,name');$s->execute([$id]);$contacts=$s->fetchAll();$s=db()->prepare('SELECT * FROM construction_vendor_compliance WHERE construction_company_id=?');$s->execute([$id]);$compliance=$s->fetch()?:[];}catch(Throwable $e){$contacts=[];$compliance=[];$error=$error?:'Run the v3.4 installer to enable contacts and compliance.';}
try{
 $availableTrades=db()->query('SELECT id,trade_name FROM construction_trades WHERE is_active=1 ORDER BY display_order,trade_name')->fetchAll();
 $s=db()->prepare('SELECT ct.id link_id,t.id trade_id,t.trade_name,ct.archived_at FROM construction_company_trades ct JOIN construction_trades t ON t.id=ct.construction_trade_id WHERE ct.construction_company_id=? ORDER BY ct.archived_at IS NOT NULL,t.display_order,t.trade_name');$s->execute([$id]);$tradeRows=$s->fetchAll();
 $activeTradeRows=array_values(array_filter($tradeRows,fn($trade)=>empty($trade['archived_at'])));$archivedTradeRows=array_values(array_filter($tradeRows,fn($trade)=>!empty($trade['archived_at'])));$trades=array_column($activeTradeRows,'trade_name');
}catch(Throwable $e){$availableTrades=[];$activeTradeRows=[];$archivedTradeRows=[];$trades=[];}
?>
<div class="page-head"><div><a href="companies.php" class="muted">← Vendors</a><h1><?=e($vendor['company_name'])?></h1><p class="muted"><?=e(implode(' · ',$trades))?></p></div></div>
<?php if($saved):?><div class="card notice-success">Vendor profile saved.</div><?php endif;?><?php if($error):?><div class="card notice-error"><?=e($error)?></div><?php endif;?>
<section class="card vendor-profile-trades"><div class="section-heading"><div><h2>Trades</h2><p class="muted">Manage this vendor’s individual trade relationships.</p></div><button class="btn btn-primary" type="button" data-open-modal="vendor-trade-modal">Add Trade</button></div><div class="vendor-profile-trade-list">
<?php foreach($activeTradeRows as $trade):?><form method="post" class="vendor-profile-trade-row"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="company_id" value="<?=$id?>"><input type="hidden" name="link_id" value="<?=(int)$trade['link_id']?>"><label><span>Active trade</span><select name="trade_id" required><?php foreach($availableTrades as $option):?><option value="<?=(int)$option['id']?>" <?=(int)$option['id']===(int)$trade['trade_id']?'selected':''?>><?=e($option['trade_name'])?></option><?php endforeach;?></select></label><div class="vendor-profile-trade-actions"><button class="btn btn-primary" name="action" value="save_trade">Save</button><button class="btn btn-danger" name="action" value="archive_trade" formnovalidate data-confirm="Archive <?=e($vendor['company_name'].' — '.$trade['trade_name'])?>? Other trades for this vendor will remain active.">Archive</button></div></form><?php endforeach;?>
<?php if(!$activeTradeRows):?><p class="muted">This vendor has no active trades.</p><?php endif;?></div>
<?php if($archivedTradeRows):?><details class="vendor-profile-archived"><summary>Archived trades (<?=count($archivedTradeRows)?>)</summary><?php foreach($archivedTradeRows as $trade):?><form method="post" class="archived-vendor-row"><span><strong><?=e($trade['trade_name'])?></strong><small>Archived <?=e(dev_datetime($trade['archived_at']))?></small></span><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="company_id" value="<?=$id?>"><input type="hidden" name="link_id" value="<?=(int)$trade['link_id']?>"><button class="btn btn-secondary" name="action" value="restore_trade">Restore</button></form><?php endforeach;?></details><?php endif;?></section>
<div class="grid grid-2"><section class="card"><h2>Vendor Information</h2><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="company_id" value="<?=$id?>"><input type="hidden" name="action" value="save_company"><div class="form-full"><label>Company</label><input name="company_name" value="<?=e($vendor['company_name'])?>" required></div><div><label>Primary Contact</label><input name="primary_contact" value="<?=e($vendor['primary_contact'])?>"></div><div><label>Phone</label><input name="cell_phone" value="<?=e($vendor['cell_phone'])?>"></div><div class="form-full"><label>Email</label><input type="email" name="email" value="<?=e($vendor['email'])?>"></div><div class="form-full"><button class="primary">Save Vendor</button></div></form></section>
<section class="card"><h2>Compliance</h2><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="company_id" value="<?=$id?>"><input type="hidden" name="action" value="save_compliance"><div><label>Insurance</label><select name="insurance_status"><option>Missing</option><option <?=($compliance['insurance_status']??'')==='Verified'?'selected':''?>>Verified</option><option <?=($compliance['insurance_status']??'')==='Expired'?'selected':''?>>Expired</option></select></div><div><label>Expiration Date</label><input type="date" name="insurance_expiration" value="<?=e($compliance['insurance_expiration']??'')?>"></div><div><label>W-9</label><select name="w9_status"><option>Missing</option><option <?=($compliance['w9_status']??'')==='On File'?'selected':''?>>On File</option></select></div><div class="form-full"><label>Compliance Notes</label><textarea name="notes"><?=e($compliance['notes']??'')?></textarea></div><div class="form-full"><button class="primary">Save Compliance</button></div></form></section></div>
<section class="card" style="margin-top:20px"><div class="section-heading"><h2>Secondary Contacts</h2><button class="btn btn-primary" type="button" data-open-modal="contact-modal">Add Contact</button></div><div class="table-scroll"><table><thead><tr><th>Name</th><th>Role</th><th>Phone</th><th>Email</th><th>Primary</th><th>Actions</th></tr></thead><tbody><?php foreach($contacts as $c):?><tr><td><?=e($c['name'])?></td><td><?=e($c['title']?:'—')?></td><td><?php if($c['phone']):?><a href="tel:<?=e(preg_replace('/\D+/','',$c['phone']))?>"><?=e($c['phone'])?></a><?php else:?>—<?php endif;?></td><td><?php if($c['email']):?><a href="mailto:<?=e($c['email'])?>"><?=e($c['email'])?></a><?php else:?>—<?php endif;?></td><td><?=$c['is_primary']?'Yes':'—'?></td><td><?php if(!$c['is_primary']):?><div class="actions no-top"><button class="btn btn-secondary btn-small" type="button" data-open-modal="edit-contact-<?=(int)$c['id']?>">Edit</button><form method="post" onsubmit="return confirm('Delete this secondary contact?');"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="company_id" value="<?=$id?>"><input type="hidden" name="action" value="delete_secondary_contact"><input type="hidden" name="contact_id" value="<?=(int)$c['id']?>"><button class="btn btn-danger btn-small" type="submit">Delete</button></form></div><?php else:?><span class="muted">Protected</span><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section>
<div class="dev-modal" id="contact-modal" hidden><div class="dev-modal-panel"><button class="modal-close" data-close-modal>×</button><h2>Add Contact</h2><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="company_id" value="<?=$id?>"><input type="hidden" name="action" value="add_contact"><div><label>Name</label><input name="name" required></div><div><label>Role / Title</label><input name="title"></div><div><label>Phone</label><input name="phone"></div><div><label>Email</label><input type="email" name="email"></div><div class="form-full"><label><input type="checkbox" name="is_primary" value="1"> Primary contact</label></div><div class="form-full"><button class="primary">Add Contact</button></div></form></div></div>
<div class="dev-modal" id="vendor-trade-modal" hidden><div class="dev-modal-panel"><button class="modal-close" type="button" data-close-modal aria-label="Close">×</button><h2>Add Trade</h2><p class="muted">Add another trade relationship for <?=e($vendor['company_name'])?>.</p><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="company_id" value="<?=$id?>"><input type="hidden" name="action" value="add_trade"><div class="form-full"><label>Trade</label><select name="trade_id" required><option value="">Choose trade...</option><?php foreach($availableTrades as $trade):?><option value="<?=(int)$trade['id']?>"><?=e($trade['trade_name'])?></option><?php endforeach;?></select></div><div class="form-full actions"><button type="button" class="btn btn-secondary" data-close-modal>Cancel</button><button type="submit" class="primary">Add Trade</button></div></form></div></div>
<?php foreach($contacts as $c):if($c['is_primary'])continue;?><div class="dev-modal" id="edit-contact-<?=(int)$c['id']?>" hidden><div class="dev-modal-panel"><button class="modal-close" type="button" data-close-modal aria-label="Close">×</button><h2>Edit Secondary Contact</h2><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="company_id" value="<?=$id?>"><input type="hidden" name="action" value="edit_secondary_contact"><input type="hidden" name="contact_id" value="<?=(int)$c['id']?>"><div><label>Name</label><input name="name" required value="<?=e($c['name'])?>"></div><div><label>Role / Title</label><input name="title" value="<?=e($c['title'])?>"></div><div><label>Phone</label><input name="phone" type="tel" value="<?=e($c['phone'])?>"></div><div><label>Email</label><input name="email" type="email" value="<?=e($c['email'])?>"></div><div class="form-full actions"><button type="button" class="btn btn-secondary" data-close-modal>Cancel</button><button type="submit" class="primary">Save Contact</button></div></form></div></div><?php endforeach;?>
<?php require __DIR__.'/includes/footer.php';?>
