<?php
$propertyId=manage_active_property_id();$property=$propertyId?manage_property($propertyId):null;$years=range(2026,2045);$systemNow=new DateTimeImmutable('now',new DateTimeZone('America/Chicago'));$defaultPeriod=$systemNow->modify('first day of previous month');$allMonths=[1=>'January','February','March','April','May','June','July','August','September','October','November','December'];$isQuarterly=$feeType==='management';
if($isQuarterly){$defaultMonth=(int)(floor(((int)$defaultPeriod->format('n'))/3)*3);$defaultYear=(int)$defaultPeriod->format('Y');if($defaultMonth<3){$defaultMonth=12;$defaultYear--;}$months=[3=>'March',6=>'June',9=>'September',12=>'December'];}else{$defaultMonth=(int)$defaultPeriod->format('n');$defaultYear=(int)$defaultPeriod->format('Y');$months=$allMonths;}
$year=(int)($_GET['year']??$defaultYear);$month=(int)($_GET['month']??$defaultMonth);if(!in_array($year,$years,true))$year=2026;if($isQuarterly){if(!isset($months[$month]))$month=$defaultMonth;}elseif($month<1||$month>12||($year===2026&&$month<7))$month=7;$feeCategories=$isQuarterly?['flash_report'=>'Flash Report']:['statement'=>'Statement','payment'=>'Payment'];$statuses=[];$period=null;$filesByCategory=array_fill_keys(array_keys($feeCategories),[]);
if($property&&manage_fees_schema_ready()){$q=db()->prepare('SELECT report_month,status FROM management_fee_periods WHERE management_property_id=? AND fee_type=? AND report_year=?');$q->execute([$propertyId,$feeType,$year]);foreach($q->fetchAll() as $row)$statuses[(int)$row['report_month']]=(string)$row['status'];$q=db()->prepare('SELECT * FROM management_fee_periods WHERE management_property_id=? AND fee_type=? AND report_year=? AND report_month=?');$q->execute([$propertyId,$feeType,$year,$month]);$period=$q->fetch()?:null;if($period){$q=db()->prepare('SELECT * FROM management_fee_files WHERE management_fee_period_id=? ORDER BY id');$q->execute([(int)$period['id']]);foreach($q->fetchAll() as $file){$category=(string)$file['file_category'];if(isset($filesByCategory[$category]))$filesByCategory[$category][]=$file;}}}
require __DIR__.'/header.php';
?>
<?php if(!manage_fees_schema_ready()):?><div class="manage-alert error">Run the Management Properties database upgrade to enable <?=manage_e($feeTitle)?>.</div><?php elseif($property):?>
<section class="manage-year-calendar manage-panel"><div class="manage-calendar-heading"><div><h2><?=$year?> <?=manage_e($feeTitle)?> Calendar</h2><p>Select a <?=$isQuarterly?'quarter-ending month':'month'?> to view or update its fee files.</p></div><div class="manage-calendar-actions"><form method="get"><label for="feeCalendarYear">Year</label><select id="feeCalendarYear" name="year" onchange="this.form.submit()"><?php foreach($years as $optionYear):?><option value="<?=$optionYear?>" <?=$year===$optionYear?'selected':''?>><?=$optionYear?></option><?php endforeach;?></select></form><?php if(manage_is_admin()&&$period):?><button type="button" class="manage-reset-month-button" data-reset-fee-month data-month-label="<?=manage_e($months[$month].' '.$year)?>"><i class="fa-solid fa-rotate-left" aria-hidden="true"></i> Reset Month</button><?php endif;?></div></div><div class="manage-calendar-months <?=$isQuarterly?'manage-calendar-quarters':''?>"><?php foreach($months as $number=>$name):$available=$isQuarterly||!($year===2026&&$number<7);$status=$statuses[$number]??'blank';?><?php if($available):?><a class="manage-calendar-month <?=$month===$number?'selected':''?> <?=manage_e($status)?>" href="?year=<?=$year?>&amp;month=<?=$number?>"><span class="manage-calendar-status-icon"><i class="fa-solid <?=$status==='submitted'?'fa-check':'fa-circle'?>"></i></span><span><?=$name?><small><?=ucfirst(manage_e($status))?></small></span></a><?php else:?><span class="manage-calendar-month unavailable"><span class="manage-calendar-status-icon"><i class="fa-regular fa-circle"></i></span><span><?=$name?><small>Unavailable</small></span></span><?php endif;?><?php endforeach;?></div></section>
<div class="manage-autosave-status manage-receipt-save-status" id="feeAutosaveStatus" role="status" aria-live="polite">Files upload automatically</div>
<section class="manage-receipt-upload-grid manage-fee-upload-grid manage-fee-upload-grid-<?=count($feeCategories)?>" id="feeUploadArea" data-endpoint="fees_autosave.php" data-fee-type="<?=manage_e($feeType)?>" data-fee-title="<?=manage_e($feeTitle)?>" data-csrf="<?=manage_e(csrf_token())?>" data-property-id="<?=$propertyId?>" data-year="<?=$year?>" data-month="<?=$month?>"><?php foreach($feeCategories as $category=>$label):?><article class="manage-panel manage-receipt-upload-card" data-category="<?=$category?>"><div><h2><?=$label?></h2><p>Upload one or multiple supporting files for <?=manage_e($months[$month].' '.$year)?>.</p></div><label class="manage-file-upload manage-file-drop-zone" data-fee-drop><strong><i class="fa-solid fa-cloud-arrow-up" aria-hidden="true"></i> Upload <?=$label?></strong><span>Drag and drop multiple files here, or click to browse. Files save automatically.</span><span class="manage-upload-selection">No files selected</span><input type="file" multiple data-fee-upload accept=".pdf,.xls,.xlsx,.csv,.doc,.docx,.jpg,.jpeg,.png,.webp"></label><div class="manage-existing-files" data-fee-files><strong>Attached Files</strong><?php foreach($filesByCategory[$category] as $file):?><span class="manage-file-item" data-file-id="<?=(int)$file['id']?>"><a href="fee_file.php?id=<?=(int)$file['id']?>"><i class="fa-solid fa-paperclip"></i> <?=manage_e($file['original_name'])?></a><button type="button" class="manage-file-delete" data-file-id="<?=(int)$file['id']?>" aria-label="Delete <?=manage_e($file['original_name'])?>"><i class="fa-solid fa-trash"></i></button></span><?php endforeach;?><?php if(!$filesByCategory[$category]):?><span class="manage-empty-files">No files have been uploaded.</span><?php endif;?></div></article><?php endforeach;?></section>
<section class="manage-panel manage-breakdown-placeholder"><h2>Breakdown</h2><p><?=manage_e($feeTitle)?> breakdown details will be added here.</p></section><script src="assets/fees-autosave.js?v=<?=manage_e(znp_asset_version())?>-monthly2" defer></script>
<?php endif;?>
<?php require __DIR__.'/footer.php';?>
