<?php
declare(strict_types=1);

function manage_xlsx_escape(mixed $value): string {
    return htmlspecialchars((string)$value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
}

function manage_xlsx_xml(string $xml): DOMXPath {
    $document=new DOMDocument();$previous=libxml_use_internal_errors(true);
    if(!$document->loadXML($xml,LIBXML_NONET|LIBXML_NOBLANKS)){libxml_clear_errors();libxml_use_internal_errors($previous);throw new RuntimeException('The Excel workbook contains invalid XML.');}
    libxml_clear_errors();libxml_use_internal_errors($previous);$xpath=new DOMXPath($document);$xpath->registerNamespace('x','http://schemas.openxmlformats.org/spreadsheetml/2006/main');$xpath->registerNamespace('r','http://schemas.openxmlformats.org/officeDocument/2006/relationships');$xpath->registerNamespace('p','http://schemas.openxmlformats.org/package/2006/relationships');return $xpath;
}

function manage_xlsx_entry(ZipArchive $zip,string $name,int $maximum=12000000): string {
    $stat=$zip->statName($name);if(!$stat||($stat['size']??0)>$maximum)throw new RuntimeException('The Excel worksheet is too large to preview.');$contents=$zip->getFromName($name);if($contents===false)throw new RuntimeException('A required Excel worksheet part is missing.');return $contents;
}

function manage_xlsx_column_index(string $reference): int {
    if(!preg_match('/^([A-Z]+)/i',$reference,$match))return 0;$index=0;foreach(str_split(strtoupper($match[1])) as $letter)$index=$index*26+(ord($letter)-64);return max(0,$index-1);
}

function manage_xlsx_indexed_color(int $index): string {
    $colors=[0=>'#000000',1=>'#FFFFFF',2=>'#FF0000',3=>'#00FF00',4=>'#0000FF',5=>'#FFFF00',6=>'#FF00FF',7=>'#00FFFF',8=>'#000000',9=>'#FFFFFF',10=>'#FF0000',11=>'#00FF00',12=>'#0000FF',13=>'#FFFF00',14=>'#FF00FF',15=>'#00FFFF',16=>'#800000',17=>'#008000',18=>'#000080',19=>'#808000',20=>'#800080',21=>'#008080',22=>'#C0C0C0',23=>'#808080',40=>'#00CCFF',41=>'#CCFFFF',42=>'#CCFFCC',43=>'#FFFF99',44=>'#99CCFF',45=>'#FF99CC',46=>'#CC99FF',47=>'#FFCC99'];return $colors[$index]??'#FFFFFF';
}

function manage_xlsx_color(?DOMElement $element): string {
    if(!$element)return'';$rgb=strtoupper($element->getAttribute('rgb'));if(preg_match('/^[A-F0-9]{8}$/',$rgb))return'#'.substr($rgb,2);if(preg_match('/^[A-F0-9]{6}$/',$rgb))return'#'.$rgb;if($element->hasAttribute('indexed'))return manage_xlsx_indexed_color((int)$element->getAttribute('indexed'));return'';
}

function manage_xlsx_decimal_places(string $format): int {
    $plain=preg_replace('/"[^"]*"|\\./','',$format)??$format;$dot=strpos($plain,'.');if($dot===false)return 0;$tail=substr($plain,$dot+1);preg_match('/^[0#]+/',$tail,$match);return strlen($match[0]??'');
}

function manage_xlsx_format_number(float $value,int $formatId,string $format): string {
    $dateFormat=in_array($formatId,range(14,22),true)||(bool)preg_match('/(?:^|[^\[])[dmy]{1,4}[\-\/ ]/i',$format);
    if($dateFormat){$seconds=(int)round(($value-25569)*86400);$date=(new DateTimeImmutable('@'.$seconds))->setTimezone(new DateTimeZone('UTC'));if(str_contains(strtolower($format),'mmm'))return $date->format(str_contains(strtolower($format),'yyyy')?'d-M-Y':'d-M-y');return $date->format('m/d/Y');}
    if(str_contains($format,'%')||in_array($formatId,[9,10],true))return number_format($value*100,manage_xlsx_decimal_places($format),'.',',').'%';
    $decimals=match($formatId){2,4=>2,1,3=>0,default=>manage_xlsx_decimal_places($format)};$useThousands=in_array($formatId,[3,4],true)||str_contains($format,',');$currency=(bool)preg_match('/[$£€¥]/u',$format,$currencyMatch);if($formatId===0&&$format==='')return abs($value-round($value))<0.0000001?(string)(int)round($value):rtrim(rtrim(number_format($value,8,'.',''), '0'),'.');$number=number_format($value,$decimals,'.',$useThousands?',':'');return($currency?$currencyMatch[0]:'').$number;
}

function manage_xlsx_preview(string $contents,string $filename,int $selectedSheet=0,array $baseQuery=[]): string {
    if(!class_exists(ZipArchive::class)||!class_exists(DOMDocument::class))throw new RuntimeException('Excel previews require the PHP ZIP and XML extensions.');
    if(strlen($contents)>26214400)throw new RuntimeException('This Excel workbook is too large to preview.');
    $temporary=znp_storage_temp_path('xlsx');if(file_put_contents($temporary,$contents,LOCK_EX)===false)throw new RuntimeException('The Excel workbook could not be staged for preview.');
    $zip=new ZipArchive();$opened=false;try{
        if($zip->open($temporary)!==true)throw new RuntimeException('The Excel workbook could not be opened.');$opened=true;
        $workbookXml=manage_xlsx_xml(manage_xlsx_entry($zip,'xl/workbook.xml'));
        $relationsXml=manage_xlsx_xml(manage_xlsx_entry($zip,'xl/_rels/workbook.xml.rels'));
        $relations=[];foreach($relationsXml->query('//p:Relationship')?:[] as $relation)if($relation instanceof DOMElement)$relations[$relation->getAttribute('Id')]=$relation->getAttribute('Target');
        $sheets=[];foreach($workbookXml->query('//x:sheets/x:sheet')?:[] as $sheet){if(!$sheet instanceof DOMElement)continue;$relationshipId=$sheet->getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id');$target=$relations[$relationshipId]??'';if($target==='')continue;$target=ltrim(str_replace('../','',$target),'/');$sheets[]=['name'=>$sheet->getAttribute('name')?:'Sheet '.(count($sheets)+1),'path'=>str_starts_with($target,'xl/')?$target:'xl/'.$target];}
        if(!$sheets)throw new RuntimeException('The Excel workbook does not contain a worksheet.');$selectedSheet=max(0,min($selectedSheet,count($sheets)-1));$sheetInfo=$sheets[$selectedSheet];
        $sharedStrings=[];if($zip->locateName('xl/sharedStrings.xml')!==false){$sharedXml=manage_xlsx_xml(manage_xlsx_entry($zip,'xl/sharedStrings.xml'));foreach($sharedXml->query('//x:si')?:[] as $item){$parts=[];foreach((new DOMXPath($item->ownerDocument))->query('.//*[local-name()="t"]',$item)?:[] as $text)$parts[]=$text->textContent;$sharedStrings[]=implode('',$parts);}}
        $formats=[0=>'',1=>'0',2=>'0.00',3=>'#,##0',4=>'#,##0.00',9=>'0%',10=>'0.00%',14=>'mm-dd-yy'];$fonts=[];$fills=[];$cellStyles=[];$stylesXml=manage_xlsx_xml(manage_xlsx_entry($zip,'xl/styles.xml'));
        foreach($stylesXml->query('//x:numFmts/x:numFmt')?:[] as $format)if($format instanceof DOMElement)$formats[(int)$format->getAttribute('numFmtId')]=$format->getAttribute('formatCode');
        foreach($stylesXml->query('//x:fonts/x:font')?:[] as $font){$fontXPath=new DOMXPath($font->ownerDocument);$fontXPath->registerNamespace('x','http://schemas.openxmlformats.org/spreadsheetml/2006/main');$size=$fontXPath->query('./x:sz',$font)?->item(0);$color=$fontXPath->query('./x:color',$font)?->item(0);$fonts[]=['bold'=>$fontXPath->query('./x:b',$font)?->length>0,'italic'=>$fontXPath->query('./x:i',$font)?->length>0,'size'=>$size instanceof DOMElement?(float)$size->getAttribute('val'):11,'color'=>$color instanceof DOMElement?manage_xlsx_color($color):''];}
        foreach($stylesXml->query('//x:fills/x:fill')?:[] as $fill){$fillXPath=new DOMXPath($fill->ownerDocument);$fillXPath->registerNamespace('x','http://schemas.openxmlformats.org/spreadsheetml/2006/main');$color=$fillXPath->query('./x:patternFill/x:fgColor',$fill)?->item(0);$fills[]=$color instanceof DOMElement?manage_xlsx_color($color):'';}
        foreach($stylesXml->query('//x:cellXfs/x:xf')?:[] as $style){if(!$style instanceof DOMElement)continue;$alignment=null;foreach($style->childNodes as $child)if($child instanceof DOMElement&&$child->localName==='alignment'){$alignment=$child;break;}$cellStyles[]=['font'=>(int)$style->getAttribute('fontId'),'fill'=>(int)$style->getAttribute('fillId'),'border'=>(int)$style->getAttribute('borderId'),'format'=>(int)$style->getAttribute('numFmtId'),'align'=>$alignment?preg_replace('/[^a-z]/','',strtolower($alignment->getAttribute('horizontal'))):'','wrap'=>$alignment&&$alignment->getAttribute('wrapText')==='1'];}
        $sheetXml=manage_xlsx_xml(manage_xlsx_entry($zip,$sheetInfo['path']));$dimension=$sheetXml->query('//x:dimension')?->item(0);$maximumRow=1;$maximumColumn=1;if($dimension instanceof DOMElement&&preg_match('/([A-Z]+)(\d+)$/i',$dimension->getAttribute('ref'),$dimensionMatch)){$maximumColumn=manage_xlsx_column_index($dimensionMatch[1])+1;$maximumRow=(int)$dimensionMatch[2];}$truncated=$maximumRow>500||$maximumColumn>100;$maximumRow=min(500,max(1,$maximumRow));$maximumColumn=min(100,max(1,$maximumColumn));
        $columnWidths=array_fill(0,$maximumColumn,88);foreach($sheetXml->query('//x:cols/x:col')?:[] as $column){if(!$column instanceof DOMElement)continue;$start=max(1,(int)$column->getAttribute('min'));$end=min($maximumColumn,(int)$column->getAttribute('max'));$width=min(260,max(32,(float)$column->getAttribute('width')*7+8));for($index=$start-1;$index<$end;$index++)$columnWidths[$index]=(int)round($width);}
        $rowHeights=[];foreach($sheetXml->query('//x:sheetData/x:row')?:[] as $row)if($row instanceof DOMElement&&$row->hasAttribute('ht'))$rowHeights[(int)$row->getAttribute('r')]=min(100,max(20,(int)round((float)$row->getAttribute('ht')*1.34)));
        $cells=[];foreach($sheetXml->query('//x:sheetData/x:row/x:c')?:[] as $cell){if(!$cell instanceof DOMElement)continue;$reference=$cell->getAttribute('r');if(!preg_match('/^[A-Z]+(\d+)$/i',$reference,$referenceMatch))continue;$rowIndex=(int)$referenceMatch[1];$columnIndex=manage_xlsx_column_index($reference);if($rowIndex<1||$rowIndex>$maximumRow||$columnIndex>=$maximumColumn)continue;$type=$cell->getAttribute('t');$styleIndex=(int)$cell->getAttribute('s');$valueNode=null;$inlineNode=null;foreach($cell->childNodes as $child)if($child instanceof DOMElement){if($child->localName==='v')$valueNode=$child;elseif($child->localName==='is')$inlineNode=$child;}$raw=$valueNode?->textContent??'';$style=$cellStyles[$styleIndex]??['font'=>0,'fill'=>0,'border'=>0,'format'=>0,'align'=>'','wrap'=>false];if($type==='s')$value=$sharedStrings[(int)$raw]??'';elseif($type==='inlineStr')$value=$inlineNode?->textContent??'';elseif($type==='b')$value=$raw==='1'?'TRUE':'FALSE';elseif($type==='e')$value=$raw;elseif($raw!==''&&is_numeric($raw))$value=manage_xlsx_format_number((float)$raw,(int)$style['format'],$formats[(int)$style['format']]??'');else $value=$raw;$cells[$rowIndex][$columnIndex]=['value'=>$value,'numeric'=>$type==='n'||($type===''&&is_numeric($raw)),'style'=>$style];}
        $mergeStarts=[];$mergeCovered=[];foreach($sheetXml->query('//x:mergeCells/x:mergeCell')?:[] as $merge){if(!$merge instanceof DOMElement||!preg_match('/^([A-Z]+)(\d+):([A-Z]+)(\d+)$/i',$merge->getAttribute('ref'),$match))continue;$startColumn=manage_xlsx_column_index($match[1]);$startRow=(int)$match[2];$endColumn=min($maximumColumn-1,manage_xlsx_column_index($match[3]));$endRow=min($maximumRow,(int)$match[4]);if($startRow>$maximumRow||$startColumn>=$maximumColumn)continue;$mergeStarts[$startRow][$startColumn]=['rowspan'=>$endRow-$startRow+1,'colspan'=>$endColumn-$startColumn+1];for($row=$startRow;$row<=$endRow;$row++)for($column=$startColumn;$column<=$endColumn;$column++)if($row!==$startRow||$column!==$startColumn)$mergeCovered[$row][$column]=true;}
        $query=$baseQuery;$html='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.manage_xlsx_escape($filename).'</title><style>*{box-sizing:border-box}html,body{height:100%;margin:0;background:#eef2f5;color:#1c2e3f;font-family:Arial,sans-serif}.xlsx-shell{display:grid;grid-template-rows:auto minmax(0,1fr);height:100%}.xlsx-toolbar{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:9px 12px;border-bottom:1px solid #cbd7e0;background:#fff}.xlsx-title{min-width:0;overflow:hidden;font-size:12px;font-weight:800;text-overflow:ellipsis;white-space:nowrap}.xlsx-tabs{display:flex;gap:5px;overflow-x:auto}.xlsx-tabs a{padding:6px 10px;border:1px solid #c8d5df;border-radius:7px;background:#f5f8fa;color:#36566f;font-size:10px;font-weight:800;text-decoration:none;white-space:nowrap}.xlsx-tabs a.active{border-color:#316f9d;background:#316f9d;color:#fff}.xlsx-scroll{overflow:auto;padding:10px}.xlsx-sheet{border-collapse:collapse;table-layout:fixed;background:#fff;box-shadow:0 4px 18px rgba(17,43,66,.1)}.xlsx-sheet td{height:22px;padding:2px 5px;overflow:hidden;border:1px solid #dfe5ea;color:#202b34;font-size:11px;line-height:1.25;text-overflow:ellipsis;white-space:nowrap}.xlsx-note{padding:7px 10px;background:#fff5d8;color:#72540e;font-size:11px}</style></head><body><div class="xlsx-shell"><div class="xlsx-toolbar"><span class="xlsx-title">'.manage_xlsx_escape($filename).'</span><nav class="xlsx-tabs" aria-label="Workbook sheets">';
        foreach($sheets as $sheetIndex=>$sheet){$query['sheet']=$sheetIndex;$html.='<a class="'.($sheetIndex===$selectedSheet?'active':'').'" href="?'.manage_xlsx_escape(http_build_query($query)).'">'.manage_xlsx_escape($sheet['name']).'</a>';}$html.='</nav></div><div class="xlsx-scroll">';if($truncated)$html.='<div class="xlsx-note">Preview limited to the first 500 rows and 100 columns.</div>';$html.='<table class="xlsx-sheet" aria-label="'.manage_xlsx_escape($sheetInfo['name']).'"><colgroup>';foreach($columnWidths as $width)$html.='<col style="width:'.$width.'px">';$html.='</colgroup><tbody>';
        for($row=1;$row<=$maximumRow;$row++){$height=$rowHeights[$row]??22;$html.='<tr style="height:'.$height.'px">';for($column=0;$column<$maximumColumn;$column++){if(isset($mergeCovered[$row][$column]))continue;$cell=$cells[$row][$column]??['value'=>'','numeric'=>false,'style'=>['font'=>0,'fill'=>0,'border'=>0,'format'=>0,'align'=>'','wrap'=>false]];$style=$cell['style'];$font=$fonts[(int)$style['font']]??['bold'=>false,'italic'=>false,'size'=>11,'color'=>''];$fill=$fills[(int)$style['fill']]??'';$css=[];if($fill!=='')$css[]='background:'.$fill;if($font['bold'])$css[]='font-weight:700';if($font['italic'])$css[]='font-style:italic';if((float)$font['size']!==11.0)$css[]='font-size:'.min(24,max(8,(float)$font['size'])).'px';if($font['color']!=='')$css[]='color:'.$font['color'];$alignment=$style['align']?:($cell['numeric']?'right':'left');if(in_array($alignment,['left','center','right'],true))$css[]='text-align:'.$alignment;if($style['wrap'])$css[]='white-space:normal';if((int)$style['border']>0)$css[]='border-bottom:3px solid #253746';$merge=$mergeStarts[$row][$column]??null;$attributes=$merge?' rowspan="'.$merge['rowspan'].'" colspan="'.$merge['colspan'].'"':'';$html.='<td'.$attributes.($css?' style="'.implode(';',$css).'"':'').'>'.manage_xlsx_escape($cell['value']).'</td>';}$html.='</tr>';}$html.='</tbody></table></div></div></body></html>';return $html;
    }finally{if($opened)$zip->close();znp_storage_remove_temp_file($temporary);}
}
