<?php
ob_start();require_once __DIR__.'/../includes/auth.php';require_admin();
function model_settings_json(array $payload,int $status=200):void{while(ob_get_level()>0)ob_end_clean();http_response_code($status);header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');echo json_encode($payload,JSON_UNESCAPED_SLASHES);exit;}
if($_SERVER['REQUEST_METHOD']!=='POST')model_settings_json(['ok'=>false,'error'=>'POST requests only.'],405);
if(!csrf_check($_POST['csrf_token']??''))model_settings_json(['ok'=>false,'error'=>'Your session expired. Refresh and try again.'],419);
$projectId=(int)($_POST['investment_opportunity_id']??0);$field=(string)($_POST['field']??'');$value=trim((string)($_POST['value']??''));
$fields=['cumulative_preferred_return_percent','tier1_lp_split','tier1_gp_split','tier2_lp_irr_hurdle','tier2_lp_split','tier2_gp_split','total_development_costs','contingency_percent','contingency_expected_use_percent','development_fee_percent','capital_fee_percent','bank_loan_percent','bank_loan_equity_percent','bank_loan_prime_rate','bank_loan_spread','bank_loan_amortization_years','bank_loan_interest_only_months','targeted_gross_income_monthly','targeted_operating_expense_percent','hold_period_years','first_distribution_month','minimum_cash_reserve','year1_occupancy_percent','year2_occupancy_percent','year3_occupancy_percent','year4_occupancy_percent','year5_occupancy_percent','year6_occupancy_percent','refinance_month','refinance_loan_amount','refinance_interest_rate','refinance_amortization_years','refinance_interest_only_months','refinance_term_years','exit_cap_rate','commission_percent'];
$integers=['bank_loan_interest_only_months','first_distribution_month','refinance_month','refinance_interest_only_months'];$percentages=array_values(array_filter($fields,static fn($n)=>str_contains($n,'percent')||str_contains($n,'split')||str_contains($n,'rate')||$n==='tier2_lp_irr_hurdle'));
if($projectId<1||!in_array($field,$fields,true))model_settings_json(['ok'=>false,'error'=>'Invalid model setting request.'],422);
try{
 if(!db()->query("SHOW TABLES LIKE 'investment_model_settings'")->fetchColumn())throw new RuntimeException('Install the Investment Model Settings database upgrade first.');
 $check=db()->prepare('SELECT id FROM investment_opportunities WHERE id=?');$check->execute([$projectId]);if(!$check->fetchColumn())throw new RuntimeException('Investment not found.');
 $stored=null;if($value!==''){if(!is_numeric($value)||!is_finite((float)$value)||(float)$value<0)throw new RuntimeException('Enter a valid number of zero or greater.');if(in_array($field,$integers,true)&&filter_var($value,FILTER_VALIDATE_INT)===false)throw new RuntimeException('Enter a whole number of months.');if(in_array($field,$percentages,true)&&(float)$value>100)throw new RuntimeException('Percentage values cannot exceed 100.');$stored=$value;}
 $sql="INSERT INTO investment_model_settings (investment_opportunity_id,`$field`,updated_by_admin_id) VALUES (?,?,?) ON DUPLICATE KEY UPDATE `$field`=VALUES(`$field`),updated_by_admin_id=VALUES(updated_by_admin_id)";db()->prepare($sql)->execute([$projectId,$stored,admin_user()['id']??null]);model_settings_json(['ok'=>true,'message'=>'Saved','value'=>$stored]);
}catch(Throwable $e){model_settings_json(['ok'=>false,'error'=>$e->getMessage()],422);}
