<?php
require_once __DIR__ . '/../includes/auth.php';
require_admin();$id=(int)($_GET['id']??0);if(investments_only_role()&&$id<1){http_response_code(403);exit('This account cannot create investments.');}if($id)require_investment_access($id);$error='';$row=['slug'=>'','project_name'=>'','asset_type'=>'','city'=>'','state'=>'Texas','status'=>'draft','investment_structure'=>'','unit_label'=>'','unit_count_text'=>'','hero_image'=>'','display_order'=>0,'is_visible'=>1,'accepting_inquiries'=>0];$statusOptions=['draft'=>'Draft','raising_capital'=>'Raising Capital','funded'=>'Funded','closed'=>'Closed','archived'=>'Archived'];if($id){$s=db()->prepare('SELECT * FROM investment_opportunities WHERE id=?');$s->execute([$id]);$row=$s->fetch()?:$row;}
if($_SERVER['REQUEST_METHOD']==='POST'){if(!csrf_check($_POST['csrf_token']??''))$error='Your session expired. Refresh and try again.';else{$status=(string)($_POST['status']??'');$img=trim((string)($_POST['existing_hero_image']??''));$oldImg=trim((string)($row['hero_image']??''));if(!isset($statusOptions[$status]))$error='Select a valid status.';if(!$error&&isset($_FILES['hero_image_upload'])&&$_FILES['hero_image_upload']['error']!==UPLOAD_ERR_NO_FILE){if($_FILES['hero_image_upload']['error']!==UPLOAD_ERR_OK)$error='The investment image upload failed.';elseif($_FILES['hero_image_upload']['size']>8*1024*1024)$error='The investment image must be smaller than 8 MB.';else{$f=new finfo(FILEINFO_MIME_TYPE);$mime=$f->file($_FILES['hero_image_upload']['tmp_name']);$exts=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];if(!isset($exts[$mime]))$error='Upload a JPG, PNG, or WebP image.';else{$dir=__DIR__.'/../assets/images/investments';if(!is_dir($dir))mkdir($dir,0755,true);$name=trim((string)($_POST['project_name']??'investment'));$slug=strtolower(trim(preg_replace('/[^a-z0-9]+/i','-',$name),'-'));$fn=$slug.'-'.time().'.'.$exts[$mime];if(!move_uploaded_file($_FILES['hero_image_upload']['tmp_name'],$dir.'/'.$fn))$error='The image could not be saved.';else$img='assets/images/investments/'.$fn;}}}
if(!$error){$vals=[trim((string)($_POST['slug']??'')),trim((string)($_POST['project_name']??'')),trim((string)($_POST['asset_type']??'')),trim((string)($_POST['city']??'')),trim((string)($_POST['state']??'')),$status,trim((string)($_POST['investment_structure']??'')),trim((string)($_POST['unit_label']??'')),trim((string)($_POST['unit_count_text']??'')),$img?:null,(int)($_POST['display_order']??0),isset($_POST['is_visible'])?1:0,isset($_POST['accepting_inquiries'])?1:0];if($id){$vals[]=$id;$sql='UPDATE investment_opportunities SET slug=?,project_name=?,asset_type=?,city=?,state=?,status=?,investment_structure=?,unit_label=?,unit_count_text=?,hero_image=?,display_order=?,is_visible=?,accepting_inquiries=? WHERE id=?';}else{$sql='INSERT INTO investment_opportunities (slug,project_name,asset_type,city,state,status,investment_structure,unit_label,unit_count_text,hero_image,display_order,is_visible,accepting_inquiries) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)';}db()->prepare($sql)->execute($vals);if($oldImg!==''&&$img!==$oldImg&&!app_delete_managed_file($oldImg,['assets/images/investments']))error_log('Replaced investment image could not be removed: '.$oldImg);header('Location: opportunities.php?saved=1'); exit;}}}
require __DIR__ . '/_header.php';
?>
<div class="admin-page-head"><div><h1><?=$id?'Edit':'Add'?> Investment</h1><p>Control the public Invest card, status, and project image.</p></div><a class="secondary" href="opportunities.php">Back to Investments</a></div><?php if($error):?><div class="status error"><?=e($error)?></div><?php endif;?>
<form method="post" enctype="multipart/form-data" class="admin-form admin-form-wide"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="existing_hero_image" value="<?=e((string)$row['hero_image'])?>">
<?php foreach(['slug'=>'Slug','project_name'=>'Project Name','asset_type'=>'Asset Type','city'=>'City','state'=>'State','investment_structure'=>'Investment Structure','unit_label'=>'Unit Label','unit_count_text'=>'Unit Count Text','display_order'=>'Display Order'] as $n=>$l):?><label><?=e($l)?></label><input name="<?=e($n)?>" value="<?=e((string)$row[$n])?>"><?php endforeach;?>
<label>Status</label><select name="status"><?php foreach($statusOptions as $v=>$l):?><option value="<?=e($v)?>" <?=$row['status']===$v?'selected':''?>><?=e($l)?></option><?php endforeach;?></select>
<label>Replace Investment Photo</label><input type="file" name="hero_image_upload" accept=".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp"><small>JPG, PNG, or WebP. Maximum 8 MB.</small>
<?php if(!empty($row['hero_image'])):?><div class="admin-current-photo admin-current-photo-wide"><span>Current Investment Photo</span><img src="../<?=e((string)$row['hero_image'])?>" alt=""></div><?php endif;?>
<label class="admin-checkbox"><input type="checkbox" name="is_visible" <?=$row['is_visible']?'checked':''?>> Visible on the public website</label><label class="admin-checkbox"><input type="checkbox" name="accepting_inquiries" <?=$row['accepting_inquiries']?'checked':''?>> Accepting inquiries</label><button class="primary admin-save-button" type="submit">Save Investment</button></form>
<?php require __DIR__ . '/_footer.php'; ?>
