<?php
require_once __DIR__.'/../includes/auth.php';require_admin();$error='';
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')==='delete'){
 if(!csrf_check((string)($_POST['csrf_token']??'')))$error='Your session expired. Refresh and try again.';
 else{$id=(int)($_POST['team_member_id']??0);if($id>0){try{$s=db()->prepare('SELECT headshot FROM team_members WHERE id=?');$s->execute([$id]);$headshot=$s->fetchColumn();db()->prepare('DELETE FROM team_members WHERE id=?')->execute([$id]);if(is_string($headshot)&&$headshot!=='')app_delete_managed_file($headshot,['assets/images/team']);header('Location: team.php?deleted=1');exit;}catch(Throwable $e){error_log('Team member deletion failed for ID '.$id.': '.$e->getMessage());$error='The team member could not be deleted.';}}}
}
require __DIR__ . '/_header.php';$message=isset($_GET['saved'])?'Team member saved successfully.':'';if(isset($_GET['deleted']))$message='Team member deleted.';$members=db()->query('SELECT * FROM team_members ORDER BY display_order,full_name')->fetchAll();?>
<div class="admin-page-head"><div><h1>Team Members</h1></div><a class="primary" href="team_edit.php">Add Team Member</a></div>
<?php if($message):?><div class="status success"><?=e($message)?></div><?php endif;?><?php if($error):?><div class="status error"><?=e($error)?></div><?php endif;?>
<div class="admin-team-list"><?php foreach($members as $m):?><article class="admin-team-card"><div><?php if(!empty($m['headshot'])):?><img class="admin-team-photo-large" src="../<?=e($m['headshot'])?>" alt=""><?php else:?><div class="admin-team-photo-large admin-team-photo-fallback">—</div><?php endif;?></div><div><div class="admin-team-card__header"><div><h2><?=e($m['full_name'])?></h2><p><?=e($m['title'])?></p></div><span class="admin-status-pill <?=$m['is_active']?'is-active':'is-inactive'?>"><?=$m['is_active']?'Visible':'Hidden'?></span></div><?php if(!empty($m['specialty_line'])):?><div class="admin-team-specialty"><?=e($m['specialty_line'])?></div><?php endif;?><div class="admin-team-bio-preview"><?=nl2br(e((string)$m['bio']))?></div><div class="admin-record-actions"><a class="secondary admin-small-button" href="team_edit.php?id=<?=(int)$m['id']?>">Edit</a><form method="post" onsubmit="return confirm('Delete this team member?')"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="team_member_id" value="<?=(int)$m['id']?>"><button class="admin-danger-link" type="submit">Delete</button></form></div></div></article><?php endforeach;?></div>
<?php require __DIR__ . '/_footer.php'; ?>
