<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/auth.php';
require_login();
if(!super_admin_role()){http_response_code(403);exit('Only a Super Admin may run database upgrades.');}
$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!csrf_check((string)($_POST['csrf_token']??'')))$error='Your session expired. Refresh and try again.';
    else try{
        if(!db_table_exists('management_receipt_transactions')||!db_table_exists('management_receipt_files'))throw new RuntimeException('Install Management Receipts before running this upgrade.');
        if(!db_column_exists('management_receipt_transactions','receipt_found'))db()->exec("ALTER TABLE management_receipt_transactions ADD COLUMN receipt_found TINYINT(1) NOT NULL DEFAULT 0 AFTER category_id");
        if(!db_column_exists('management_receipt_files','file_comment'))db()->exec("ALTER TABLE management_receipt_files ADD COLUMN file_comment VARCHAR(500) NOT NULL DEFAULT '' AFTER receipt_group");
        if(!db_column_exists('management_receipt_files','owner_receipt_number'))db()->exec('ALTER TABLE management_receipt_files ADD COLUMN owner_receipt_number INT UNSIGNED NULL AFTER file_comment, ADD UNIQUE KEY uq_owner_receipt_period_number(management_receipt_period_id,owner_receipt_number)');
        if(!db_column_exists('management_receipt_transactions','owner_receipt_file_id'))db()->exec('ALTER TABLE management_receipt_transactions ADD COLUMN owner_receipt_file_id BIGINT UNSIGNED NULL AFTER receipt_found, ADD UNIQUE KEY uq_transaction_owner_receipt(owner_receipt_file_id)');
        db()->exec("CREATE TABLE IF NOT EXISTS management_receipt_card_settings (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,management_receipt_period_id BIGINT UNSIGNED NOT NULL,card_key VARCHAR(190) NOT NULL,is_owner TINYINT(1) NOT NULL DEFAULT 0,updated_by_admin_user_id BIGINT UNSIGNED NULL,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_receipt_card_period_key(management_receipt_period_id,card_key),KEY idx_receipt_card_owner(management_receipt_period_id,is_owner)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $periods=db()->query("SELECT DISTINCT management_receipt_period_id FROM management_receipt_files WHERE file_category='backup_invoices' AND receipt_group='owner' ORDER BY management_receipt_period_id")->fetchAll(PDO::FETCH_COLUMN);$selectFiles=db()->prepare("SELECT id,owner_receipt_number FROM management_receipt_files WHERE management_receipt_period_id=? AND file_category='backup_invoices' AND receipt_group='owner' ORDER BY id");$numberFile=db()->prepare('UPDATE management_receipt_files SET owner_receipt_number=? WHERE id=?');foreach($periods as $periodId){$selectFiles->execute([(int)$periodId]);$files=$selectFiles->fetchAll();$used=[];foreach($files as $file)if((int)$file['owner_receipt_number']>0)$used[(int)$file['owner_receipt_number']]=true;$number=1;foreach($files as $file)if((int)$file['owner_receipt_number']<1){while(isset($used[$number]))$number++;$numberFile->execute([$number,(int)$file['id']]);$used[$number]=true;}}
        $message='Receipt Found tracking, Owner Receipt comments, numbering, and card matching are installed.';
    }catch(Throwable $exception){$error=$exception->getMessage();error_log('Receipt Found upgrade failed: '.$exception->getMessage());}
}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Receipt Tracking Upgrade</title><link rel="stylesheet" href="<?=e(app_url('/assets/design-system.css'))?>"></head><body class="znp-workspace-shell"><main style="width:min(720px,92%);margin:48px auto"><section class="card"><h1>Receipt Tracking Upgrade</h1><p>Adds Receipt Found tracking, Owner Receipt comments, stable receipt numbers, and Owner card matching.</p><?php if($message):?><div class="notice-success"><?=e($message)?></div><?php endif;?><?php if($error):?><div class="notice-error"><?=e($error)?></div><?php endif;?><?php if(!$message):?><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><button class="btn btn-primary" type="submit">Install Receipt Tracking</button></form><?php endif;?><p><a href="<?=e(app_url('/manage/receipts.php'))?>">Return to Management Receipts</a></p></section></main></body></html>
