<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/auth.php';require_login();if(!super_admin_role()){http_response_code(403);exit('Only a Super Admin may run database upgrades.');}$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!csrf_check((string)($_POST['csrf_token']??'')))$error='Your session expired. Refresh and try again.';
 else try{
  if(!db()->query("SHOW TABLES LIKE 'management_properties'")->fetchColumn())throw new RuntimeException('Install the Management Properties database upgrade first.');
  $columns=['management_fee_recipient_1'=>"VARCHAR(150) NOT NULL DEFAULT ''",'management_fee_percent_1'=>'DECIMAL(7,4) NOT NULL DEFAULT 4.0000','management_fee_recipient_2'=>"VARCHAR(150) NOT NULL DEFAULT ''",'management_fee_percent_2'=>'DECIMAL(7,4) NOT NULL DEFAULT 0.0000'];foreach($columns as $name=>$definition)if(!db()->query("SHOW COLUMNS FROM management_properties LIKE ".db()->quote($name))->fetchColumn())db()->exec("ALTER TABLE management_properties ADD COLUMN $name $definition");
  db()->exec("CREATE TABLE IF NOT EXISTS management_fee_records (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,management_property_id BIGINT UNSIGNED NOT NULL,entry_date DATE NOT NULL,fee_quarter TINYINT UNSIGNED NOT NULL,report_year SMALLINT UNSIGNED NOT NULL,room_revenue DECIMAL(14,2) NOT NULL DEFAULT 0.00,total_revenue DECIMAL(14,2) NOT NULL DEFAULT 0.00,recipient_1 VARCHAR(150) NOT NULL DEFAULT '',percent_1 DECIMAL(7,4) NOT NULL DEFAULT 0.0000,fee_1 DECIMAL(14,2) NOT NULL DEFAULT 0.00,recipient_2 VARCHAR(150) NOT NULL DEFAULT '',percent_2 DECIMAL(7,4) NOT NULL DEFAULT 0.0000,fee_2 DECIMAL(14,2) NOT NULL DEFAULT 0.00,total_fee DECIMAL(14,2) NOT NULL DEFAULT 0.00,created_by_admin_user_id BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_management_fee_records_year(management_property_id,report_year,entry_date)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  if(!db()->query("SHOW COLUMNS FROM management_fee_records LIKE 'check_number_1'")->fetchColumn())db()->exec("ALTER TABLE management_fee_records ADD COLUMN check_number_1 VARCHAR(100) NOT NULL DEFAULT '' AFTER fee_1");
  if(!db()->query("SHOW COLUMNS FROM management_fee_records LIKE 'check_number_2'")->fetchColumn())db()->exec("ALTER TABLE management_fee_records ADD COLUMN check_number_2 VARCHAR(100) NOT NULL DEFAULT '' AFTER fee_2");
  if(!db()->query("SHOW COLUMNS FROM management_fee_records LIKE 'fee_basis_revenue'")->fetchColumn())db()->exec("ALTER TABLE management_fee_records ADD COLUMN fee_basis_revenue DECIMAL(14,2) NOT NULL DEFAULT 0.00 AFTER total_revenue");
  $groups=db()->query('SELECT DISTINCT management_property_id,report_year FROM management_fee_records ORDER BY management_property_id,report_year')->fetchAll();$records=db()->prepare('SELECT id,total_revenue,percent_1,percent_2 FROM management_fee_records WHERE management_property_id=? AND report_year=? ORDER BY fee_quarter,entry_date,id');$recalculate=db()->prepare('UPDATE management_fee_records SET fee_basis_revenue=?,fee_1=?,fee_2=?,total_fee=? WHERE id=?');foreach($groups as $group){$records->execute([(int)$group['management_property_id'],(int)$group['report_year']]);$recognized=0.0;foreach($records->fetchAll() as $record){$basis=(float)$record['total_revenue']-$recognized;$recognized+=$basis;$fee1=$basis*(float)$record['percent_1']/100;$fee2=$basis*(float)$record['percent_2']/100;$recalculate->execute([number_format($basis,2,'.',''),number_format($fee1,2,'.',''),number_format($fee2,2,'.',''),number_format($fee1+$fee2,2,'.',''),(int)$record['id']]);}}
  db()->exec("CREATE TABLE IF NOT EXISTS management_fee_record_files (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,management_fee_record_id BIGINT UNSIGNED NOT NULL,file_path VARCHAR(500) NOT NULL,original_name VARCHAR(255) NOT NULL,mime_type VARCHAR(150) NOT NULL,file_size BIGINT UNSIGNED NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_management_fee_record_files_record(management_fee_record_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  $message='Management Fee records are installed.';
 }catch(Throwable $exception){$error=$exception->getMessage();error_log('Management Fee records upgrade failed: '.$exception->getMessage());}
}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Management Fee Records Upgrade</title><link rel="stylesheet" href="<?=e(app_url('/assets/design-system.css'))?>"></head><body class="znp-workspace-shell"><main style="width:min(720px,92%);margin:48px auto"><section class="card"><h1>Management Fee Records Upgrade</h1><p>Adds property-level 4% fee splits and the annual Management Fee register with record files.</p><?php if($message):?><div class="notice-success"><?=e($message)?></div><?php endif;?><?php if($error):?><div class="notice-error"><?=e($error)?></div><?php endif;?><?php if(!$message):?><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><button class="btn btn-primary" type="submit">Install Management Fee Records</button></form><?php endif;?><p><a href="<?=e(app_url('/manage/management_fees.php'))?>">Return to Management Fees</a></p></section></main></body></html>
