<?php
declare(strict_types=1);
require_once __DIR__.'/workspace_bootstrap.php';

// Start the public session before any HTML output so CSRF-protected forms
// (including the footer newsletter signup) share the same session on submit.
if (session_status() !== PHP_SESSION_ACTIVE) {
    session_start();
}

$pageTitle=$pageTitle??'ZNP Development';$activePage=$activePage??'home';$bodyClass=$bodyClass??'';
$seo=isset($pageSeo)&&is_array($pageSeo)?array_merge(seo_page_data($activePage),$pageSeo):seo_page_data($activePage);$canonical=current_canonical_url();$socialImage=trim(setting('seo_social_image','assets/images/home-slide-1.jpeg'));if($socialImage!==''&&!preg_match('#^https?://#i',$socialImage))$socialImage=rtrim(setting('website_url',app_public_url()),'/').'/'.ltrim($socialImage,'/');
$orgSchema=['@context'=>'https://schema.org','@type'=>'Organization','name'=>'ZNP Development','url'=>rtrim(setting('website_url',app_public_url()),'/'),'description'=>setting('seo_default_description','ZNP Development is a Texas-based real estate development and investment company specializing in multifamily, townhome, hospitality, commercial, and residential projects.'),'areaServed'=>'Texas','knowsAbout'=>['Real estate development','Multifamily development','Townhome development','Hospitality development','Commercial development','Residential development','Real estate investment opportunities','Asset management','Investor relations and capital']];
$ga=trim(setting('google_analytics_id'));$gtm=trim(setting('google_tag_manager_id'));
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title><?=e($seo['title'])?></title><meta name="description" content="<?=e($seo['description'])?>"><link rel="canonical" href="<?=e($canonical)?>">
<?php if(!empty($pageRobots)):?><meta name="robots" content="<?=e((string)$pageRobots)?>"><?php endif;?>
<meta property="og:type" content="website"><meta property="og:site_name" content="ZNP Development"><meta property="og:title" content="<?=e($seo['og_title'])?>"><meta property="og:description" content="<?=e($seo['og_description'])?>"><meta property="og:url" content="<?=e($canonical)?>"><?php if($socialImage):?><meta property="og:image" content="<?=e($socialImage)?>"><?php endif;?>
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="<?=e($seo['og_title'])?>"><meta name="twitter:description" content="<?=e($seo['og_description'])?>">
<?php if(!empty($pagePreloadImage)):?><link rel="preload" as="image" href="<?=e(app_url((string)$pagePreloadImage))?>" fetchpriority="high"><?php endif;?><link rel="icon" href="<?=e(app_url('/favicon.ico'))?>" sizes="any"><link rel="icon" type="image/png" href="<?=e(app_url('/assets/favicon.png'))?>"><?php if(!empty($pageManifest)):?><link rel="manifest" href="<?=e(app_url((string)$pageManifest))?>"><?php endif;?><?php if(!empty($pageThemeColor)):?><meta name="theme-color" content="<?=e((string)$pageThemeColor)?>"><?php endif;?><?php if(!empty($pageAppleMobileWebAppTitle)):?><meta name="mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"><meta name="apple-mobile-web-app-title" content="<?=e((string)$pageAppleMobileWebAppTitle)?>"><?php endif;?><?php if(!empty($pageAppleTouchIcon)):?><link rel="apple-touch-icon" sizes="180x180" href="<?=e(app_url((string)$pageAppleTouchIcon))?>"><?php endif;?><link rel="stylesheet" href="<?=e(app_url('/assets/site.css'))?>?v=<?=e(isset($pageAssetVersion)?(string)$pageAssetVersion:(function_exists('znp_asset_version')?znp_asset_version():'531'))?>"><link rel="stylesheet" href="<?=e(app_url('/assets/design-system.css'))?>?v=<?=e(function_exists('znp_asset_version')?znp_asset_version():'1')?>"><!-- ZNP PUBLIC SITE REDESIGN START --><link rel="stylesheet" href="<?=e(app_url('/assets/public-redesign.css'))?>?v=20260730-4"><!-- ZNP PUBLIC SITE REDESIGN END --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"><script type="application/ld+json"><?=json_encode($orgSchema,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?></script>
<?php foreach((array)($pageStylesheets??[]) as $pageStylesheet):?><link rel="stylesheet" href="<?=e(app_url((string)$pageStylesheet))?>"><?php endforeach;?>
<?php if($ga):?><script async src="https://www.googletagmanager.com/gtag/js?id=<?=e($ga)?>"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','<?=e($ga)?>');</script><?php endif;?>
<?php if($gtm):?><script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f)})(window,document,'script','dataLayer','<?=e($gtm)?>');</script><?php endif;?></head><body class="<?=e($bodyClass)?>">
<?php if($gtm):?><noscript><iframe class="znp-tracking-frame" src="https://www.googletagmanager.com/ns.html?id=<?=e($gtm)?>" height="0" width="0"></iframe></noscript><?php endif;?><!-- ZNP PUBLIC SITE REDESIGN START -->
<header class="site-header"><div class="container nav"><a class="brand" href="<?=e(app_url('/'))?>" aria-label="ZNP Development home"><span class="mark wordmark">ZNP Development</span></a><nav class="desktop" aria-label="Primary navigation"><a class="<?=$activePage==='home'?'active':''?>" href="<?=e(app_url('/'))?>">Home</a><a class="<?=$activePage==='team'?'active':''?>" href="<?=e(app_url('/team'))?>">Team</a><a class="<?=$activePage==='projects'?'active':''?>" href="<?=e(app_url('/projects'))?>">Projects</a><a class="<?=$activePage==='invest'?'active':''?>" href="<?=e(app_url('/invest'))?>">Invest</a></nav><a class="cta desktop-cta" href="<?=e(app_url('/contact'))?>">Start a Conversation<i class="fa-solid fa-pen" aria-hidden="true"></i></a><a class="portal-login-icon desktop-login" href="<?=e(app_url('/login'))?>" aria-label="Portal Access" title="Portal Access"><i class="fa-solid fa-right-to-bracket" aria-hidden="true"></i></a><button class="menu-btn" type="button" aria-label="Open menu" aria-expanded="false"><span></span><span></span><span></span></button></div></header>
<nav class="mobile-menu" aria-label="Mobile navigation"><a class="<?=$activePage==='home'?'active':''?>" href="<?=e(app_url('/'))?>">Home</a><a class="<?=$activePage==='team'?'active':''?>" href="<?=e(app_url('/team'))?>">Team</a><a class="<?=$activePage==='projects'?'active':''?>" href="<?=e(app_url('/projects'))?>">Projects</a><a class="<?=$activePage==='invest'?'active':''?>" href="<?=e(app_url('/invest'))?>">Invest</a><a class="cta" href="<?=e(app_url('/contact'))?>">Start a Conversation<i class="fa-solid fa-pen" aria-hidden="true"></i></a><a class="mobile-portal-login" href="<?=e(app_url('/login'))?>" aria-label="Portal Login"><i class="fa-solid fa-right-to-bracket" aria-hidden="true"></i><span>Portal Login</span></a></nav>
<!-- ZNP PUBLIC SITE REDESIGN END -->
