<?php
declare(strict_types=1);
require_once __DIR__.'/includes/bootstrap.php';
manage_require_admin();
header('Content-Type: application/json; charset=utf-8');
function fee_json(bool $ok,string $message,array $extra=[]):never{echo json_encode(array_merge(['ok'=>$ok,'message'=>$message],$extra),JSON_UNESCAPED_SLASHES);exit;}
if($_SERVER['REQUEST_METHOD']!=='POST'||!hash_equals(csrf_token(),(string)($_POST['csrf_token']??'')))fee_json(false,'Your session expired. Refresh and try again.');
$propertyId=(int)($_POST['property_id']??0);$year=(int)($_POST['report_year']??0);$month=(int)($_POST['report_month']??0);$category=(string)($_POST['category']??'');$feeType=(string)($_POST['fee_type']??'');$action=(string)($_POST['action']??'');
if(!manage_fees_schema_ready()||!manage_can_access_property($propertyId))fee_json(false,'Property access denied.');
$allowedCategories=['management'=>['flash_report'],'franchise'=>['statement','payment']];if(!isset($allowedCategories[$feeType]))fee_json(false,'Invalid fee type.');if($action!=='reset_month'&&!in_array($category,$allowedCategories[$feeType],true))fee_json(false,'Invalid fee upload.');$invalidPeriod=$year<2026||$year>2045||$month<1||$month>12;if($feeType==='management')$invalidPeriod=$invalidPeriod||!in_array($month,[3,6,9,12],true);else $invalidPeriod=$invalidPeriod||($year===2026&&$month<7);if($invalidPeriod)fee_json(false,'Invalid fee period.');
try{
 if($action==='reset_month'){
  $q=db()->prepare('SELECT id FROM management_fee_periods WHERE management_property_id=? AND fee_type=? AND report_year=? AND report_month=?');$q->execute([$propertyId,$feeType,$year,$month]);$periodId=(int)$q->fetchColumn();if($periodId<1)fee_json(true,'Month is already blank.');$q=db()->prepare('SELECT file_path FROM management_fee_files WHERE management_fee_period_id=?');$q->execute([$periodId]);$paths=array_map('strval',$q->fetchAll(PDO::FETCH_COLUMN));db()->beginTransaction();db()->prepare('DELETE FROM management_fee_files WHERE management_fee_period_id=?')->execute([$periodId]);db()->prepare('DELETE FROM management_fee_periods WHERE id=?')->execute([$periodId]);db()->commit();foreach($paths as $path)try{znp_storage_delete($path);}catch(Throwable $cleanup){error_log('Fee month reset file cleanup failed: '.$cleanup->getMessage());}fee_json(true,'Fee month reset.');
 }
 if($action==='upload'){
  $uploads=manage_store_fee_files($_FILES['files']??[],$propertyId,$year,$month,$feeType,$category);if(!$uploads)fee_json(false,'Choose at least one file.');
  try{db()->beginTransaction();db()->prepare("INSERT INTO management_fee_periods(management_property_id,fee_type,report_year,report_month,status,updated_by_admin_user_id) VALUES(?,?,?,?,'submitted',?) ON DUPLICATE KEY UPDATE status='submitted',updated_by_admin_user_id=VALUES(updated_by_admin_user_id)")->execute([$propertyId,$feeType,$year,$month,(int)($managementUser['id']??0)]);$q=db()->prepare('SELECT id FROM management_fee_periods WHERE management_property_id=? AND fee_type=? AND report_year=? AND report_month=?');$q->execute([$propertyId,$feeType,$year,$month]);$periodId=(int)$q->fetchColumn();$insert=db()->prepare('INSERT INTO management_fee_files(management_fee_period_id,file_category,file_path,original_name,mime_type,file_size) VALUES(?,?,?,?,?,?)');$items=[];foreach($uploads as $file){$insert->execute([$periodId,$category,$file['path'],$file['name'],$file['mime'],$file['size']]);$id=(int)db()->lastInsertId();$items[]=['id'=>$id,'name'=>$file['name'],'url'=>'fee_file.php?id='.$id];}db()->commit();fee_json(true,count($items)===1?'File uploaded.':'Files uploaded.',['files'=>$items,'period_status'=>'submitted']);}
  catch(Throwable $error){if(db()->inTransaction())db()->rollBack();foreach($uploads as $file)try{znp_storage_delete((string)$file['path']);}catch(Throwable $cleanup){}throw $error;}
 }
 if($action==='delete_file'){
  $id=(int)($_POST['file_id']??0);$q=db()->prepare('SELECT f.*,p.management_property_id,p.fee_type FROM management_fee_files f JOIN management_fee_periods p ON p.id=f.management_fee_period_id WHERE f.id=?');$q->execute([$id]);$file=$q->fetch();if(!$file||(int)$file['management_property_id']!==$propertyId||(string)$file['fee_type']!==$feeType||(string)$file['file_category']!==$category)fee_json(false,'File not found.');znp_storage_delete((string)$file['file_path']);db()->prepare('DELETE FROM management_fee_files WHERE id=?')->execute([$id]);$q=db()->prepare('SELECT COUNT(*) FROM management_fee_files WHERE management_fee_period_id=?');$q->execute([(int)$file['management_fee_period_id']]);$status=(int)$q->fetchColumn()>0?'submitted':'blank';if($status==='blank')db()->prepare('DELETE FROM management_fee_periods WHERE id=?')->execute([(int)$file['management_fee_period_id']]);fee_json(true,'File deleted.',['period_status'=>$status]);
 }
 fee_json(false,'Invalid action.');
}catch(Throwable $error){if(db()->inTransaction())db()->rollBack();error_log('Fee upload failed: '.$error->getMessage());fee_json(false,'The fee file change could not be saved.');}
