<?php
require_once __DIR__.'/includes/bootstrap.php';
$error='';$propertyId=manage_active_property_id();$property=$propertyId?manage_property($propertyId):null;
$years=range(2026,2045);$systemNow=new DateTimeImmutable('now',new DateTimeZone('America/Chicago'));$defaultPeriod=$systemNow->modify('first day of previous month');$defaultYear=(int)$defaultPeriod->format('Y');$defaultMonth=(int)$defaultPeriod->format('n');
if($_SERVER['REQUEST_METHOD']==='GET'&&!isset($_GET['year'])&&!isset($_GET['month'])){
    header('Location: month_end.php?year='.$defaultYear.'&month='.$defaultMonth);exit;
}
$selectedYear=(int)($_POST['report_year']??$_GET['year']??$defaultYear);$selectedMonth=(int)($_POST['report_month']??$_GET['month']??$defaultMonth);
if(!in_array($selectedYear,$years,true))$selectedYear=2026;
if($selectedMonth<1||$selectedMonth>12||($selectedYear===2026&&$selectedMonth<6))$selectedMonth=6;
if($_SERVER['REQUEST_METHOD']==='POST'&&$property&&manage_month_end_schema_ready()){
    if(!hash_equals(csrf_token(),(string)($_POST['csrf_token']??'')))$error='Your session expired. Please try again.';
    else{
        $action=(string)($_POST['action']??'save');$uploads=[];
        try{
            $find=db()->prepare('SELECT * FROM management_month_end_submissions WHERE management_property_id=? AND report_year=? AND report_month=?');
            $find->execute([$propertyId,$selectedYear,$selectedMonth]);$savedSubmission=$find->fetch()?:null;
            if($action==='unfinalize'){
                if(!manage_is_admin())throw new RuntimeException('Only a Super Admin may unfinalize a month.');
                if(!$savedSubmission||$savedSubmission['status']!=='finalized')throw new RuntimeException('This month is not finalized.');
                db()->prepare("UPDATE management_month_end_submissions SET status='submitted',submitted_by_admin_user_id=?,submitted_at=NOW() WHERE id=?")->execute([(int)($managementUser['id']??0),(int)$savedSubmission['id']]);
                header('Location: month_end.php?year='.$selectedYear.'&month='.$selectedMonth.'&unfinalized=1');exit;
            }
            if($action==='finalize'){
                if(!manage_is_admin())throw new RuntimeException('Only a Super Admin may finalize a month.');
                if(!$savedSubmission||$savedSubmission['status']!=='submitted')throw new RuntimeException('Submit this Month End before finalizing it.');
                if($savedSubmission['status']==='finalized')throw new RuntimeException('This month is already finalized. Unfinalize it before making further changes.');
                $uploads=manage_store_month_end_files($_FILES['final_files']??[],$propertyId,$selectedYear,$selectedMonth);
                db()->beginTransaction();$submissionId=(int)$savedSubmission['id'];
                $insert=db()->prepare('INSERT INTO management_month_end_files(management_month_end_submission_id,file_path,original_name,mime_type,file_size) VALUES(?,?,?,?,?)');
                foreach($uploads as $file)$insert->execute([$submissionId,$file['path'],$file['name'],$file['mime'],$file['size']]);
                db()->prepare("UPDATE management_month_end_submissions SET status='finalized',submitted_by_admin_user_id=?,submitted_at=NOW() WHERE id=?")->execute([(int)($managementUser['id']??0),$submissionId]);
                db()->commit();header('Location: month_end.php?year='.$selectedYear.'&month='.$selectedMonth.'&finalized=1');exit;
            }
            if($savedSubmission&&$savedSubmission['status']==='finalized')throw new RuntimeException('Unfinalize this month before making changes.');
            if(in_array((string)($property['pms_system']??'hotel_key'),['opera','hotel_key','fossee'],true))throw new RuntimeException('Month End values for this PMS can only be created from uploaded reports.');
            $source=$_POST;$values=manage_month_end_values($source,!empty($property['has_restaurant']));
            $uploads=manage_store_month_end_files($_FILES['report_files']??[],$propertyId,$selectedYear,$selectedMonth);
            if(!$uploads){$fileCount=0;if($savedSubmission){$count=db()->prepare('SELECT COUNT(*) FROM management_month_end_files WHERE management_month_end_submission_id=?');$count->execute([(int)$savedSubmission['id']]);$fileCount=(int)$count->fetchColumn();}if($fileCount<1)throw new RuntimeException('Upload at least one Month End report file.');}
            db()->beginTransaction();
            manage_save_month_end_values($propertyId,$selectedYear,$selectedMonth,$values,'submitted',(int)($managementUser['id']??0));
            $find->execute([$propertyId,$selectedYear,$selectedMonth]);$submissionId=(int)($find->fetch()['id']??0);
            $insert=db()->prepare('INSERT INTO management_month_end_files(management_month_end_submission_id,file_path,original_name,mime_type,file_size) VALUES(?,?,?,?,?)');
            foreach($uploads as $file)$insert->execute([$submissionId,$file['path'],$file['name'],$file['mime'],$file['size']]);
            db()->commit();header('Location: month_end.php?year='.$selectedYear.'&month='.$selectedMonth.'&submitted=1');exit;
        }catch(Throwable $e){
            if(db()->inTransaction())db()->rollBack();
            foreach($uploads as $file)try{znp_storage_delete((string)$file['path']);}catch(Throwable $cleanup){}
            $error=$e->getMessage();
        }
    }
}
$periodStatuses=[];$existing=null;$existingFiles=[];$taxCardStatuses=[];
if($property&&manage_month_end_schema_ready()){
    $calendar=db()->prepare('SELECT report_month,status FROM management_month_end_submissions WHERE management_property_id=? AND report_year=?');$calendar->execute([$propertyId,$selectedYear]);foreach($calendar->fetchAll() as $period)$periodStatuses[(int)$period['report_month']]=(string)$period['status']==='draft'?'blank':(string)$period['status'];
    $find=db()->prepare('SELECT * FROM management_month_end_submissions WHERE management_property_id=? AND report_year=? AND report_month=?');$find->execute([$propertyId,$selectedYear,$selectedMonth]);$existing=$find->fetch()?:null;
    if($existing)foreach(['state_tax','city_tax'] as $taxField){$adjustmentField=$taxField.'_adjustments';$existing[$taxField]=number_format(max(0,(float)($existing[$taxField]??0)-(float)($existing[$adjustmentField]??0)),2,'.','');$existing[$adjustmentField]='0.00';}
    if($existing){$files=db()->prepare('SELECT * FROM management_month_end_files WHERE management_month_end_submission_id=? ORDER BY id');$files->execute([(int)$existing['id']]);$existingFiles=$files->fetchAll();}
    $taxStatuses=db()->prepare('SELECT tax_key,status FROM management_month_end_tax_statuses WHERE management_property_id=? AND report_year=? AND report_month=?');$taxStatuses->execute([$propertyId,$selectedYear,$selectedMonth]);foreach($taxStatuses->fetchAll() as $taxStatus)$taxCardStatuses[(string)$taxStatus['tax_key']]=(string)$taxStatus['status'];
}
$isFinalized=$existing&&$existing['status']==='finalized';$pmsSystem=(string)($property['pms_system']??'hotel_key');$isOperaProperty=$pmsSystem==='opera';$isHotelKeyProperty=$pmsSystem==='hotel_key';$isFosseeProperty=$pmsSystem==='fossee';$isAutomatedProperty=$isOperaProperty||$isHotelKeyProperty||$isFosseeProperty;$hasCalculationParser=$isAutomatedProperty;$requiredReportCount=$isFosseeProperty?4:($isOperaProperty&& !empty($property['has_restaurant'])?4:2);$requiredExtension=$isHotelKeyProperty?'xlsx':'pdf';$automatedReportCount=count(array_filter($existingFiles,static fn(array $file):bool=>strtolower(pathinfo((string)$file['original_name'],PATHINFO_EXTENSION))===$requiredExtension));$showMonthEndValues=!$isAutomatedProperty||($automatedReportCount>=$requiredReportCount&&$existing&&in_array((string)$existing['status'],['submitted','finalized'],true));
require_once __DIR__.'/includes/header.php';
$months=[1=>'January','February','March','April','May','June','July','August','September','October','November','December'];
?>
<?php if(isset($_GET['submitted'])):?><div class="manage-alert success">Month End reports saved successfully.</div><?php endif;?><?php if(isset($_GET['finalized'])):?><div class="manage-alert success">Month End finalized successfully. All report values are now locked.</div><?php endif;?><?php if(isset($_GET['unfinalized'])):?><div class="manage-alert success">Month End returned to Submitted status and can now be edited.</div><?php endif;?><?php if($error):?><div class="manage-alert error"><?=manage_e($error)?></div><?php endif;?>
<?php if(!manage_month_end_schema_ready()):?><div class="manage-alert error">Run the <a href="<?=manage_e(app_url('/admin/upgrade_management_month_end_tax_adjustments.php'))?>">Month End Tax Fields database upgrade</a> to enable Month End reporting.</div>
<?php elseif($property):?>
<section class="manage-year-calendar manage-panel"><div class="manage-calendar-heading"><div><h2><?=$selectedYear?> Calendar</h2><p>Select a month to view, upload, or update its report.</p></div><div class="manage-calendar-actions"><form method="get"><label for="calendarYear">Year</label><select id="calendarYear" name="year" onchange="this.form.submit()"><?php foreach($years as $year):?><option value="<?=$year?>" <?=$selectedYear===$year?'selected':''?>><?=$year?></option><?php endforeach;?></select></form><?php if(manage_is_admin()&&!$isFinalized&&($existing||$taxCardStatuses)):?><button type="button" class="manage-reset-month-button" data-reset-month-end data-month-label="<?=manage_e($months[$selectedMonth].' '.$selectedYear)?>"><i class="fa-solid fa-rotate-left" aria-hidden="true"></i> Reset Month</button><?php endif;?></div></div><div class="manage-calendar-months"><?php foreach($months as $number=>$name):$available=!($selectedYear===2026&&$number<6);$status=$periodStatuses[$number]??'blank';$statusLabel=$status==='finalized'?'Finalized':($status==='submitted'?'Files & Numbers Loaded':'Not Ready');?><?php if($available):?><a class="manage-calendar-month <?=$selectedMonth===$number?'selected':''?> <?=manage_e($status)?>" href="?year=<?=$selectedYear?>&amp;month=<?=$number?>"><span class="manage-calendar-status-icon" aria-hidden="true"><i class="fa-solid <?=$status==='finalized'?'fa-lock':($status==='submitted'?'fa-file-circle-check':'fa-circle')?>"></i></span><span><?=$name?><small><?=manage_e($statusLabel)?></small></span></a><?php else:?><span class="manage-calendar-month unavailable"><span class="manage-calendar-status-icon" aria-hidden="true"><i class="fa-regular fa-circle"></i></span><span><?=$name?><small>Unavailable</small></span></span><?php endif;?><?php endforeach;?></div></section>
<div class="manage-month-end-layout"><section class="manage-month-end-main">
 <form method="post" enctype="multipart/form-data" class="manage-panel manage-month-end-form" data-autosave-url="month_end_autosave.php" data-calculation-workflow="<?=$isOperaProperty?'opera':($isHotelKeyProperty?'hotel_key':($isFosseeProperty?'fossee':'manual'))?>" data-required-reports="<?=$requiredReportCount?>" data-required-extension="<?=$requiredExtension?>"><input type="hidden" name="csrf_token" value="<?=manage_e(csrf_token())?>"><input type="hidden" name="property_id" value="<?=$propertyId?>"><input type="hidden" name="report_year" value="<?=$selectedYear?>"><input type="hidden" name="report_month" value="<?=$selectedMonth?>"><input type="hidden" name="total_revenue" value="<?=manage_e($existing['total_revenue']??'0.00')?>">
  <div class="manage-autosave-status" id="monthEndAutosaveStatus" role="status" aria-live="polite" <?=$isAutomatedProperty&&$automatedReportCount===0?'hidden':''?>><?=$isFinalized?'Finalized — values are locked':($isAutomatedProperty?('Values are filled only from validated '.($isHotelKeyProperty?'Excel':'PDF').' reports'):'Changes save automatically')?></div>
  <?php if($showMonthEndValues):?>
  <fieldset class="manage-month-end-values" <?=$isFinalized?'disabled':''?>>
  <section class="manage-office-number-fields manage-tax-fields"><h2>Office Numbers &amp; Taxes</h2><div class="manage-money-grid">
   <?php foreach(['rooms_available'=>'Total Rooms Available','rooms_occupied'=>'Total Rooms Sold'] as $field=>$label):?><label><?=$label?><?php if($isAutomatedProperty):?><small>Filled from the validated <?=$isHotelKeyProperty?'Occupancy Summary':'Manager Flash'?> report</small><?php endif;?><span class="manage-money-input manage-room-count-input <?=$isAutomatedProperty?'manage-calculated-money-input':''?>"><input type="number" min="0" step="1" name="<?=$field?>" inputmode="numeric" required value="<?=manage_e($existing[$field]??'0')?>" <?=$isAutomatedProperty?'readonly aria-readonly="true" data-report-calculated':''?>></span></label><?php endforeach;?>
   <?php foreach(['room_revenue'=>'Room Revenue','suite_shop_revenue'=>'Suite Shop Revenue'] as $field=>$label):?><label><?=$label?><?php if($isAutomatedProperty):?><small>Filled from validated <?=$isOperaProperty?'Opera':($isHotelKeyProperty?'HotelKey':'Fossee')?> reports</small><?php endif;?><span class="manage-money-input <?=$isAutomatedProperty?'manage-calculated-money-input':''?>"><span>$</span><input name="<?=$field?>" inputmode="decimal" required value="<?=number_format((float)($existing[$field]??0),2,'.',',')?>" <?=$isAutomatedProperty?'readonly aria-readonly="true" data-report-calculated':''?>></span></label><?php endforeach;?>
   <?php foreach(['state_tax'=>'State Tax Posted','city_tax'=>'City Tax Posted'] as $field=>$label):$reportLocked=$isAutomatedProperty;?><label><?=$label?><?php if($reportLocked):?><small>Filled from the validated <?=$isOperaProperty?'Opera tax subgroup total':($isHotelKeyProperty?'HotelKey Payable Tax column':'Fossee Tax Posted total')?></small><?php endif;?><span class="manage-money-input <?=$reportLocked?'manage-calculated-money-input':''?>"><span>$</span><input id="<?=$field?>" name="<?=$field?>" inputmode="decimal" required value="<?=number_format((float)($existing[$field]??0),2,'.',',')?>" <?=$reportLocked?'readonly aria-readonly="true" data-report-calculated':''?>></span></label><?php endforeach;?>
   <?php if($isOperaProperty&&(float)($existing['banquet_tax']??0)>0):?><label>Banquet Tax Posted <small>Detected from the Opera report subgroup total</small><span class="manage-money-input manage-calculated-money-input"><span>$</span><input id="banquet_tax" name="banquet_tax" readonly aria-readonly="true" data-opera-calculated value="<?=number_format((float)$existing['banquet_tax'],2,'.',',')?>"></span></label><?php endif;?>
   <label>Sales Tax <small><?=$isOperaProperty?'Filled from the validated tax subgroup total':($isHotelKeyProperty?'Filled from the HotelKey Payable Tax column':($isFosseeProperty?'Filled from the Fossee Tax Posted total':'8.25% of Suite Shop Revenue'))?></small><span class="manage-money-input manage-calculated-money-input"><span>$</span><input id="sales_tax" name="sales_tax" readonly aria-readonly="true" <?=$isAutomatedProperty?'data-report-calculated':'data-suite-shop-sales-tax'?> value="<?=number_format((float)($existing['sales_tax']??((float)($existing['suite_shop_revenue']??0)*0.0825)),2,'.',',')?>"></span></label>
  </div></section>
  <?php if(!empty($property['has_restaurant'])):?><section class="manage-restaurant-tax-fields"><h2>Restaurant Taxes</h2><div class="manage-money-grid"><?php foreach(['liquor_net_sales'=>'Liquor Net Sales','beer_net_sales'=>'Beer Net Sales','wine_net_sales'=>'Wine Net Sales','taxable_sales_mix_bev_sales_tax'=>'Mix Bev Sales Tax Taxable Sales'] as $field=>$label):?><label><?=$label?><?php if($isAutomatedProperty):?><small><?=$isOperaProperty?'Filled from validated restaurant reports':'Not supplied by the current '.($isHotelKeyProperty?'HotelKey':'Fossee').' reports'?></small><?php endif;?><span class="manage-money-input <?=$isAutomatedProperty?'manage-calculated-money-input':''?>"><span>$</span><input name="<?=$field?>" inputmode="decimal" required value="<?=number_format((float)($existing[$field]??0),2,'.',',')?>" <?=$isAutomatedProperty?'readonly aria-readonly="true" data-report-calculated':''?>></span></label><?php endforeach;?></div></section><?php endif;?>
  </fieldset>
  <?php endif;?>
  <?php if(!$isFinalized):?><label class="manage-file-upload manage-file-drop-zone" data-drop-upload><strong><i class="fa-solid fa-cloud-arrow-up" aria-hidden="true"></i> <?=$isOperaProperty?'Opera PDF Reports':($isHotelKeyProperty?'HotelKey Excel Reports':($isFosseeProperty?'Fossee PDF Reports':'Report Files'))?></strong><span><?=$isOperaProperty?(!empty($property['has_restaurant'])?'Drag and Drop Four Reports: Manager Flash, FinDeptCodes, and 2 Restaurant Reports':'Drag and Drop Two Reports: Manager Flash and Findeptcodes Report'):($isHotelKeyProperty?'Drag and Drop Two Excel Reports: Occupancy Summary and Tax Report':($isFosseeProperty?'Drag and Drop Four Reports: Manager Flash, City Tax, State Tax, and Sales Tax. Use clear, straight, full-page scans.':'Drag and drop multiple files here, or click to browse. Files upload automatically. Up to 25 MB each.'))?></span><span class="manage-upload-selection" aria-live="polite">No files selected</span><input type="file" name="report_files[]" multiple accept="<?=$isOperaProperty||$isFosseeProperty?'.pdf':($isHotelKeyProperty?'.xlsx':'.pdf,.xls,.xlsx,.csv,.doc,.docx,.jpg,.jpeg,.png,.webp')?>"></label><?php endif;?>
  <div class="manage-existing-files" id="monthEndFileList" <?=$isAutomatedProperty&&$automatedReportCount===0?'hidden':''?>><strong>Files attached to this month</strong><?php foreach($existingFiles as $file):?><span class="manage-file-item" data-file-id="<?=(int)$file['id']?>"><a href="month_end_file.php?id=<?=(int)$file['id']?>"><i class="fa-solid fa-paperclip"></i> <?=manage_e($file['original_name'])?></a><?php if(!$isFinalized):?><button type="button" class="manage-file-delete" data-file-id="<?=(int)$file['id']?>" aria-label="Delete <?=manage_e($file['original_name'])?>"><i class="fa-solid fa-trash"></i></button><?php endif;?></span><?php endforeach;?></div>
  <?php if($hasCalculationParser&&!$isFinalized):?><div class="manage-opera-calculations" <?=($automatedReportCount===0||!manage_is_admin())?'hidden':''?>><button type="button" class="manage-button primary" data-find-calculations <?=$automatedReportCount<$requiredReportCount?'disabled':''?>><i class="fa-solid fa-wand-magic-sparkles" aria-hidden="true"></i> FIND CALCULATIONS</button><small data-calculation-help><?=$automatedReportCount<$requiredReportCount?'Upload all '.$requiredReportCount.' required reports to enable calculations.':'Validates all required '.($isOperaProperty?'Opera':($isHotelKeyProperty?'HotelKey':'Fossee')).' reports against '.$months[$selectedMonth].' '.$selectedYear.'.'?></small></div><?php endif;?>
  <?php if(!$isFinalized&&!$isAutomatedProperty):?><button class="manage-button primary manage-submit-button" name="action" value="save"><?= $existing&&$existing['status']==='submitted'?'Save Changes':'Submit Month End'?></button><?php endif;?>
 </form>
 <?php if(manage_is_admin()&&$showMonthEndValues):?>
 <section class="manage-panel manage-finalize-panel">
  <div><h2>Finalize Month</h2><p>Review the calculated revenue and property bank details, attach any final supporting reports, then finalize this period.</p></div>
  <div class="manage-finalize-calculations">
   <?php $calculationGroups=[
    'city_tax'=>['City Tax',[
     ['Room Revenue','room_revenue',1,'divide'],['Taxable Revenue','city_tax',0.09,'divide'],['Difference','room_revenue,city_tax',0.09,'difference'],['City Tax Posted','city_tax',1,'divide']
    ]],
    'state_tax'=>['State Tax',[
     ['Room Revenue','room_revenue',1,'divide'],['Taxable Revenue','state_tax',0.06,'divide'],['Difference','room_revenue,state_tax',0.06,'difference'],['State Tax Posted','state_tax',1,'divide']
    ]],
   'suite_shop_tax'=>['Sales Tax ('.ucfirst((string)($property['suite_shop_tax_frequency']??'monthly')).')',[
     ['Suite Shop Revenue','suite_shop_revenue',1,'divide'],[$isFosseeProperty?'Sales Tax Posted':'Sales Tax Due','sales_tax',1,'divide']
    ]]
   ];if((float)($existing['banquet_tax']??0)>0)$calculationGroups['banquet_tax']=['Banquet Tax',[['Banquet Tax Posted','banquet_tax',1,'divide']]];if(!empty($property['has_restaurant'])){$calculationGroups['mixed_beverage_gross_receipts']=['Mixed Beverage Gross Receipts',[['Liquor Net Sales','liquor_net_sales',1,'divide'],['Beer Net Sales','beer_net_sales',1,'divide'],['Wine Net Sales','wine_net_sales',1,'divide'],['Gross Receipts','liquor_net_sales,beer_net_sales,wine_net_sales',1,'divide'],['Mixed Beverage Gross Receipts Tax Due','liquor_net_sales,beer_net_sales,wine_net_sales',0.0670,'multiply']]];$calculationGroups['mixed_beverage_sales_tax']=['Mixed Beverage Sales Tax',[['Taxable Sales','taxable_sales_mix_bev_sales_tax',1,'divide'],['Mixed Beverage Sales Tax Due','taxable_sales_mix_bev_sales_tax',0.0825,'multiply']]];}foreach($calculationGroups as $taxKey=>[$groupTitle,$calculations]):$taxStatus=$taxCardStatuses[$taxKey]??'unsubmitted';?><section class="manage-finalize-calculation-group" data-tax-card="<?=$taxKey?>"><div class="manage-finalize-calculation-heading"><h3><?=$groupTitle?></h3><button type="button" class="manage-tax-status-button <?=$taxStatus?>" data-tax-key="<?=$taxKey?>" aria-pressed="<?=$taxStatus==='submitted'?'true':'false'?>"><span class="manage-tax-status-dot"></span><span class="manage-tax-status-label"><?=ucfirst($taxStatus)?></span></button></div><div class="manage-finalize-calculation-grid"><?php foreach($calculations as [$label,$sources,$rate,$mode]):$sourceValues=[];foreach(explode(',',$sources) as $source){$negative=str_starts_with($source,'-');$sourceName=$negative?substr($source,1):$source;$sourceAmount=(float)($existing[$sourceName]??0);$sourceValues[]=$negative?-$sourceAmount:$sourceAmount;}$sourceTotal=array_sum($sourceValues);if($mode==='multiply')$calculated=$sourceTotal*$rate;elseif($mode==='difference')$calculated=($sourceValues[0]??0)-(array_sum(array_slice($sourceValues,1))/$rate);else $calculated=$sourceTotal/$rate;$isCopyCalculation=($label==='Taxable Revenue'&&in_array($taxKey,['city_tax','state_tax'],true))||($taxKey==='suite_shop_tax'&&$label==='Suite Shop Revenue')||in_array($taxKey,['mixed_beverage_gross_receipts','mixed_beverage_sales_tax'],true);?><label><?=$label?><span class="manage-money-input <?=$isCopyCalculation?'manage-copy-money-field':''?>"><span>$</span><input readonly data-calculation-sources="<?=$sources?>" data-calculation-rate="<?=$rate?>" data-calculation-mode="<?=$mode?>" value="<?=number_format($calculated,2,'.',',')?>" <?=$isCopyCalculation?'data-copy-bank-value title="Click to copy '.manage_e($label).'"':''?>><?php if($isCopyCalculation):?><button type="button" data-copy-bank-button aria-label="Copy <?=manage_e($label)?>"><i class="fa-regular fa-copy" aria-hidden="true"></i><span>Copy</span></button><?php endif;?></span></label><?php endforeach;?></div></section><?php endforeach;?>
  </div>
  <div class="manage-finalize-bank-grid"><?php foreach([['Account Name',(string)($property['bank_account_name']??'')],['Bank Account Number',manage_plain_bank_value($property['bank_account_number']??'')],['Bank Routing Number',manage_plain_bank_value($property['bank_routing_number']??'')]] as [$bankLabel,$bankValue]):?><label><?=$bankLabel?><span class="manage-copy-bank-field"><input readonly value="<?=manage_e($bankValue)?>" data-copy-bank-value title="Click to copy <?=$bankLabel?>"><button type="button" data-copy-bank-button aria-label="Copy <?=$bankLabel?>"><i class="fa-regular fa-copy" aria-hidden="true"></i><span>Copy</span></button></span></label><?php endforeach;?></div>
  <form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?=manage_e(csrf_token())?>"><input type="hidden" name="property_id" value="<?=$propertyId?>"><input type="hidden" name="report_year" value="<?=$selectedYear?>"><input type="hidden" name="report_month" value="<?=$selectedMonth?>"><?php if($isFinalized):?><p class="manage-finalized-note"><i class="fa-solid fa-lock"></i> This report is finalized. Unfinalize it before changing any numbers or files.</p><button class="manage-button manage-unfinalize-button" name="action" value="unfinalize">Unfinalize Report</button><?php else:?><label class="manage-file-upload manage-file-drop-zone" data-drop-upload><strong><i class="fa-solid fa-cloud-arrow-up" aria-hidden="true"></i> Additional Final Files</strong><span>Optional — drag and drop multiple files here, or click to browse.</span><span class="manage-upload-selection" aria-live="polite">No files selected</span><input type="file" name="final_files[]" multiple accept=".pdf,.xls,.xlsx,.csv,.doc,.docx,.jpg,.jpeg,.png,.webp"></label><?php if(!$existing||$existing['status']!=='submitted'):?><p class="manage-finalized-note"><i class="fa-solid fa-circle-info"></i> Submit the Month End form before finalizing this month.</p><?php endif;?><button class="manage-button manage-finalize-button" name="action" value="finalize" <?=!$existing||$existing['status']!=='submitted'?'disabled':''?>>Finalize</button><?php endif;?></form>
 </section>
 <?php endif;?>
</section></div>
<?php $stateTaxUrl=trim((string)($property['state_tax_url']??''));$cityTaxUrl=trim((string)($property['city_tax_url']??''));$taxNotes=trim((string)($property['tax_notes']??''));?>
<section class="manage-panel manage-property-tax-resources">
 <div class="manage-property-tax-resources-heading"><div><h2>TAX Notes</h2><p><?=manage_e($property['property_name'])?> tax resources and filing notes.</p></div><div class="manage-property-tax-links"><?php if($stateTaxUrl!==''):?><a class="manage-button" href="<?=manage_e($stateTaxUrl)?>" target="_blank" rel="noopener noreferrer"><i class="fa-solid fa-arrow-up-right-from-square" aria-hidden="true"></i> STATE TAX</a><?php endif;?><?php if($cityTaxUrl!==''):?><a class="manage-button" href="<?=manage_e($cityTaxUrl)?>" target="_blank" rel="noopener noreferrer"><i class="fa-solid fa-arrow-up-right-from-square" aria-hidden="true"></i> CITY TAX</a><?php endif;?></div></div>
 <div class="manage-tax-notes-content"><?=$taxNotes!==''?nl2br(manage_e($taxNotes)):'No TAX notes have been added for this property.'?></div>
</section>
<?php if($isFosseeProperty&&!$isFinalized):?>
<div class="manage-calculation-modal" data-calculation-modal hidden role="dialog" aria-modal="true" aria-labelledby="fosseeCalculationTitle" aria-describedby="fosseeCalculationMessage">
 <div class="manage-calculation-dialog" data-calculation-dialog data-state="running">
  <button type="button" class="manage-calculation-close" data-calculation-modal-close hidden aria-label="Close calculation status"><i class="fa-solid fa-xmark" aria-hidden="true"></i></button>
  <div class="manage-calculation-spinner" data-calculation-spinner aria-hidden="true"></div>
  <div class="manage-calculation-result-icon" data-calculation-result-icon hidden aria-hidden="true"></div>
  <h2 id="fosseeCalculationTitle" data-calculation-modal-title>Calculating Month End</h2>
  <p id="fosseeCalculationMessage" data-calculation-modal-message>Preparing Fossee reports…</p>
  <div class="manage-calculation-progress" role="progressbar" aria-label="Fossee calculation progress" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><span data-calculation-progress></span></div>
  <small data-calculation-modal-detail>Please keep this page open while the four reports are read.</small>
 </div>
</div>
<?php endif;?>
<?php endif;?>
<script src="assets/month-end-autosave.js?v=<?=manage_e(znp_asset_version())?>-workflow-status5" defer></script>
<?php require_once __DIR__.'/includes/footer.php';?>
