<?php
require_once __DIR__.'/includes/bootstrap.php';
manage_require_admin();
$message='';$error='';$edit=null;$pmsOptions=['hotel_key'=>'Hotel Key','opera'=>'Opera','fossee'=>'Fossee'];
$defaultStateTaxUrl='https://security.app.cpa.state.tx.us/';
$defaultCityTaxUrl='https://cityoflongviewtx.tylerportico.com/css/citizen-selfservice-bl/bl/dashboard/guest';
if(!manage_schema_ready()||!manage_month_end_schema_ready()||!manage_management_fee_records_schema_ready()||!manage_bank_deposits_schema_ready())$error='Run the current Management database upgrades before adding or editing hotels.';
if($_SERVER['REQUEST_METHOD']==='POST'&&manage_schema_ready()&&manage_month_end_schema_ready()&&manage_management_fee_records_schema_ready()&&manage_bank_deposits_schema_ready()){
  if(!hash_equals(csrf_token(),(string)($_POST['csrf_token']??'')))$error='Your session expired. Please try again.';
  else{
    $id=(int)($_POST['id']??0);$name=trim((string)($_POST['property_name']??''));$address=trim((string)($_POST['address_line1']??''));$city=trim((string)($_POST['city']??''));$state=strtoupper(trim((string)($_POST['state']??'')));$zip=trim((string)($_POST['postal_code']??''));$phone=trim((string)($_POST['phone']??''));$gm=strtolower(trim((string)($_POST['gm_email']??'')));$sales=strtolower(trim((string)($_POST['sales_email']??'')));$hasRestaurant=isset($_POST['has_restaurant'])?1:0;$pmsSystem=(string)($_POST['pms_system']??'hotel_key');if(!isset($pmsOptions[$pmsSystem]))$pmsSystem='hotel_key';$participatesBankDeposits=isset($_POST['participates_bank_deposits'])?1:0;$suiteShopTaxFrequency=(string)($_POST['suite_shop_tax_frequency']??'monthly');if(!in_array($suiteShopTaxFrequency,['monthly','quarterly'],true))$suiteShopTaxFrequency='monthly';$stateTaxUrl=mb_substr(trim((string)($_POST['state_tax_url']??$defaultStateTaxUrl)),0,500);$cityTaxUrl=mb_substr(trim((string)($_POST['city_tax_url']??$defaultCityTaxUrl)),0,500);$taxNotes=mb_substr(trim((string)($_POST['tax_notes']??'')),0,20000);$bankAccountName=trim((string)($_POST['bank_account_name']??''));$bankAccountNumber=trim((string)($_POST['bank_account_number']??''));$bankRoutingNumber=trim((string)($_POST['bank_routing_number']??''));$feeRecipient1=trim((string)($_POST['management_fee_recipient_1']??''));$feeRecipient2=trim((string)($_POST['management_fee_recipient_2']??''));$feePercent1=(float)($_POST['management_fee_percent_1']??0);$feePercent2=(float)($_POST['management_fee_percent_2']??0);
    $stateTaxScheme=strtolower((string)parse_url($stateTaxUrl,PHP_URL_SCHEME));$cityTaxScheme=strtolower((string)parse_url($cityTaxUrl,PHP_URL_SCHEME));
    if($name===''||$address===''||$city===''||$state===''||$zip===''||$phone===''||!filter_var($gm,FILTER_VALIDATE_EMAIL)||!filter_var($sales,FILTER_VALIDATE_EMAIL))$error='Complete every property field and enter valid GM and Sales email addresses.';
    elseif(!filter_var($stateTaxUrl,FILTER_VALIDATE_URL)||!in_array($stateTaxScheme,['http','https'],true)||!filter_var($cityTaxUrl,FILTER_VALIDATE_URL)||!in_array($cityTaxScheme,['http','https'],true))$error='Enter valid STATE TAX and CITY TAX links.';
    elseif($feeRecipient1===''||$feePercent1<=0||$feePercent2<0||($feeRecipient2===''&&$feePercent2>0)||($feeRecipient2!==''&&$feePercent2<=0)||abs(($feePercent1+$feePercent2)-4.0)>0.0001)$error='Management Fee recipients and percentages must be complete and total exactly 4%.';
    else try{
      $oldLogo='';if($id){$q=db()->prepare('SELECT logo_path FROM management_properties WHERE id=?');$q->execute([$id]);$oldLogo=(string)($q->fetchColumn()?:'');}
      $upload=manage_store_logo($_FILES['logo']??[]);
      $logo=$upload['path']??$oldLogo;
      if($id){$s=db()->prepare('UPDATE management_properties SET property_name=?,logo_path=?,address_line1=?,city=?,state=?,postal_code=?,phone=?,gm_email=?,sales_email=?,has_restaurant=?,pms_system=?,participates_bank_deposits=?,suite_shop_tax_frequency=?,state_tax_url=?,city_tax_url=?,tax_notes=?,bank_account_name=?,bank_account_number=?,bank_routing_number=?,management_fee_recipient_1=?,management_fee_percent_1=?,management_fee_recipient_2=?,management_fee_percent_2=?,is_active=? WHERE id=?');$s->execute([$name,$logo,$address,$city,$state,$zip,$phone,$gm,$sales,$hasRestaurant,$pmsSystem,$participatesBankDeposits,$suiteShopTaxFrequency,$stateTaxUrl,$cityTaxUrl,$taxNotes,$bankAccountName,$bankAccountNumber,$bankRoutingNumber,$feeRecipient1,number_format($feePercent1,4,'.',''),$feeRecipient2,number_format($feePercent2,4,'.',''),isset($_POST['is_active'])?1:0,$id]);}
      else{$s=db()->prepare('INSERT INTO management_properties(property_name,logo_path,address_line1,city,state,postal_code,phone,gm_email,sales_email,has_restaurant,pms_system,participates_bank_deposits,suite_shop_tax_frequency,state_tax_url,city_tax_url,tax_notes,bank_account_name,bank_account_number,bank_routing_number,management_fee_recipient_1,management_fee_percent_1,management_fee_recipient_2,management_fee_percent_2,is_active) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1)');$s->execute([$name,$logo,$address,$city,$state,$zip,$phone,$gm,$sales,$hasRestaurant,$pmsSystem,$participatesBankDeposits,$suiteShopTaxFrequency,$stateTaxUrl,$cityTaxUrl,$taxNotes,$bankAccountName,$bankAccountNumber,$bankRoutingNumber,$feeRecipient1,number_format($feePercent1,4,'.',''),$feeRecipient2,number_format($feePercent2,4,'.','')]);}
      if($upload&&$oldLogo!==''&&$oldLogo!==$logo)try{znp_storage_delete($oldLogo);}catch(Throwable $cleanup){error_log('Old property logo cleanup failed: '.$cleanup->getMessage());}
      header('Location: properties.php?saved=1');exit;
    }catch(Throwable $e){if(!empty($upload['path']))try{znp_storage_delete((string)$upload['path']);}catch(Throwable $cleanup){}$error=$e->getMessage();}
  }
}
if(isset($_GET['edit'])&&manage_schema_ready()){$s=db()->prepare('SELECT * FROM management_properties WHERE id=?');$s->execute([(int)$_GET['edit']]);$edit=$s->fetch()?:null;if($edit){$edit['bank_account_number']=manage_plain_bank_value($edit['bank_account_number']??'');$edit['bank_routing_number']=manage_plain_bank_value($edit['bank_routing_number']??'');}}
$showPropertyForm=$edit!==null||isset($_GET['add'])||$_SERVER['REQUEST_METHOD']==='POST';
$properties=manage_schema_ready()?manage_properties(true):[];
require_once __DIR__.'/includes/header.php';
?>
<section class="manage-page-heading"><h1>Management Settings</h1><p>Manage properties, users, and global receipt categories.</p></section>
<?php require __DIR__.'/includes/settings_tabs.php';?>
<section class="manage-section-heading manage-section-heading-actions"><div><h2>Properties</h2><p>Add hotels and maintain their operating contacts.</p></div><?php if(!$showPropertyForm):?><a class="manage-button primary" href="properties.php?add=1"><i class="fa-solid fa-plus" aria-hidden="true"></i> Add Property</a><?php endif;?></section>
<?php if(isset($_GET['saved'])):?><div class="manage-alert success">Property saved.</div><?php endif;?>
<?php if($error):?><div class="manage-alert error"><?=manage_e($error)?></div><?php endif;?>
<?php if(manage_schema_ready()&&manage_month_end_schema_ready()&&manage_management_fee_records_schema_ready()&&manage_bank_deposits_schema_ready()):?>
<?php if($showPropertyForm):?><section class="manage-panel manage-property-editor znp-mb-5"><div class="manage-property-editor-heading"><div><h2><?=$edit?'Edit Property':'Add Property'?></h2><p><?=$edit?'Update this hotel’s information and operating settings.':'Enter the hotel’s information and operating settings.'?></p></div><a class="manage-button" href="properties.php">Close</a></div><form method="post" enctype="multipart/form-data" class="manage-form-grid"><input type="hidden" name="csrf_token" value="<?=manage_e(csrf_token())?>"><input type="hidden" name="id" value="<?=(int)($edit['id']??0)?>">
<label>Hotel Name<input name="property_name" required value="<?=manage_e($edit['property_name']??'')?>"></label><label>Logo (JPG, PNG, WebP — 5 MB)<input type="file" name="logo" accept=".jpg,.jpeg,.png,.webp"></label>
<label class="manage-form-full">Street Address<input name="address_line1" required value="<?=manage_e($edit['address_line1']??'')?>"></label><label>City<input name="city" required value="<?=manage_e($edit['city']??'')?>"></label><label>State<input name="state" maxlength="60" required value="<?=manage_e($edit['state']??'')?>"></label><label>ZIP Code<input name="postal_code" required value="<?=manage_e($edit['postal_code']??'')?>"></label><label>Phone<input name="phone" required value="<?=manage_e($edit['phone']??'')?>"></label><label>GM Email<input type="email" name="gm_email" required value="<?=manage_e($edit['gm_email']??'')?>"></label><label>Sales Email<input type="email" name="sales_email" required value="<?=manage_e($edit['sales_email']??'')?>"></label>
<label class="manage-property-flag"><span><input type="checkbox" name="has_restaurant" value="1" <?=!empty($edit['has_restaurant'])?'checked':''?>> Restaurant</span><small>Show restaurant tax fields on Month End reports.</small></label>
<label>PMS<select name="pms_system"><?php $selectedPms=(string)($_POST['pms_system']??$edit['pms_system']??'hotel_key');foreach($pmsOptions as $pmsValue=>$pmsLabel):?><option value="<?=$pmsValue?>" <?=$selectedPms===$pmsValue?'selected':''?>><?=$pmsLabel?></option><?php endforeach;?></select></label>
<label class="manage-property-flag"><span><input type="checkbox" name="participates_bank_deposits" value="1" <?=($_SERVER['REQUEST_METHOD']==='POST'?isset($_POST['participates_bank_deposits']):(!$edit||!empty($edit['participates_bank_deposits'])))?'checked':''?>> Participates in Bank Deposits</span><small>Show the Bank Deposits uploader and include this property in the admin calendar.</small></label>
<label>Suite Shop Tax Due<select name="suite_shop_tax_frequency"><option value="monthly" <?=($edit['suite_shop_tax_frequency']??'monthly')==='monthly'?'selected':''?>>Monthly</option><option value="quarterly" <?=($edit['suite_shop_tax_frequency']??'monthly')==='quarterly'?'selected':''?>>Quarterly</option></select></label>
<fieldset class="manage-form-full manage-bank-settings manage-tax-settings"><legend>Tax Links &amp; Notes</legend><div class="manage-form-grid"><label>STATE TAX Link<input type="url" name="state_tax_url" maxlength="500" required value="<?=manage_e($_POST['state_tax_url']??$edit['state_tax_url']??$defaultStateTaxUrl)?>"></label><label>CITY TAX Link<input type="url" name="city_tax_url" maxlength="500" required value="<?=manage_e($_POST['city_tax_url']??$edit['city_tax_url']??$defaultCityTaxUrl)?>"></label><label class="manage-form-full">TAX Notes<textarea name="tax_notes" rows="5" maxlength="20000" placeholder="Property-specific tax filing notes"><?=manage_e($_POST['tax_notes']??$edit['tax_notes']??'')?></textarea></label></div></fieldset>
<fieldset class="manage-form-full manage-bank-settings"><legend>Management Fee Breakdown (Total 4%)</legend><div class="manage-form-grid"><label>Recipient 1<input name="management_fee_recipient_1" maxlength="150" required value="<?=manage_e($edit['management_fee_recipient_1']??'')?>" placeholder="Name"></label><label>Fee 1 (%)<input type="number" name="management_fee_percent_1" min="0.0001" max="4" step="0.0001" required value="<?=manage_e($edit['management_fee_percent_1']??'4.0000')?>"></label><label>Recipient 2 (Optional)<input name="management_fee_recipient_2" maxlength="150" value="<?=manage_e($edit['management_fee_recipient_2']??'')?>" placeholder="Name"></label><label>Fee 2 (%)<input type="number" name="management_fee_percent_2" min="0" max="4" step="0.0001" value="<?=manage_e($edit['management_fee_percent_2']??'0.0000')?>"></label></div><small>Use one or two recipients. Their percentages must total exactly 4%.</small></fieldset>
<fieldset class="manage-form-full manage-bank-settings"><legend>Bank Info</legend><div class="manage-form-grid"><label>Account Name<input name="bank_account_name" autocomplete="off" value="<?=manage_e($edit['bank_account_name']??'')?>"></label><label>Bank Account Number<input name="bank_account_number" autocomplete="off" inputmode="numeric" value="<?=manage_e($edit['bank_account_number']??'')?>"></label><label>Bank Routing Number<input name="bank_routing_number" autocomplete="off" inputmode="numeric" value="<?=manage_e($edit['bank_routing_number']??'')?>"></label></div><small>Bank information remains visible for authorized Management administrators.</small></fieldset>
<?php if($edit):?><label><span><input type="checkbox" name="is_active" value="1" <?=!empty($edit['is_active'])?'checked':''?>> Active property</span></label><?php endif;?><div class="manage-form-full"><button class="manage-button primary"><?= $edit?'Update':'Add'?> Property</button><a class="manage-button" href="properties.php">Cancel</a></div></form></section><?php endif;?>
<section class="manage-property-grid"><?php foreach($properties as $property):?><article class="manage-property-card <?=!$property['is_active']?'inactive':''?>"><div class="manage-property-card-logo"><?php if($property['logo_path']):?><img src="<?=manage_e(znp_storage_url((string)$property['logo_path']))?>" alt="<?=manage_e($property['property_name'])?> logo"><?php else:?><div class="manage-property-logo-placeholder"><i class="fa-solid fa-hotel"></i></div><?php endif;?></div><div class="manage-property-card-content"><header><div><h2><?=manage_e($property['property_name'])?></h2><span class="manage-status <?=$property['is_active']?'active':'inactive'?>"><?=$property['is_active']?'Active':'Inactive'?></span></div><a class="manage-button" href="properties.php?edit=<?=(int)$property['id']?>"><i class="fa-solid fa-pen" aria-hidden="true"></i> Edit</a></header><dl class="manage-property-details"><div><dt><i class="fa-solid fa-location-dot" aria-hidden="true"></i> Address</dt><dd><?=manage_e($property['address_line1'])?><br><?=manage_e($property['city'].', '.$property['state'].' '.$property['postal_code'])?></dd></div><div><dt><i class="fa-solid fa-phone" aria-hidden="true"></i> Phone</dt><dd><?=manage_e($property['phone'])?></dd></div><div><dt><i class="fa-solid fa-user-tie" aria-hidden="true"></i> GM Email</dt><dd><a href="mailto:<?=manage_e($property['gm_email'])?>"><?=manage_e($property['gm_email'])?></a></dd></div><div><dt><i class="fa-solid fa-envelope" aria-hidden="true"></i> Sales Email</dt><dd><a href="mailto:<?=manage_e($property['sales_email'])?>"><?=manage_e($property['sales_email'])?></a></dd></div></dl><div class="manage-property-card-flags"><span><i class="fa-solid fa-utensils" aria-hidden="true"></i> <?=$property['has_restaurant']?'Restaurant':'No Restaurant'?></span><span><i class="fa-solid fa-computer" aria-hidden="true"></i> PMS: <?=manage_e($pmsOptions[(string)($property['pms_system']??'hotel_key')]??'Hotel Key')?></span><span><i class="fa-solid fa-receipt" aria-hidden="true"></i> Suite Shop Tax: <?=manage_e(ucfirst((string)$property['suite_shop_tax_frequency']))?></span><span><i class="fa-solid fa-building-columns" aria-hidden="true"></i> <?=!empty($property['participates_bank_deposits'])?'Bank Deposits':'No Bank Deposits'?></span><?php if(trim((string)($property['bank_account_name']??''))!==''):?><span><i class="fa-solid fa-building-columns" aria-hidden="true"></i> <?=manage_e($property['bank_account_name'])?></span><?php endif;?></div></div></article><?php endforeach;?><?php if(!$properties):?><div class="manage-panel">No properties have been added. Select Add Property to create the first hotel.</div><?php endif;?></section>
<?php endif;?>
<?php require_once __DIR__.'/includes/footer.php';?>
