<?php
declare(strict_types=1);require_once __DIR__.'/includes/bootstrap.php';
function receipt_json(bool $ok,string $message,array $extra=[]): never {app_json_result($ok,$message,$extra);}
function receipt_transaction_summary(int $periodId): array {
 $q=db()->prepare("SELECT COALESCE(c.category_name,'UNCATEGORIZED') category_name,SUM(t.amount) total,COUNT(*) item_count,SUM(CASE WHEN t.receipt_found=0 THEN 1 ELSE 0 END) missing_receipt_count,SUM(CASE WHEN t.category_id IS NULL THEN 1 ELSE 0 END) incomplete_count FROM management_receipt_transactions t LEFT JOIN management_receipt_categories c ON c.id=t.category_id LEFT JOIN management_receipt_analysis_runs r ON r.id=t.analysis_run_id WHERE t.management_receipt_period_id=? AND (r.is_current=1 OR t.analysis_run_id IS NULL) GROUP BY COALESCE(c.category_name,'UNCATEGORIZED')");$q->execute([$periodId]);$categoryTotals=[];$uncategorizedCount=0;$missingReceiptCount=0;$incompleteCount=0;$transactionCount=0;$breakdownTotal=0.0;foreach($q->fetchAll() as $row){$categoryName=(string)$row['category_name'];$total=(float)$row['total'];$count=(int)$row['item_count'];$categoryTotals[$categoryName]=$total;$transactionCount+=$count;$breakdownTotal+=$total;$missingReceiptCount+=(int)$row['missing_receipt_count'];$incompleteCount+=(int)$row['incomplete_count'];if($categoryName==='UNCATEGORIZED')$uncategorizedCount=$count;}return ['category_totals'=>$categoryTotals,'uncategorized_count'=>$uncategorizedCount,'missing_receipt_count'=>$missingReceiptCount,'incomplete_count'=>$incompleteCount,'transaction_count'=>$transactionCount,'breakdown_total'=>$breakdownTotal];
}
function receipt_payment_summary(int $periodId): array {
 $transactionSummary=receipt_transaction_summary($periodId);$q=db()->prepare('SELECT COALESCE(SUM(amount_paid),0) FROM management_receipt_payments WHERE management_receipt_period_id=?');$q->execute([$periodId]);$paymentTotal=(float)$q->fetchColumn();
 return array_merge($transactionSummary,['payment_total'=>$paymentTotal,'payment_remaining'=>(float)$transactionSummary['breakdown_total']-$paymentTotal]);
}
function receipt_next_owner_number(int $periodId): int {
 $q=db()->prepare("SELECT COALESCE(MAX(owner_receipt_number),0)+1 FROM management_receipt_files WHERE management_receipt_period_id=? AND file_category='backup_invoices' AND receipt_group='owner'");$q->execute([$periodId]);return max(1,(int)$q->fetchColumn());
}
function receipt_gm_due_date(): DateTimeImmutable {
 $dueDate=new DateTimeImmutable('today',new DateTimeZone('America/Chicago'));$businessDays=0;while($businessDays<5){$dueDate=$dueDate->modify('+1 day');if((int)$dueDate->format('N')<=5)$businessDays++;}return $dueDate;
}
if($_SERVER['REQUEST_METHOD']!=='POST'||!hash_equals(csrf_token(),(string)($_POST['csrf_token']??'')))receipt_json(false,'Your session expired. Refresh and try again.');
$propertyId=(int)($_POST['property_id']??0);$year=(int)($_POST['report_year']??0);$month=(int)($_POST['report_month']??0);$category=(string)($_POST['category']??'');$receiptGroup=(string)($_POST['receipt_group']??'unassigned');$ownerReceiptGroups=['owner','owner_ach_check'];$validReceiptGroups=['manager',...$ownerReceiptGroups];$ownerMatchingReady=manage_owner_receipt_matching_ready();
if(!manage_receipts_schema_ready()||!manage_can_access_property($propertyId))receipt_json(false,'Property access denied.');if($year<2026||$year>2045||$month<1||$month>12||($year===2026&&$month<7))receipt_json(false,'Invalid receipt period.');if(!in_array($category,['statement','payment','backup_invoices'],true))receipt_json(false,'Invalid file category.');
try{
 if(($_POST['action']??'')==='reset_month'){
  if(!manage_is_admin())receipt_json(false,'Only a Super Admin may reset a receipt month.');$q=db()->prepare('SELECT id,status FROM management_receipt_periods WHERE management_property_id=? AND report_year=? AND report_month=?');$q->execute([$propertyId,$year,$month]);$receiptPeriod=$q->fetch();$periodId=(int)($receiptPeriod['id']??0);if($periodId<1){if(manage_cpa_delivery_schema_ready())db()->prepare('DELETE FROM management_cpa_deliveries WHERE management_property_id=? AND report_year=? AND report_month=?')->execute([$propertyId,$year,$month]);receipt_json(true,'Month reset.');}if((string)($receiptPeriod['status']??'')==='finalized')receipt_json(false,'A finalized receipt month cannot be reset.');$q=db()->prepare('SELECT file_path FROM management_receipt_files WHERE management_receipt_period_id=?');$q->execute([$periodId]);$filePaths=array_map('strval',$q->fetchAll(PDO::FETCH_COLUMN));db()->beginTransaction();if($ownerMatchingReady)db()->prepare('DELETE FROM management_receipt_card_settings WHERE management_receipt_period_id=?')->execute([$periodId]);if(manage_cpa_delivery_schema_ready())db()->prepare('DELETE FROM management_cpa_deliveries WHERE management_property_id=? AND report_year=? AND report_month=?')->execute([$propertyId,$year,$month]);db()->prepare('DELETE FROM management_receipt_transactions WHERE management_receipt_period_id=?')->execute([$periodId]);db()->prepare('DELETE FROM management_receipt_analysis_runs WHERE management_receipt_period_id=?')->execute([$periodId]);if(manage_receipt_payments_schema_ready())db()->prepare('DELETE FROM management_receipt_payments WHERE management_receipt_period_id=?')->execute([$periodId]);db()->prepare('DELETE FROM management_receipt_files WHERE management_receipt_period_id=?')->execute([$periodId]);db()->prepare('DELETE FROM management_receipt_periods WHERE id=?')->execute([$periodId]);db()->commit();foreach($filePaths as $filePath)try{znp_storage_delete($filePath);}catch(Throwable $cleanup){error_log('Receipt month reset file cleanup failed: '.$cleanup->getMessage());}receipt_json(true,'Receipt month reset.');
 }
 if(($_POST['action']??'')==='add_payment'){
  if(!manage_receipt_payments_schema_ready())receipt_json(false,'Run the Management Properties upgrade before adding payments.');
  $paymentDate=trim((string)($_POST['payment_date']??''));$bankAccount=mb_substr(trim((string)($_POST['bank_account_paid_from']??'')),0,190);$amount=(float)str_replace([',','$'],'',(string)($_POST['amount_paid']??'0'));
  $date=DateTimeImmutable::createFromFormat('!Y-m-d',$paymentDate);if(!$date||$date->format('Y-m-d')!==$paymentDate||$bankAccount===''||$amount<=0)receipt_json(false,'Enter a valid payment date, bank account, and amount greater than zero.');
  db()->beginTransaction();db()->prepare("INSERT INTO management_receipt_periods(management_property_id,report_year,report_month,status,updated_by_admin_user_id) VALUES(?,?,?,'submitted',?) ON DUPLICATE KEY UPDATE updated_by_admin_user_id=VALUES(updated_by_admin_user_id)")->execute([$propertyId,$year,$month,(int)($managementUser['id']??0)]);$q=db()->prepare('SELECT id FROM management_receipt_periods WHERE management_property_id=? AND report_year=? AND report_month=?');$q->execute([$propertyId,$year,$month]);$periodId=(int)$q->fetchColumn();db()->prepare('INSERT INTO management_receipt_payments(management_receipt_period_id,payment_date,bank_account_paid_from,amount_paid,created_by_admin_user_id) VALUES(?,?,?,?,?)')->execute([$periodId,$paymentDate,$bankAccount,$amount,(int)($managementUser['id']??0)]);db()->commit();receipt_json(true,'Payment saved.');
 }
 if(($_POST['action']??'')==='delete_payment'){
  if(!manage_receipt_payments_schema_ready())receipt_json(false,'Payment records are not installed.');$paymentId=(int)($_POST['payment_id']??0);$q=db()->prepare('SELECT rp.id FROM management_receipt_payments rp JOIN management_receipt_periods p ON p.id=rp.management_receipt_period_id WHERE rp.id=? AND p.management_property_id=? AND p.report_year=? AND p.report_month=?');$q->execute([$paymentId,$propertyId,$year,$month]);if(!$q->fetchColumn())receipt_json(false,'Payment not found.');db()->prepare('DELETE FROM management_receipt_payments WHERE id=?')->execute([$paymentId]);receipt_json(true,'Payment deleted.');
 }
 if(($_POST['action']??'')==='update_payment'){
  if(!manage_is_admin())receipt_json(false,'Only a Super Admin may edit payment records.');if(!manage_receipt_payments_schema_ready())receipt_json(false,'Payment records are not installed.');
  $paymentId=(int)($_POST['payment_id']??0);$paymentDate=trim((string)($_POST['payment_date']??''));$bankAccount=mb_substr(trim((string)($_POST['bank_account_paid_from']??'')),0,190);$amountRaw=str_replace([',','$',' '],'',(string)($_POST['amount_paid']??''));$date=DateTimeImmutable::createFromFormat('!Y-m-d',$paymentDate);
  if(!$date||$date->format('Y-m-d')!==$paymentDate||$bankAccount===''||!is_numeric($amountRaw)||(float)$amountRaw<=0)receipt_json(false,'Enter a valid payment date, bank account, and amount greater than zero.');
  $q=db()->prepare('SELECT rp.management_receipt_period_id FROM management_receipt_payments rp JOIN management_receipt_periods p ON p.id=rp.management_receipt_period_id WHERE rp.id=? AND p.management_property_id=? AND p.report_year=? AND p.report_month=?');$q->execute([$paymentId,$propertyId,$year,$month]);$periodId=(int)$q->fetchColumn();if($periodId<1)receipt_json(false,'Payment not found.');
  $amount=round((float)$amountRaw,2);db()->prepare('UPDATE management_receipt_payments SET payment_date=?,bank_account_paid_from=?,amount_paid=? WHERE id=?')->execute([$paymentDate,$bankAccount,number_format($amount,2,'.',''),$paymentId]);receipt_json(true,'Payment updated.',array_merge(['payment'=>['id'=>$paymentId,'payment_date'=>$paymentDate,'payment_date_label'=>$date->format('M j, Y'),'bank_account_paid_from'=>$bankAccount,'amount_paid'=>$amount]],receipt_payment_summary($periodId)));
 }
 if(($_POST['action']??'')==='upload'){
  if(in_array($category,['statement','payment'],true)&&!manage_is_admin())receipt_json(false,'Only a Super Admin may upload statements and payments.');
  if($category==='backup_invoices'&&!in_array($receiptGroup,$validReceiptGroups,true))receipt_json(false,'Choose Manager Receipts, Owner Receipts, or Owner ACH/CHECK.');
  if($category==='backup_invoices'&&in_array($receiptGroup,$ownerReceiptGroups,true)&&!manage_is_admin())receipt_json(false,'Only a Super Admin may access Owner Receipts.');
  if($category!=='backup_invoices')$receiptGroup='unassigned';
  $uploads=manage_store_receipt_files($_FILES['files']??[],$propertyId,$year,$month,$category);if(!$uploads)receipt_json(false,'Choose at least one file.');
  $extracted=[];$parseFailed=false;if($category==='statement')foreach($uploads as $index=>$file){try{$extracted[$index]=manage_extract_statement_transactions((string)$file['data'],$year,$month);}catch(Throwable $parseError){$parseFailed=true;$extracted[$index]=[];error_log('Statement PDF extraction failed: '.$parseError->getMessage());}}
  try{db()->beginTransaction();db()->prepare("INSERT INTO management_receipt_periods(management_property_id,report_year,report_month,status,updated_by_admin_user_id) VALUES(?,?,?,'submitted',?) ON DUPLICATE KEY UPDATE status='submitted',updated_by_admin_user_id=VALUES(updated_by_admin_user_id)")->execute([$propertyId,$year,$month,(int)($managementUser['id']??0)]);$q=db()->prepare('SELECT id FROM management_receipt_periods WHERE management_property_id=? AND report_year=? AND report_month=?');$q->execute([$propertyId,$year,$month]);$periodId=(int)$q->fetchColumn();$insert=db()->prepare($ownerMatchingReady?'INSERT INTO management_receipt_files(management_receipt_period_id,file_category,receipt_group,file_path,original_name,mime_type,file_size,owner_receipt_number) VALUES(?,?,?,?,?,?,?,?)':'INSERT INTO management_receipt_files(management_receipt_period_id,file_category,receipt_group,file_path,original_name,mime_type,file_size) VALUES(?,?,?,?,?,?,?)');$insertTransaction=db()->prepare('INSERT INTO management_receipt_transactions(management_receipt_period_id,statement_file_id,transaction_date,cardholder,card_last_four,transaction_type,analysis_run_id,description,amount,source_line) VALUES(?,?,?,?,?,?,?,?,?,?)');$items=[];$transactionCount=0;foreach($uploads as $index=>$file){$ownerReceiptNumber=$ownerMatchingReady&&$category==='backup_invoices'&&$receiptGroup==='owner'?receipt_next_owner_number($periodId):null;$fileArguments=[$periodId,$category,$receiptGroup,$file['path'],$file['name'],$file['mime'],$file['size']];if($ownerMatchingReady)$fileArguments[]=$ownerReceiptNumber;$insert->execute($fileArguments);$id=(int)db()->lastInsertId();$items[]=['id'=>$id,'name'=>$file['name'],'url'=>'receipt_file.php?id='.$id,'receipt_group'=>$receiptGroup,'owner_receipt_number'=>$ownerReceiptNumber];$runId=null;if($category==='statement'&&isset($extracted[$index])){$total=array_sum(array_column($extracted[$index],'amount'));db()->prepare('INSERT INTO management_receipt_analysis_runs(management_receipt_period_id,statement_file_id,is_current,analyzed_by_admin_user_id,transaction_count,total_amount) VALUES(?,?,1,?,?,?)')->execute([$periodId,$id,(int)($managementUser['id']??0),count($extracted[$index]),$total]);$runId=(int)db()->lastInsertId();}foreach($extracted[$index]??[] as $transaction){$insertTransaction->execute([$periodId,$id,$transaction['date'],$transaction['cardholder'],$transaction['last_four'],$transaction['type'],$runId,$transaction['description'],$transaction['amount'],$transaction['source_line']]);$transactionCount++;}}db()->commit();
   $message=count($items)===1?'File uploaded.':'Files uploaded.';
   if($category==='statement'){if($parseFailed||$transactionCount===0)$message.=' No charge rows could be extracted automatically; the statement remains available for review.';else $message.=' '.$transactionCount.' charge'.($transactionCount===1?' was':'s were').' added to the breakdown.';try{$property=manage_property($propertyId);$monthName=DateTimeImmutable::createFromFormat('!m',(string)$month)->format('F');$subject='Credit Card Statement - '.$monthName.', '.$year.' - DUE '.receipt_gm_due_date()->format('F j, Y');$body='<p>Please access portal at <a href="https://ZNPDEV.com">ZNPDEV.com</a> to upload your receipts and categorize the statement.</p>';$mail=app_send_mail_detailed((string)($property['gm_email']??''),$subject,$body,[]);if(!$mail['ok']){error_log('Receipt statement GM notification failed: '.$mail['error']);$message.=' The GM notification email could not be sent.';}else $message.=' The property GM was notified.';}catch(Throwable $mailError){error_log('Receipt statement GM notification failed: '.$mailError->getMessage());$message.=' The GM notification email could not be sent.';}}
   receipt_json(true,$message,['files'=>$items,'period_status'=>'submitted','transaction_count'=>$transactionCount]);}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();foreach($uploads as $file)try{znp_storage_delete((string)$file['path']);}catch(Throwable $cleanup){}throw $e;}
 }
 if(($_POST['action']??'')==='analyze_statement'){
  if(!manage_is_admin())receipt_json(false,'Only a Super Admin may analyze statements.');$id=(int)($_POST['file_id']??0);
  $q=db()->prepare("SELECT f.*,p.management_property_id,p.report_year,p.report_month FROM management_receipt_files f JOIN management_receipt_periods p ON p.id=f.management_receipt_period_id WHERE f.id=? AND f.file_category='statement'");$q->execute([$id]);$file=$q->fetch();if(!$file||(int)$file['management_property_id']!==$propertyId)receipt_json(false,'Statement not found.');
  $transactions=manage_extract_statement_transactions(znp_storage_contents((string)$file['file_path']),(int)$file['report_year'],(int)$file['report_month']);
  db()->beginTransaction();db()->prepare('DELETE FROM management_receipt_transactions WHERE statement_file_id=?')->execute([$id]);db()->prepare('DELETE FROM management_receipt_analysis_runs WHERE statement_file_id=?')->execute([$id]);$total=array_sum(array_column($transactions,'amount'));db()->prepare('INSERT INTO management_receipt_analysis_runs(management_receipt_period_id,statement_file_id,is_current,analyzed_by_admin_user_id,transaction_count,total_amount) VALUES(?,?,1,?,?,?)')->execute([(int)$file['management_receipt_period_id'],$id,(int)($managementUser['id']??0),count($transactions),$total]);$runId=(int)db()->lastInsertId();$insert=db()->prepare('INSERT INTO management_receipt_transactions(management_receipt_period_id,statement_file_id,transaction_date,cardholder,card_last_four,transaction_type,analysis_run_id,description,amount,source_line) VALUES(?,?,?,?,?,?,?,?,?,?)');foreach($transactions as $transaction)$insert->execute([(int)$file['management_receipt_period_id'],$id,$transaction['date'],$transaction['cardholder'],$transaction['last_four'],$transaction['type'],$runId,$transaction['description'],$transaction['amount'],$transaction['source_line']]);db()->commit();receipt_json(true,count($transactions).' line item'.(count($transactions)===1?' was':'s were').' saved. The previous analysis was replaced.',['transaction_count'=>count($transactions)]);
 }
 if(($_POST['action']??'')==='add_transaction'){
  if(!manage_is_admin())receipt_json(false,'Only a Super Admin may add manual line items.');
  $templateId=(int)($_POST['template_transaction_id']??0);$transactionDate=trim((string)($_POST['transaction_date']??''));$transactionType=(string)($_POST['transaction_type']??'charge');$description=mb_substr(trim((string)($_POST['description']??'')),0,500);$amountRaw=str_replace([',','$',' '],'',(string)($_POST['amount']??''));$categoryId=(int)($_POST['category_id']??0);$receiptFound=(int)($_POST['receipt_found']??0)===1?1:0;$notes=mb_substr(trim((string)($_POST['notes']??'')),0,5000);
  $date=DateTimeImmutable::createFromFormat('!Y-m-d',$transactionDate);if(!$date||$date->format('Y-m-d')!==$transactionDate||(int)$date->format('Y')!==$year||(int)$date->format('n')!==$month)receipt_json(false,'Choose a valid date within the selected receipt month.');if(!in_array($transactionType,['charge','credit','payment'],true)||$description===''||!is_numeric($amountRaw)||(float)$amountRaw==0.0)receipt_json(false,'Enter a type, description, and amount greater than zero.');if($categoryId>0){$q=db()->prepare('SELECT 1 FROM management_receipt_categories WHERE id=? AND is_active=1');$q->execute([$categoryId]);if(!$q->fetchColumn())receipt_json(false,'Invalid category.');}
  $q=db()->prepare('SELECT t.management_receipt_period_id,t.statement_file_id,t.cardholder,t.card_last_four,p.management_property_id,p.report_year,p.report_month FROM management_receipt_transactions t JOIN management_receipt_periods p ON p.id=t.management_receipt_period_id LEFT JOIN management_receipt_analysis_runs r ON r.id=t.analysis_run_id WHERE t.id=? AND (r.is_current=1 OR t.analysis_run_id IS NULL)');$q->execute([$templateId]);$template=$q->fetch();if(!$template||(int)$template['management_property_id']!==$propertyId||(int)$template['report_year']!==$year||(int)$template['report_month']!==$month)receipt_json(false,'The selected card could not be found. Refresh and try again.');
  $amount=abs((float)$amountRaw);if($transactionType!=='charge')$amount=-$amount;db()->prepare('INSERT INTO management_receipt_transactions(management_receipt_period_id,statement_file_id,transaction_date,cardholder,card_last_four,transaction_type,analysis_run_id,description,amount,source_line,category_id,receipt_found,notes) VALUES(?,?,?,?,?,?,NULL,?,?,?,?,?,?)')->execute([(int)$template['management_receipt_period_id'],(int)$template['statement_file_id'],$transactionDate,(string)$template['cardholder'],(string)$template['card_last_four'],$transactionType,$description,number_format($amount,2,'.',''),'Manual entry',$categoryId?:null,$receiptFound,$notes]);receipt_json(true,'Manual line item added.',receipt_transaction_summary((int)$template['management_receipt_period_id']));
 }
 if(($_POST['action']??'')==='toggle_owner_card'){
  if(!manage_is_admin())receipt_json(false,'Only a Super Admin may identify Owner sections.');if(!$ownerMatchingReady)receipt_json(false,'Run the Receipt Tracking upgrade before identifying Owner sections.');$cardKey=mb_substr(trim((string)($_POST['card_key']??'')),0,190);$isOwner=(int)($_POST['is_owner']??0)===1?1:0;if($cardKey==='')receipt_json(false,'The card section could not be identified.');$q=db()->prepare("SELECT t.management_receipt_period_id FROM management_receipt_transactions t JOIN management_receipt_periods p ON p.id=t.management_receipt_period_id LEFT JOIN management_receipt_analysis_runs r ON r.id=t.analysis_run_id WHERE p.management_property_id=? AND p.report_year=? AND p.report_month=? AND (CASE WHEN TRIM(COALESCE(t.card_last_four,''))='' THEN 'unknown' ELSE TRIM(t.card_last_four) END)=? AND (r.is_current=1 OR t.analysis_run_id IS NULL) LIMIT 1");$q->execute([$propertyId,$year,$month,$cardKey]);$periodId=(int)$q->fetchColumn();if($periodId<1)receipt_json(false,'The card section could not be found.');db()->beginTransaction();db()->prepare('INSERT INTO management_receipt_card_settings(management_receipt_period_id,card_key,is_owner,updated_by_admin_user_id) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE is_owner=VALUES(is_owner),updated_by_admin_user_id=VALUES(updated_by_admin_user_id)')->execute([$periodId,$cardKey,$isOwner,(int)($managementUser['id']??0)]);if($isOwner)db()->prepare("UPDATE management_receipt_transactions SET receipt_found=CASE WHEN owner_receipt_file_id IS NULL THEN 0 ELSE 1 END WHERE management_receipt_period_id=? AND (CASE WHEN TRIM(COALESCE(card_last_four,''))='' THEN 'unknown' ELSE TRIM(card_last_four) END)=?")->execute([$periodId,$cardKey]);else db()->prepare("UPDATE management_receipt_transactions SET owner_receipt_file_id=NULL,receipt_found=0 WHERE management_receipt_period_id=? AND (CASE WHEN TRIM(COALESCE(card_last_four,''))='' THEN 'unknown' ELSE TRIM(card_last_four) END)=?")->execute([$periodId,$cardKey]);db()->commit();receipt_json(true,$isOwner?'Card marked as an Owner section.':'Owner section removed.',array_merge(['is_owner'=>$isOwner],receipt_transaction_summary($periodId)));
 }
 if(($_POST['action']??'')==='assign_owner_receipt'){
  if(!manage_is_admin())receipt_json(false,'Only a Super Admin may match Owner Receipts.');if(!$ownerMatchingReady)receipt_json(false,'Run the Receipt Tracking upgrade before matching Owner Receipts.');$transactionId=(int)($_POST['transaction_id']??0);$ownerFileId=(int)($_POST['owner_receipt_file_id']??0);$q=db()->prepare("SELECT t.management_receipt_period_id,CASE WHEN TRIM(COALESCE(t.card_last_four,''))='' THEN 'unknown' ELSE TRIM(t.card_last_four) END card_key,p.management_property_id,p.report_year,p.report_month FROM management_receipt_transactions t JOIN management_receipt_periods p ON p.id=t.management_receipt_period_id LEFT JOIN management_receipt_analysis_runs r ON r.id=t.analysis_run_id WHERE t.id=? AND (r.is_current=1 OR t.analysis_run_id IS NULL)");$q->execute([$transactionId]);$transaction=$q->fetch();if(!$transaction||(int)$transaction['management_property_id']!==$propertyId||(int)$transaction['report_year']!==$year||(int)$transaction['report_month']!==$month)receipt_json(false,'Line item not found.');$q=db()->prepare('SELECT is_owner FROM management_receipt_card_settings WHERE management_receipt_period_id=? AND card_key=?');$q->execute([(int)$transaction['management_receipt_period_id'],(string)$transaction['card_key']]);if((int)$q->fetchColumn()!==1)receipt_json(false,'Mark this card as an Owner section first.');if($ownerFileId>0){$q=db()->prepare("SELECT owner_receipt_number FROM management_receipt_files WHERE id=? AND management_receipt_period_id=? AND file_category='backup_invoices' AND receipt_group='owner'");$q->execute([$ownerFileId,(int)$transaction['management_receipt_period_id']]);$receiptNumber=(int)$q->fetchColumn();if($receiptNumber<1)receipt_json(false,'Owner Receipt not found.');$q=db()->prepare('SELECT id FROM management_receipt_transactions WHERE owner_receipt_file_id=? AND id<>?');$q->execute([$ownerFileId,$transactionId]);if($q->fetchColumn())receipt_json(false,'That Owner Receipt is already assigned to another row.');}else $receiptNumber=0;db()->prepare('UPDATE management_receipt_transactions SET owner_receipt_file_id=?,receipt_found=? WHERE id=?')->execute([$ownerFileId?:null,$ownerFileId>0?1:0,$transactionId]);receipt_json(true,$ownerFileId>0?'Owner Receipt #'.$receiptNumber.' assigned.':'Owner Receipt assignment removed.',array_merge(['owner_receipt_file_id'=>$ownerFileId,'owner_receipt_number'=>$receiptNumber],receipt_transaction_summary((int)$transaction['management_receipt_period_id'])));
 }
 if(($_POST['action']??'')==='save_transaction'){
  $transactionId=(int)($_POST['transaction_id']??0);$notes=mb_substr(trim((string)($_POST['notes']??'')),0,5000);$categoryId=(int)($_POST['category_id']??0);$receiptFound=(int)($_POST['receipt_found']??0)===1?1:0;$ownerReceiptSelect=$ownerMatchingReady?'t.owner_receipt_file_id':'NULL owner_receipt_file_id';$q=db()->prepare("SELECT t.id,t.management_receipt_period_id,{$ownerReceiptSelect},CASE WHEN TRIM(COALESCE(t.card_last_four,''))='' THEN 'unknown' ELSE TRIM(t.card_last_four) END card_key,p.management_property_id,p.report_year,p.report_month FROM management_receipt_transactions t JOIN management_receipt_periods p ON p.id=t.management_receipt_period_id WHERE t.id=?");$q->execute([$transactionId]);$transaction=$q->fetch();if(!$transaction||(int)$transaction['management_property_id']!==$propertyId||(int)$transaction['report_year']!==$year||(int)$transaction['report_month']!==$month)receipt_json(false,'Line item not found.');if(!manage_is_admin()&&manage_receipt_period_sent_to_cpa((int)$transaction['management_property_id'],(int)$transaction['report_year'],(int)$transaction['report_month']))receipt_json(false,'This receipt breakdown was sent to the CPA and is locked. Only a Super Admin may change it.');if($ownerMatchingReady){$q=db()->prepare('SELECT is_owner FROM management_receipt_card_settings WHERE management_receipt_period_id=? AND card_key=?');$q->execute([(int)$transaction['management_receipt_period_id'],(string)$transaction['card_key']]);$transactionIsOwner=(int)$q->fetchColumn()===1;if($transactionIsOwner&&!manage_is_admin())receipt_json(false,'Owner sections are locked for managers.');if($transactionIsOwner)$receiptFound=(int)($transaction['owner_receipt_file_id']??0)>0?1:0;}if($categoryId>0){$q=db()->prepare('SELECT 1 FROM management_receipt_categories WHERE id=? AND is_active=1');$q->execute([$categoryId]);if(!$q->fetchColumn())receipt_json(false,'Invalid category.');}db()->prepare('UPDATE management_receipt_transactions SET category_id=?,receipt_found=?,notes=? WHERE id=?')->execute([$categoryId?:null,$receiptFound,$notes,$transactionId]);receipt_json(true,'Line item saved.',receipt_transaction_summary((int)$transaction['management_receipt_period_id']));
 }
 if(($_POST['action']??'')==='delete_transaction'){
  if(!manage_is_admin())receipt_json(false,'Only a Super Admin may remove analyzed line items.');$transactionId=(int)($_POST['transaction_id']??0);$q=db()->prepare('SELECT t.id,t.analysis_run_id,t.management_receipt_period_id,p.management_property_id,p.report_year,p.report_month FROM management_receipt_transactions t JOIN management_receipt_periods p ON p.id=t.management_receipt_period_id WHERE t.id=?');$q->execute([$transactionId]);$transaction=$q->fetch();if(!$transaction||(int)$transaction['management_property_id']!==$propertyId||(int)$transaction['report_year']!==$year||(int)$transaction['report_month']!==$month)receipt_json(false,'Line item not found.');db()->beginTransaction();db()->prepare('DELETE FROM management_receipt_transactions WHERE id=?')->execute([$transactionId]);if((int)($transaction['analysis_run_id']??0)>0){$q=db()->prepare('SELECT COUNT(*),COALESCE(SUM(amount),0) FROM management_receipt_transactions WHERE analysis_run_id=?');$q->execute([(int)$transaction['analysis_run_id']]);[$count,$total]=$q->fetch(PDO::FETCH_NUM);db()->prepare('UPDATE management_receipt_analysis_runs SET transaction_count=?,total_amount=? WHERE id=?')->execute([(int)$count,(float)$total,(int)$transaction['analysis_run_id']]);}$summary=receipt_transaction_summary((int)$transaction['management_receipt_period_id']);db()->commit();receipt_json(true,'Line item removed.',$summary);
 }
 if(($_POST['action']??'')==='save_file_comment'){
  if(!manage_is_admin())receipt_json(false,'Only a Super Admin may edit Owner Receipt comments.');
  if(!manage_receipt_file_comments_ready())receipt_json(false,'Run the Receipt Tracking upgrade before adding comments.');
  $id=(int)($_POST['file_id']??0);$comment=mb_substr(trim((string)($_POST['file_comment']??'')),0,500);
  $q=db()->prepare("SELECT f.id,f.receipt_group,p.management_property_id,p.report_year,p.report_month FROM management_receipt_files f JOIN management_receipt_periods p ON p.id=f.management_receipt_period_id WHERE f.id=? AND f.file_category='backup_invoices'");$q->execute([$id]);$file=$q->fetch();
  if(!$file||(int)$file['management_property_id']!==$propertyId||(int)$file['report_year']!==$year||(int)$file['report_month']!==$month||!in_array((string)$file['receipt_group'],$ownerReceiptGroups,true))receipt_json(false,'Owner Receipt file not found.');
  db()->prepare('UPDATE management_receipt_files SET file_comment=? WHERE id=?')->execute([$comment,$id]);receipt_json(true,'Comment saved.',['file_comment'=>$comment]);
 }
 if(($_POST['action']??'')==='categorize_file'){
  if($category!=='backup_invoices'||!in_array($receiptGroup,$validReceiptGroups,true))receipt_json(false,'Invalid receipt category.');
  $id=(int)($_POST['file_id']??0);$q=db()->prepare('SELECT f.*,p.management_property_id FROM management_receipt_files f JOIN management_receipt_periods p ON p.id=f.management_receipt_period_id WHERE f.id=? AND f.file_category=?');$q->execute([$id,'backup_invoices']);$file=$q->fetch();if(!$file||(int)$file['management_property_id']!==$propertyId)receipt_json(false,'File not found.');if(!manage_is_admin()&&(in_array($receiptGroup,$ownerReceiptGroups,true)||in_array((string)$file['receipt_group'],$ownerReceiptGroups,true)))receipt_json(false,'Only a Super Admin may access Owner Receipts.');$ownerReceiptNumber=null;db()->beginTransaction();if($ownerMatchingReady&&$receiptGroup==='owner'){$ownerReceiptNumber=(int)($file['owner_receipt_number']??0);if($ownerReceiptNumber<1)$ownerReceiptNumber=receipt_next_owner_number((int)$file['management_receipt_period_id']);db()->prepare('UPDATE management_receipt_files SET receipt_group=?,owner_receipt_number=? WHERE id=?')->execute([$receiptGroup,$ownerReceiptNumber,$id]);}elseif($ownerMatchingReady){db()->prepare('UPDATE management_receipt_transactions SET owner_receipt_file_id=NULL,receipt_found=0 WHERE owner_receipt_file_id=?')->execute([$id]);db()->prepare('UPDATE management_receipt_files SET receipt_group=?,owner_receipt_number=NULL WHERE id=?')->execute([$receiptGroup,$id]);}else db()->prepare('UPDATE management_receipt_files SET receipt_group=? WHERE id=?')->execute([$receiptGroup,$id]);db()->commit();receipt_json(true,'Receipt categorized.',['receipt_group'=>$receiptGroup,'file_comment'=>(string)($file['file_comment']??''),'owner_receipt_number'=>$ownerReceiptNumber]);
 }
 if(($_POST['action']??'')==='delete_file'){
  if(in_array($category,['statement','payment'],true)&&!manage_is_admin())receipt_json(false,'Only a Super Admin may delete statements and payments.');
  $id=(int)($_POST['file_id']??0);$q=db()->prepare('SELECT f.*,p.management_property_id FROM management_receipt_files f JOIN management_receipt_periods p ON p.id=f.management_receipt_period_id WHERE f.id=?');$q->execute([$id]);$file=$q->fetch();if(!$file||(int)$file['management_property_id']!==$propertyId||(string)$file['file_category']!==$category)receipt_json(false,'File not found.');if(in_array((string)($file['receipt_group']??''),$ownerReceiptGroups,true)&&!manage_is_admin())receipt_json(false,'Only a Super Admin may access Owner Receipts.');znp_storage_delete((string)$file['file_path']);if($ownerMatchingReady)db()->prepare('UPDATE management_receipt_transactions SET owner_receipt_file_id=NULL,receipt_found=0 WHERE owner_receipt_file_id=?')->execute([$id]);db()->prepare('DELETE FROM management_receipt_transactions WHERE statement_file_id=?')->execute([$id]);db()->prepare('DELETE FROM management_receipt_analysis_runs WHERE statement_file_id=?')->execute([$id]);db()->prepare('DELETE FROM management_receipt_files WHERE id=?')->execute([$id]);$q=db()->prepare('SELECT COUNT(*) FROM management_receipt_files WHERE management_receipt_period_id=?');$q->execute([(int)$file['management_receipt_period_id']]);$status=(int)$q->fetchColumn()>0?'submitted':'blank';if($status==='blank'){if($ownerMatchingReady)db()->prepare('DELETE FROM management_receipt_card_settings WHERE management_receipt_period_id=?')->execute([(int)$file['management_receipt_period_id']]);db()->prepare('DELETE FROM management_receipt_periods WHERE id=?')->execute([(int)$file['management_receipt_period_id']]);}receipt_json(true,'File deleted.',['period_status'=>$status]);
 }
 receipt_json(false,'Invalid action.');
}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();error_log('Receipt upload failed: '.$e->getMessage());receipt_json(false,'The receipt file change could not be saved.');}
