<?php
require_once __DIR__.'/includes/bootstrap.php';manage_require_admin();$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){if(!hash_equals(csrf_token(),(string)($_POST['csrf_token']??'')))$error='Your session expired.';else try{$action=(string)($_POST['action']??'');if($action==='save_cpa'){$cpaName=trim((string)($_POST['cpa_name']??''));$cpaEmail=strtolower(trim((string)($_POST['cpa_email']??'')));if($cpaEmail!==''&&!filter_var($cpaEmail,FILTER_VALIDATE_EMAIL))throw new RuntimeException('Enter a valid CPA email address.');setting_save('management_cpa_name',$cpaName);setting_save('management_cpa_email',$cpaEmail);$message='CPA settings saved.';}elseif($action==='add'){$name=strtoupper(trim((string)($_POST['category_name']??'')));if($name==='')throw new RuntimeException('Enter a category name.');db()->prepare('INSERT INTO management_receipt_categories(category_name,is_active) VALUES(?,1) ON DUPLICATE KEY UPDATE is_active=1')->execute([$name]);$message='Category saved.';}elseif($action==='delete'){$id=(int)($_POST['category_id']??0);db()->beginTransaction();db()->prepare('UPDATE management_receipt_transactions SET category_id=NULL WHERE category_id=?')->execute([$id]);db()->prepare('DELETE FROM management_receipt_categories WHERE id=?')->execute([$id]);db()->commit();$message='Category deleted.';}}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();$error=$e->getMessage();}}
$categories=manage_receipts_schema_ready()?db()->query('SELECT * FROM management_receipt_categories WHERE is_active=1 ORDER BY category_name')->fetchAll():[];require_once __DIR__.'/includes/header.php';
?>
<section class="manage-page-heading"><h1>Management Settings</h1><p>Manage properties, users, and global receipt categories.</p></section><?php require __DIR__.'/includes/settings_tabs.php';?><?php if($message):?><div class="manage-alert success"><?=manage_e($message)?></div><?php endif;?><?php if($error):?><div class="manage-alert error"><?=manage_e($error)?></div><?php endif;?>
<section class="manage-panel manage-global-cpa-settings"><div><h2>CPA</h2><p>Set the global CPA contact for future report submissions. Changes save automatically.</p></div><form class="manage-form-grid" data-cpa-autosave data-endpoint="settings_autosave.php"><input type="hidden" name="csrf_token" value="<?=manage_e(csrf_token())?>"><label>CPA Name<input name="cpa_name" maxlength="150" value="<?=manage_e(setting('management_cpa_name'))?>" placeholder="CPA or firm name"></label><label>CPA Email<input type="email" name="cpa_email" maxlength="190" value="<?=manage_e(setting('management_cpa_email'))?>" placeholder="cpa@example.com"></label></form></section>
<section class="manage-panel manage-category-settings"><h2>Receipt Categories</h2><form method="post" class="manage-category-add"><input type="hidden" name="csrf_token" value="<?=manage_e(csrf_token())?>"><input type="hidden" name="action" value="add"><label>New Category<input name="category_name" maxlength="100" required></label><button class="manage-button primary">Add Category</button></form><div class="manage-category-list"><?php foreach($categories as $category):?><div><strong><?=manage_e($category['category_name'])?></strong><form method="post" onsubmit="return confirm('Delete this category? Existing line items will become uncategorized.');"><input type="hidden" name="csrf_token" value="<?=manage_e(csrf_token())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="category_id" value="<?=(int)$category['id']?>"><button class="manage-file-delete" aria-label="Delete <?=manage_e($category['category_name'])?>"><i class="fa-solid fa-trash"></i></button></form></div><?php endforeach;?></div></section>
<script src="assets/settings-autosave.js?v=<?=manage_e(znp_asset_version())?>-1" defer></script><?php require_once __DIR__.'/includes/footer.php';?>
