<?php
declare(strict_types=1);
function dev_ensure_contract_schema(): void
{
    db()->exec("CREATE TABLE IF NOT EXISTS construction_contracts (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,construction_project_id BIGINT UNSIGNED NOT NULL,construction_project_company_id BIGINT UNSIGNED NOT NULL,construction_budget_item_id BIGINT UNSIGNED NULL,original_contract_amount DECIMAL(16,2) NOT NULL DEFAULT 0.00,notes TEXT NULL,created_by_admin_user_id BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_contracts_project(construction_project_id,id),KEY idx_contracts_assignment(construction_project_id,construction_project_company_id),KEY idx_contracts_budget_item(construction_budget_item_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    if(db()->query("SHOW COLUMNS FROM construction_contracts LIKE 'trade_type'")->fetchColumn())db()->exec("ALTER TABLE construction_contracts DROP COLUMN trade_type");
    if(db()->query("SHOW COLUMNS FROM construction_contracts LIKE 'is_verified'")->fetchColumn())db()->exec("ALTER TABLE construction_contracts DROP COLUMN is_verified");
    if(db()->query("SHOW INDEX FROM construction_contracts WHERE Key_name='uq_project_contract_assignment'")->fetchColumn())db()->exec("ALTER TABLE construction_contracts DROP INDEX uq_project_contract_assignment");
    if(!db()->query("SHOW INDEX FROM construction_contracts WHERE Key_name='idx_contracts_assignment'")->fetchColumn())db()->exec("ALTER TABLE construction_contracts ADD KEY idx_contracts_assignment(construction_project_id,construction_project_company_id)");
    if(!db()->query("SHOW COLUMNS FROM construction_contracts LIKE 'notes'")->fetchColumn())db()->exec("ALTER TABLE construction_contracts ADD COLUMN notes TEXT NULL AFTER original_contract_amount");
    if(!db()->query("SHOW COLUMNS FROM construction_contracts LIKE 'construction_budget_item_id'")->fetchColumn())db()->exec("ALTER TABLE construction_contracts ADD COLUMN construction_budget_item_id BIGINT UNSIGNED NULL AFTER construction_project_company_id, ADD KEY idx_contracts_budget_item(construction_budget_item_id)");
    if(!db()->query("SHOW INDEX FROM construction_contracts WHERE Key_name='idx_contracts_budget_item'")->fetchColumn())db()->exec("ALTER TABLE construction_contracts ADD KEY idx_contracts_budget_item(construction_budget_item_id)");
    db()->exec("CREATE TABLE IF NOT EXISTS construction_contract_payments (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,construction_contract_id BIGINT UNSIGNED NOT NULL,construction_project_expense_id BIGINT UNSIGNED NULL,app_number VARCHAR(50) NOT NULL DEFAULT '',amount_requested DECIMAL(16,2) NOT NULL DEFAULT 0.00,retainage DECIMAL(16,2) NOT NULL DEFAULT 0.00,amount_paid DECIMAL(16,2) NOT NULL DEFAULT 0.00,payment_method VARCHAR(190) NOT NULL DEFAULT '',entry_date DATE NOT NULL,created_by_admin_user_id BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_contract_payments_contract(construction_contract_id,entry_date,id),KEY idx_contract_payment_expense(construction_project_expense_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    if(!db()->query("SHOW COLUMNS FROM construction_contract_payments LIKE 'construction_project_expense_id'")->fetchColumn())db()->exec("ALTER TABLE construction_contract_payments ADD COLUMN construction_project_expense_id BIGINT UNSIGNED NULL AFTER construction_contract_id, ADD KEY idx_contract_payment_expense(construction_project_expense_id)");
    if(!db()->query("SHOW INDEX FROM construction_contract_payments WHERE Key_name='idx_contract_payment_expense'")->fetchColumn())db()->exec("ALTER TABLE construction_contract_payments ADD KEY idx_contract_payment_expense(construction_project_expense_id)");
    db()->exec("CREATE TABLE IF NOT EXISTS construction_contract_change_orders (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,construction_contract_id BIGINT UNSIGNED NOT NULL,change_order_number VARCHAR(50) NOT NULL DEFAULT '',description VARCHAR(500) NOT NULL DEFAULT '',amount DECIMAL(16,2) NOT NULL DEFAULT 0.00,change_order_date DATE NOT NULL,created_by_admin_user_id BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_contract_change_orders_contract(construction_contract_id,change_order_date,id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    db()->exec("CREATE TABLE IF NOT EXISTS construction_contract_documents (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,construction_contract_id BIGINT UNSIGNED NOT NULL,document_type ENUM('signed_agreement','insurance_certificate') NOT NULL,file_path VARCHAR(500) NOT NULL,original_name VARCHAR(255) NOT NULL,mime_type VARCHAR(150) NOT NULL DEFAULT 'application/octet-stream',file_size BIGINT UNSIGNED NOT NULL DEFAULT 0,expiration_date DATE NULL,created_by_admin_user_id BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_contract_documents_contract(construction_contract_id,document_type,expiration_date,id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    db()->exec("CREATE TABLE IF NOT EXISTS construction_contract_templates (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,construction_project_id BIGINT UNSIGNED NOT NULL,template_name VARCHAR(190) NOT NULL DEFAULT 'Subcontractor Agreement',body_html MEDIUMTEXT NOT NULL,created_by_admin_user_id BIGINT UNSIGNED NULL,updated_by_admin_user_id BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_contract_template_project(construction_project_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    db()->exec("CREATE TABLE IF NOT EXISTS construction_contract_envelopes (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,construction_project_id BIGINT UNSIGNED NOT NULL,construction_contract_id BIGINT UNSIGNED NOT NULL,construction_contract_template_id BIGINT UNSIGNED NOT NULL,access_token CHAR(64) NOT NULL,owner_access_token CHAR(64) NULL,owner_name VARCHAR(190) NOT NULL DEFAULT '',owner_email VARCHAR(190) NOT NULL DEFAULT '',owner_signed_at DATETIME NULL,owner_signature_text VARCHAR(255) NOT NULL DEFAULT '',owner_signature_data MEDIUMTEXT NULL,owner_signer_ip VARCHAR(64) NOT NULL DEFAULT '',owner_signer_user_agent VARCHAR(500) NOT NULL DEFAULT '',recipient_name VARCHAR(190) NOT NULL DEFAULT '',recipient_email VARCHAR(190) NOT NULL,subject VARCHAR(255) NOT NULL,rendered_html MEDIUMTEXT NOT NULL,status VARCHAR(40) NOT NULL DEFAULT 'owner_pending',sent_at DATETIME NULL,first_viewed_at DATETIME NULL,last_viewed_at DATETIME NULL,signed_at DATETIME NULL,voided_at DATETIME NULL,signer_name VARCHAR(190) NOT NULL DEFAULT '',signer_email VARCHAR(190) NOT NULL DEFAULT '',signature_text VARCHAR(255) NOT NULL DEFAULT '',signature_data MEDIUMTEXT NULL,signer_ip VARCHAR(64) NOT NULL DEFAULT '',signer_user_agent VARCHAR(500) NOT NULL DEFAULT '',created_by_admin_user_id BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_contract_envelope_token(access_token),UNIQUE KEY uq_contract_envelope_owner_token(owner_access_token),KEY idx_contract_envelopes_project(construction_project_id,status,created_at),KEY idx_contract_envelopes_contract(construction_contract_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    if(!db()->query("SHOW COLUMNS FROM construction_contract_envelopes LIKE 'owner_access_token'")->fetchColumn())db()->exec("ALTER TABLE construction_contract_envelopes ADD COLUMN owner_access_token CHAR(64) NULL AFTER access_token,ADD COLUMN owner_name VARCHAR(190) NOT NULL DEFAULT '' AFTER owner_access_token,ADD COLUMN owner_email VARCHAR(190) NOT NULL DEFAULT '' AFTER owner_name,ADD COLUMN owner_signed_at DATETIME NULL AFTER owner_email,ADD COLUMN owner_signature_text VARCHAR(255) NOT NULL DEFAULT '' AFTER owner_signed_at,ADD COLUMN owner_signature_data MEDIUMTEXT NULL AFTER owner_signature_text,ADD COLUMN owner_signer_ip VARCHAR(64) NOT NULL DEFAULT '' AFTER owner_signature_data,ADD COLUMN owner_signer_user_agent VARCHAR(500) NOT NULL DEFAULT '' AFTER owner_signer_ip,ADD UNIQUE KEY uq_contract_envelope_owner_token(owner_access_token)");
    if(!db()->query("SHOW COLUMNS FROM construction_contract_envelopes LIKE 'signature_data'")->fetchColumn())db()->exec("ALTER TABLE construction_contract_envelopes ADD COLUMN signature_data MEDIUMTEXT NULL AFTER signature_text");
    if(!db()->query("SHOW COLUMNS FROM construction_contract_envelopes LIKE 'owner_sent_at'")->fetchColumn())db()->exec("ALTER TABLE construction_contract_envelopes ADD COLUMN owner_sent_at DATETIME NULL AFTER owner_email,ADD COLUMN contractor_sent_at DATETIME NULL AFTER owner_signed_at");
}
function dev_contract_project_team(int $projectId): array
{
    $q=db()->prepare("SELECT pc.id,pc.trade_role,c.company_name,COALESCE(vc.name,NULLIF(pc.project_contact_name,''),c.primary_contact,'') contact_name,COALESCE(vc.email,NULLIF(pc.project_contact_email,''),c.email,'') contact_email,COALESCE(vc.phone,NULLIF(pc.project_contact_phone,''),NULLIF(c.cell_phone,''),c.office_phone,'') contact_phone FROM construction_project_companies pc JOIN construction_companies c ON c.id=pc.construction_company_id LEFT JOIN construction_vendor_contacts vc ON vc.id=CAST(REPLACE(pc.project_contact_name,'contact_id:','') AS UNSIGNED) WHERE pc.construction_project_id=? ORDER BY pc.trade_role,c.company_name");$q->execute([$projectId]);return $q->fetchAll()?:[];
}
function dev_contracts(int $projectId): array
{
    $q=db()->prepare("SELECT ct.*,pc.trade_role,c.company_name,COALESCE(vc.name,NULLIF(pc.project_contact_name,''),c.primary_contact,'') contact_name,COALESCE(vc.email,NULLIF(pc.project_contact_email,''),c.email,'') contact_email,COALESCE(vc.phone,NULLIF(pc.project_contact_phone,''),NULLIF(c.cell_phone,''),c.office_phone,'') contact_phone,(SELECT COALESCE(SUM(e.retainage_amount),0) FROM construction_project_expenses e WHERE e.construction_contract_id=ct.id)+(SELECT COALESCE(SUM(cp.retainage),0) FROM construction_contract_payments cp WHERE cp.construction_contract_id=ct.id AND cp.construction_project_expense_id IS NULL) retainage_collected,(SELECT COALESCE(SUM(e.amount),0) FROM construction_project_expenses e WHERE e.construction_contract_id=ct.id)+(SELECT COALESCE(SUM(cp.amount_paid),0) FROM construction_contract_payments cp WHERE cp.construction_contract_id=ct.id AND cp.construction_project_expense_id IS NULL) total_payments,(SELECT COALESCE(SUM(co.amount),0) FROM construction_contract_change_orders co WHERE co.construction_contract_id=ct.id) change_order_total,ct.original_contract_amount+(SELECT COALESCE(SUM(co.amount),0) FROM construction_contract_change_orders co WHERE co.construction_contract_id=ct.id) new_contract_amount,ct.original_contract_amount+(SELECT COALESCE(SUM(co.amount),0) FROM construction_contract_change_orders co WHERE co.construction_contract_id=ct.id)-((SELECT COALESCE(SUM(e.amount),0) FROM construction_project_expenses e WHERE e.construction_contract_id=ct.id)+(SELECT COALESCE(SUM(cp.amount_paid),0) FROM construction_contract_payments cp WHERE cp.construction_contract_id=ct.id AND cp.construction_project_expense_id IS NULL)) total_balance FROM construction_contracts ct JOIN construction_project_companies pc ON pc.id=ct.construction_project_company_id JOIN construction_companies c ON c.id=pc.construction_company_id LEFT JOIN construction_vendor_contacts vc ON vc.id=CAST(REPLACE(pc.project_contact_name,'contact_id:','') AS UNSIGNED) WHERE ct.construction_project_id=? ORDER BY pc.trade_role,c.company_name,ct.id");$q->execute([$projectId]);return $q->fetchAll()?:[];
}
function dev_contract_payments(int $contractId): array
{
    $q=db()->prepare("SELECT COALESCE(cp.id,0) id,e.id construction_project_expense_id,COALESCE(NULLIF(cp.app_number,''),e.expense_number) app_number,e.amount amount_requested,e.retainage_amount retainage,e.amount amount_paid,e.payment_method,e.expense_date entry_date,'expense' source_type,e.expense_number,e.expense_name FROM construction_project_expenses e LEFT JOIN construction_contract_payments cp ON cp.id=(SELECT MIN(cp2.id) FROM construction_contract_payments cp2 WHERE cp2.construction_project_expense_id=e.id AND cp2.construction_contract_id=e.construction_contract_id) WHERE e.construction_contract_id=? UNION ALL SELECT cp.id,NULL construction_project_expense_id,cp.app_number,cp.amount_requested,cp.retainage,cp.amount_paid,cp.payment_method,cp.entry_date,'legacy' source_type,'' expense_number,'Legacy contract-only payment' expense_name FROM construction_contract_payments cp WHERE cp.construction_contract_id=? AND cp.construction_project_expense_id IS NULL ORDER BY entry_date,id");$q->execute([$contractId,$contractId]);return $q->fetchAll()?:[];
}
function dev_contract_payment_reference_key(string $value): string
{
    $normalized=preg_replace('/[^A-Z0-9]+/','',strtoupper(trim($value)))??'';
    if(preg_match('/^(?:CK|CHECK)?0*(\d+)$/',$normalized,$match))return 'CK'.(string)(int)$match[1];
    return $normalized;
}
function dev_match_contract_payment_expense(int $projectId,int $contractId,float $amountPaid,string $paymentMethod,string $entryDate): ?int
{
    $methodKey=dev_contract_payment_reference_key($paymentMethod);
    if($contractId<=0||$amountPaid<=0||$methodKey===''||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$entryDate))return null;
    $q=db()->prepare('SELECT id,payment_method FROM construction_project_expenses WHERE construction_project_id=? AND construction_contract_id=? AND expense_date=? AND ABS(amount-?)<0.005 ORDER BY id');
    $q->execute([$projectId,$contractId,$entryDate,$amountPaid]);
    $matches=[];foreach($q->fetchAll()?:[] as $expense)if(dev_contract_payment_reference_key((string)$expense['payment_method'])===$methodKey)$matches[]=(int)$expense['id'];
    return count($matches)===1?$matches[0]:null;
}
function dev_match_expense_contract_payment(int $projectId,int $contractId,float $amount,string $paymentMethod,string $expenseDate): ?int
{
    $methodKey=dev_contract_payment_reference_key($paymentMethod);
    if($contractId<=0||$amount<=0||$methodKey===''||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$expenseDate))return null;
    $q=db()->prepare('SELECT cp.id,cp.payment_method FROM construction_contract_payments cp JOIN construction_contracts ct ON ct.id=cp.construction_contract_id WHERE ct.construction_project_id=? AND cp.construction_contract_id=? AND cp.entry_date=? AND ABS(cp.amount_paid-?)<0.005 ORDER BY cp.id');
    $q->execute([$projectId,$contractId,$expenseDate,$amount]);
    $matches=[];foreach($q->fetchAll()?:[] as $payment)if(dev_contract_payment_reference_key((string)$payment['payment_method'])===$methodKey)$matches[]=(int)$payment['id'];
    return count($matches)===1?$matches[0]:null;
}
function dev_sync_contract_payment_expense_references(int $projectId): void
{
    $q=db()->prepare('SELECT cp.id,cp.construction_contract_id,cp.amount_paid,cp.payment_method,cp.entry_date FROM construction_contract_payments cp JOIN construction_contracts ct ON ct.id=cp.construction_contract_id WHERE ct.construction_project_id=? AND cp.construction_project_expense_id IS NULL AND cp.amount_paid>0');
    $q->execute([$projectId]);$update=db()->prepare('UPDATE construction_contract_payments SET construction_project_expense_id=? WHERE id=?');
    foreach($q->fetchAll()?:[] as $payment){$expenseId=dev_match_contract_payment_expense($projectId,(int)$payment['construction_contract_id'],(float)$payment['amount_paid'],(string)$payment['payment_method'],(string)$payment['entry_date']);if($expenseId)$update->execute([$expenseId,(int)$payment['id']]);}
}
function dev_contract_change_orders(int $contractId): array{$q=db()->prepare('SELECT * FROM construction_contract_change_orders WHERE construction_contract_id=? ORDER BY change_order_date,id');$q->execute([$contractId]);return $q->fetchAll()?:[];}
function dev_contract_documents(int $projectId): array{$q=db()->prepare('SELECT d.* FROM construction_contract_documents d JOIN construction_contracts ct ON ct.id=d.construction_contract_id WHERE ct.construction_project_id=? ORDER BY d.document_type,d.expiration_date DESC,d.created_at DESC,d.id DESC');$q->execute([$projectId]);$documents=[];foreach($q->fetchAll()?:[] as $document)$documents[(int)$document['construction_contract_id']][]=$document;return $documents;}
function dev_contract_store_document(array $file,int $projectId,int $contractId,string $type,int $maxBytes=26214400): array
{
    if(($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new RuntimeException('Choose a contract document to upload.');
    if((int)($file['size']??0)>$maxBytes)throw new RuntimeException('The contract document exceeds the 25 MB upload limit.');
    $extension=strtolower(pathinfo((string)($file['name']??''),PATHINFO_EXTENSION));$allowed=['pdf','jpg','jpeg','png','webp'];if(!in_array($extension,$allowed,true))throw new RuntimeException('Contract documents must be PDF, JPG, PNG, or WebP files.');
    $mime='application/octet-stream';if(class_exists('finfo')){$finfo=new finfo(FILEINFO_MIME_TYPE);$detected=$finfo->file((string)($file['tmp_name']??''));if(is_string($detected)&&$detected!=='')$mime=$detected;}$valid=['pdf'=>['application/pdf'],'jpg'=>['image/jpeg'],'jpeg'=>['image/jpeg'],'png'=>['image/png'],'webp'=>['image/webp']];if(!in_array($mime,$valid[$extension],true))throw new RuntimeException('The contract document content does not match its file extension.');
    $folder=$type==='insurance_certificate'?'insurance-certificates':'signed-agreements';$path='uploads/dev/contract-documents/project-'.$projectId.'/contract-'.$contractId.'/'.$folder.'/'.bin2hex(random_bytes(20)).'.'.$extension;znp_storage_store_uploaded_file($path,(string)$file['tmp_name'],$extension,$mime);return ['path'=>$path,'name'=>(string)$file['name'],'mime'=>$mime,'size'=>(int)$file['size']];
}
function dev_contract_template(int $projectId,int $userId=0): array
{
    $q=db()->prepare('SELECT * FROM construction_contract_templates WHERE construction_project_id=?');$q->execute([$projectId]);$template=$q->fetch();if($template)return $template;
    $default='<h1>Subcontractor Agreement</h1><p>This Subcontractor Agreement is entered into for <strong>[PROJECT NAME]</strong>, located at [PROJECT ADDRESS], between ZNP Development and <strong>[CONTRACTOR COMPANY]</strong> for the trade of <strong>[TRADE TYPE]</strong>.</p><h2>Contract Amount</h2><p>The original contract amount is <strong>[ORIGINAL CONTRACT AMOUNT]</strong>.</p><h2>Scope and Terms</h2><p>Enter the agreement scope, payment terms, insurance requirements, schedule obligations, and other terms here.</p><p>Project Contact: [PROJECT CONTACT NAME] · [PROJECT CONTACT EMAIL] · [PROJECT CONTACT PHONE]</p><p>Date Issued: [CURRENT DATE]</p>';
    db()->prepare('INSERT INTO construction_contract_templates(construction_project_id,body_html,created_by_admin_user_id,updated_by_admin_user_id) VALUES(?,?,?,?)')->execute([$projectId,$default,$userId?:null,$userId?:null]);$q->execute([$projectId]);return $q->fetch()?:[];
}
function dev_contract_template_clean_html(string $html): string
{
    $html=mb_substr($html,0,200000);if(!class_exists(DOMDocument::class))return '<p>'.nl2br(htmlspecialchars(strip_tags($html),ENT_QUOTES,'UTF-8')).'</p>';
    $document=new DOMDocument('1.0','UTF-8');libxml_use_internal_errors(true);$document->loadHTML('<?xml encoding="utf-8"?><div id="znp-contract-root">'.$html.'</div>',LIBXML_HTML_NOIMPLIED|LIBXML_HTML_NODEFDTD);libxml_clear_errors();$root=$document->getElementById('znp-contract-root');if(!$root)return '';$allowed=['div','p','br','strong','b','em','i','u','ul','ol','li','h1','h2','h3','a','blockquote','hr','span'];
    $walk=function(DOMNode $node)use(&$walk,$allowed):void{foreach(iterator_to_array($node->childNodes) as $child){if(!($child instanceof DOMElement))continue;$tag=strtolower($child->tagName);if(in_array($tag,['script','style','iframe','object','embed'],true)){$child->parentNode?->removeChild($child);continue;}if(!in_array($tag,$allowed,true)){$fragment=$child->ownerDocument->createDocumentFragment();while($child->firstChild)$fragment->appendChild($child->firstChild);$child->parentNode?->replaceChild($fragment,$child);continue;}foreach(iterator_to_array($child->attributes) as $attribute)if(!($tag==='a'&&$attribute->name==='href'))$child->removeAttribute($attribute->name);if($tag==='a'){if(!preg_match('#^(https?://|mailto:)#i',$child->getAttribute('href')))$child->removeAttribute('href');else{$child->setAttribute('target','_blank');$child->setAttribute('rel','noopener');}}$walk($child);}};$walk($root);$clean='';foreach($root->childNodes as $child)$clean.=$document->saveHTML($child);return trim($clean);
}
function dev_contract_render_template(string $html,array $project,array $contract): string
{
    $address=(string)($project['project_address']??$project['address']??$project['site_address']??'');if($address==='')$address=trim((string)($project['city']??'').((string)($project['state']??'')!==''?', '.$project['state']:''));$ownerName=(string)($project['project_owner_name']??$project['contact_name']??'');$ownerEmail=(string)($project['project_owner_email']??$project['contact_email']??'');$ownerPhone=(string)($project['project_owner_phone']??$project['contact_phone']??'');$values=['[PROJECT NAME]'=>(string)($project['project_name']??''),'[PROJECT ADDRESS]'=>$address,'[PROJECT CITY]'=>(string)($project['city']??''),'[PROJECT STATE]'=>(string)($project['state']??''),'[PROJECT CODE]'=>(string)($project['project_code']??''),'[PROJECT PHASE]'=>(string)($project['phase']??''),'[PROJECT OWNER NAME]'=>$ownerName,'[PROJECT OWNER EMAIL]'=>$ownerEmail,'[PROJECT OWNER PHONE]'=>$ownerPhone,'[PROJECT GC]'=>(string)($project['project_gc']??''),'[PROJECT BANK]'=>(string)($project['project_bank']??''),'[CONTRACTOR COMPANY]'=>(string)($contract['company_name']??''),'[TRADE TYPE]'=>(string)($contract['trade_role']??''),'[CONTRACTOR CONTACT]'=>(string)($contract['contact_name']??''),'[CONTRACTOR EMAIL]'=>(string)($contract['contact_email']??''),'[ORIGINAL CONTRACT AMOUNT]'=>'$'.number_format((float)($contract['original_contract_amount']??0),2),'[CURRENT CONTRACT AMOUNT]'=>'$'.number_format((float)($contract['new_contract_amount']??$contract['original_contract_amount']??0),2),'[PROJECT CONTACT NAME]'=>$ownerName,'[PROJECT CONTACT EMAIL]'=>$ownerEmail,'[PROJECT CONTACT PHONE]'=>$ownerPhone,'[CURRENT DATE]'=>date('F j, Y')];foreach($values as $variable=>$value)$html=str_replace($variable,htmlspecialchars($value,ENT_QUOTES,'UTF-8'),$html);return $html;
}
function dev_contract_envelopes(int $projectId): array{$q=db()->prepare("SELECT e.*,ct.construction_project_company_id,pc.trade_role,c.company_name FROM construction_contract_envelopes e JOIN construction_contracts ct ON ct.id=e.construction_contract_id JOIN construction_project_companies pc ON pc.id=ct.construction_project_company_id JOIN construction_companies c ON c.id=pc.construction_company_id WHERE e.construction_project_id=? ORDER BY e.created_at DESC,e.id DESC");$q->execute([$projectId]);return $q->fetchAll()?:[];}
function dev_contract_sign_url(string $token): string{$configured=rtrim(setting('website_url',''),' /');if($configured!=='')return $configured.'/dev/contract_sign.php?token='.rawurlencode($token);$https=!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off';$host=(string)($_SERVER['HTTP_HOST']??'localhost');$directory=rtrim(str_replace('\\','/',dirname((string)($_SERVER['SCRIPT_NAME']??'/dev/expenses.php'))),'/');return ($https?'https':'http').'://'.$host.$directory.'/contract_sign.php?token='.rawurlencode($token);}
