<?php
declare(strict_types=1);

function dev_render_progress_workflow(int $projectId,int $buildingId,array $project): void
{
    $building=null;
    if($buildingId){
        $s=db()->prepare('SELECT * FROM construction_buildings WHERE id=? AND construction_project_id=? AND is_archived=0');
        $s->execute([$buildingId,$projectId]);
        $building=$s->fetch();
        if(!$building){http_response_code(404);echo '<div class="card notice-error">Building not found.</div>';return;}
    }
    $sql="SELECT csi.*,au.full_name completed_by_name FROM construction_schedule_items csi LEFT JOIN admin_users au ON au.id=csi.completed_by_admin_user_id WHERE csi.construction_project_id=? AND ".($buildingId?'csi.construction_building_id=?':'csi.construction_building_id IS NULL').' ORDER BY csi.sequence_no,csi.id';
    $s=db()->prepare($sql);$args=[$projectId];if($buildingId)$args[]=$buildingId;$s->execute($args);$items=$s->fetchAll();
    $active=array_values(array_filter($items,static fn($item)=>$item['status']!=='Complete'));
    $completed=array_values(array_filter($items,static fn($item)=>$item['status']==='Complete'));
    $progress=dev_schedule_progress($projectId,$buildingId?:null);
    $late=count(array_filter($active,static fn($item)=>!empty($item['planned_finish_date'])&&$item['planned_finish_date']<date('Y-m-d')));
    $attachments=[];
    if($completed){$ids=array_column($completed,'id');$marks=implode(',',array_fill(0,count($ids),'?'));$a=db()->prepare("SELECT * FROM construction_schedule_attachments WHERE schedule_item_id IN ($marks) ORDER BY created_at");$a->execute($ids);foreach($a->fetchAll() as $file)$attachments[(int)$file['schedule_item_id']][]=$file;}
    $scheduleUrl='schedule.php?project_id='.$projectId.($buildingId?'&building_id='.$buildingId:'');
    ?>
    <div class="page-head"><div><h2><?=e($building?$building['building_name'].' Workflow':'Site Workflow')?></h2><p class="muted">Active work stays visible; completed work is archived below.</p></div><div class="actions no-top"><a class="btn btn-primary" href="<?=e($scheduleUrl)?>&add=1">Add Activity</a><a class="btn btn-secondary" href="<?=e($scheduleUrl)?>">Manage Workflow</a></div></div>
    <div class="grid grid-4 schedule-summary"><div class="card metric"><strong><?=$progress?>%</strong><span>Complete</span></div><div class="card metric"><strong><?=count($active)?></strong><span>Active Work</span></div><div class="card metric"><strong><?=count($completed)?></strong><span>Completed</span></div><div class="card metric"><strong><?=$late?></strong><span>Late</span></div></div>
    <?php if(!$items):?><div class="card empty"><p>No workflow activities yet.</p><form method="post" action="<?=e($scheduleUrl)?>"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="project_id" value="<?=$projectId?>"><input type="hidden" name="building_id" value="<?=$buildingId?>"><input type="hidden" name="action" value="initialize"><button class="btn btn-primary">Load Default <?=e($building?'Building':'Project')?> Workflow</button></form></div><?php endif;?>
    <?php if($active):?><section><h2 class="section-title">Active Work</h2><div class="workflow-list"><?php foreach($active as $item):$isLate=!empty($item['planned_finish_date'])&&$item['planned_finish_date']<date('Y-m-d');?><article class="card workflow-card <?=$isLate?'workflow-late':''?> <?=!empty($item['is_inspection'])?'workflow-inspection':''?>"><div class="workflow-main"><div class="workflow-seq"><?=e((string)$item['sequence_no'])?></div><div><h3><?=e($item['activity_name'])?></h3><div class="workflow-meta"><span>Due <?=e(dev_date($item['planned_finish_date']))?></span><span><?=e($item['responsible_party']?:'Unassigned')?></span><span class="badge <?=e(dev_status_class($item['status']))?>"><?=e($item['status'])?></span></div></div></div><div class="workflow-actions"><a class="btn btn-secondary btn-small" href="<?=e($scheduleUrl)?>&edit=<?=(int)$item['id']?>#edit-<?=(int)$item['id']?>">Edit</a><button type="button" class="btn btn-complete btn-small" data-open-modal="progress-complete-<?=(int)$item['id']?>">Mark as Complete</button></div></article><div class="dev-modal" id="progress-complete-<?=(int)$item['id']?>" hidden><div class="dev-modal-panel"><button class="modal-close" type="button" data-close-modal>×</button><h2>Complete Activity</h2><p><strong><?=e($item['activity_name'])?></strong></p><form method="post" enctype="multipart/form-data" action="<?=e($scheduleUrl)?>" class="form-grid"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="project_id" value="<?=$projectId?>"><input type="hidden" name="building_id" value="<?=$buildingId?>"><input type="hidden" name="action" value="complete"><input type="hidden" name="id" value="<?=(int)$item['id']?>"><div><label>Completion Date</label><input type="date" name="completion_date" value="<?=date('Y-m-d')?>" required></div><div><label>Inspection Result</label><select name="inspection_result"><option value="">Not Applicable / Pending</option><option>Passed</option><option>Failed</option><option>Partial</option><option>Reinspection Required</option></select></div><div class="form-full"><label>Completion Notes</label><textarea name="completion_notes"></textarea></div><div class="form-full"><label>Photos or Documents</label><input type="file" name="attachments[]" multiple accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png,.webp"></div><div class="form-full actions"><button class="primary">Complete Activity</button><button type="button" class="btn btn-secondary" data-close-modal>Cancel</button></div></form></div></div><?php endforeach;?></div></section><?php endif;?>
    <section class="completed-section"><button class="completed-toggle" type="button" aria-expanded="false" data-toggle-completed><span>Completed (<?=count($completed)?>)</span><span class="toggle-arrow">▸</span></button><div class="completed-list" hidden><?php foreach($completed as $item):?><article class="card completed-card"><div><h3>✓ <?=e($item['activity_name'])?></h3><p class="muted">Completed <?=e(dev_date($item['actual_finish_date']))?><?=!empty($item['completed_by_name'])?' by '.e($item['completed_by_name']):''?></p><?php if($item['completion_notes']):?><p><?=nl2br(e($item['completion_notes']))?></p><?php endif;?><?php if(!empty($attachments[(int)$item['id']])):?><div class="attachment-list"><?php foreach($attachments[(int)$item['id']] as $file):?><a href="schedule_file.php?id=<?=(int)$file['id']?>" target="_blank">📎 <?=e($file['original_filename'])?></a><?php endforeach;?></div><?php endif;?></div><form method="post" action="<?=e($scheduleUrl)?>"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="project_id" value="<?=$projectId?>"><input type="hidden" name="building_id" value="<?=$buildingId?>"><input type="hidden" name="action" value="reopen"><input type="hidden" name="id" value="<?=(int)$item['id']?>"><button class="btn btn-secondary btn-small" data-confirm="Reopen this activity?">Reopen</button></form></article><?php endforeach;?><?php if(!$completed):?><div class="card empty">No completed activities yet.</div><?php endif;?></div></section>
    <?php
}
